2019-06-26 11:42:07,274 - INFO - register_us.py[:149] - 等待超时，程序终止！
2019-06-26 11:43:34,343 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-06-26 11:44:31,540 - INFO - register_us.py[:215] - 从接口获取的StateOrRegion信息对应不上，默认为下拉列表的第一个州或地区！
2019-06-26 11:44:42,236 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-06-26 11:44:52,586 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-06-26 11:45:10,048 - INFO - register_us.py[:236] - ArnaudeAnnissaa921@gets.fun用户注册成功！
2019-06-26 11:45:10,885 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-06-26 11:45:14,060 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000385E9E57B8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/d2472ef27e1354fa105d707c5282ec05
2019-06-26 11:45:15,074 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000385E7DD780>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/d2472ef27e1354fa105d707c5282ec05
2019-06-26 11:45:16,092 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000385E7DD160>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/d2472ef27e1354fa105d707c5282ec05
2019-06-26 11:46:31,675 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-06-26 11:47:29,714 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-06-26 11:47:39,756 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-06-26 11:47:54,218 - INFO - register_us.py[:236] - ZarolaeVerdaa627@yyw.wiki用户注册成功！
2019-06-26 11:47:55,277 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-06-26 11:47:58,515 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000385E7C9048>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/391d5e07ca3f0bf711bdaad715348d35
2019-06-26 11:47:59,520 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000385EC11E10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/391d5e07ca3f0bf711bdaad715348d35
2019-06-26 11:48:00,538 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000385EC11240>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/391d5e07ca3f0bf711bdaad715348d35
2019-06-26 11:49:48,113 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-06-26 11:51:14,938 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-06-26 11:51:24,957 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-06-26 11:51:46,313 - INFO - register_us.py[:236] - GabeeFairiee589@yyw.link用户注册成功！
2019-06-26 11:51:47,857 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-06-26 11:51:51,316 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000385E9FB3C8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/0875e6c7451d76d4c5e4200ee69b8ddb
2019-06-26 11:51:52,329 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000385E7DDC18>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/0875e6c7451d76d4c5e4200ee69b8ddb
2019-06-26 11:51:53,350 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000385E9E5DA0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/0875e6c7451d76d4c5e4200ee69b8ddb
2019-06-26 11:53:29,067 - INFO - register_us.py[:126] - 注册出错，程序结束！
2019-06-26 11:54:49,653 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-06-26 11:55:55,818 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-06-26 11:56:05,865 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-06-26 11:56:24,922 - INFO - register_us.py[:236] - DeeaDome456@beads.ren用户注册成功！
2019-06-26 11:56:26,011 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-06-26 11:56:29,175 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000385EC31E48>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/47e11a3e121a5495e09dbe32b290b918
2019-06-26 11:56:30,176 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000385EC412E8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/47e11a3e121a5495e09dbe32b290b918
2019-06-26 11:56:31,176 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000385EC41160>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/47e11a3e121a5495e09dbe32b290b918
2019-06-26 11:58:05,866 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-06-26 11:58:59,598 - INFO - register_us.py[:145] - 注册出错，程序结束！
2019-06-26 12:00:42,472 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-06-26 12:02:03,207 - INFO - register_us.py[:215] - 从接口获取的StateOrRegion信息对应不上，默认为下拉列表的第一个州或地区！
2019-06-26 12:02:17,158 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-06-26 12:02:27,209 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-06-26 12:02:53,545 - INFO - register_us.py[:236] - WeseSame648@beads.ink用户注册成功！
2019-06-26 12:02:54,733 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-06-26 12:02:57,867 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000385EC216A0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/b3fb2f08dabbf877cfa6cc95ded80525
2019-06-26 12:02:58,883 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000385EC4ABA8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/b3fb2f08dabbf877cfa6cc95ded80525
2019-06-26 12:02:59,897 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000385EC4A550>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/b3fb2f08dabbf877cfa6cc95ded80525
2019-06-26 12:04:28,669 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-06-26 12:05:31,841 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-06-26 12:05:41,873 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-06-26 12:05:57,722 - INFO - register_us.py[:236] - OthnieleNeraa320@beads.group用户注册成功！
2019-06-26 12:05:58,876 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-06-26 12:06:02,054 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000385EC21278>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/9c7453a91220766539126d02654cbaf0
2019-06-26 12:06:03,059 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000385EC41588>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/9c7453a91220766539126d02654cbaf0
2019-06-26 12:06:04,070 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000385F837CC0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/9c7453a91220766539126d02654cbaf0
2019-06-26 12:11:12,977 - INFO - register_us.py[:149] - 等待超时，程序终止！
2019-06-26 12:11:17,668 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-06-26 12:23:19,320 - INFO - register_us.py[:145] - 注册出错，程序结束！
2019-06-26 12:24:44,503 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-06-26 12:25:44,662 - INFO - register_us.py[:215] - 从接口获取的StateOrRegion信息对应不上，默认为下拉列表的第一个州或地区！
2019-06-26 12:25:54,723 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-06-26 12:26:04,746 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-06-26 12:26:22,570 - INFO - register_us.py[:236] - GwendolyncChloea564@beads.pub用户注册成功！
2019-06-26 12:26:24,080 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-06-26 12:26:28,238 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000385E9E5EF0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/c536ce3712d772a20f3a710d999baf59
2019-06-26 12:26:29,254 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000385E9E5CC0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/c536ce3712d772a20f3a710d999baf59
2019-06-26 12:26:30,255 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000385EC21AC8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/c536ce3712d772a20f3a710d999baf59
2019-06-26 12:27:47,797 - INFO - register_us.py[:126] - 注册出错，程序结束！
2019-06-26 12:32:57,047 - INFO - register_us.py[:149] - 等待超时，程序终止！
2019-06-26 12:34:19,009 - INFO - register_us.py[:126] - 注册出错，程序结束！
2019-06-26 12:35:58,661 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-06-26 12:36:57,587 - INFO - register_us.py[:215] - 从接口获取的StateOrRegion信息对应不上，默认为下拉列表的第一个州或地区！
2019-06-26 12:37:03,692 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-06-26 12:37:13,730 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-06-26 12:37:41,687 - INFO - register_us.py[:236] - DovcMatthiase567@beads.wang用户注册成功！
2019-06-26 12:37:42,885 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-06-26 12:37:46,040 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000385E7DD518>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/495eb2d28066bf570bc53524d89fb3c2
2019-06-26 12:37:47,071 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000385EC412B0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/495eb2d28066bf570bc53524d89fb3c2
2019-06-26 12:37:48,087 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000385EC415C0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/495eb2d28066bf570bc53524d89fb3c2
2019-06-26 12:39:20,650 - INFO - register_us.py[:126] - 注册出错，程序结束！
2019-06-26 12:42:14,260 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-06-26 12:46:07,633 - INFO - register_us.py[:215] - 从接口获取的StateOrRegion信息对应不上，默认为下拉列表的第一个州或地区！
2019-06-26 12:46:53,781 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-06-26 12:47:03,827 - INFO - register_us.py[:122] - 个人信息设置失败！failed,Quit!
2019-06-26 12:48:28,368 - INFO - register_us.py[:126] - 注册出错，程序结束！
2019-06-26 12:50:56,916 - INFO - register_us.py[:145] - 注册出错，程序结束！
2019-06-26 12:53:06,250 - INFO - register_us.py[:126] - 注册出错，程序结束！
2019-06-26 12:58:59,117 - INFO - register_us.py[:149] - 等待超时，程序终止！
2019-06-26 13:05:44,824 - INFO - register_us.py[:145] - 注册出错，程序结束！
2019-06-26 13:07:06,869 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-06-26 13:08:01,877 - INFO - register_us.py[:215] - 从接口获取的StateOrRegion信息对应不上，默认为下拉列表的第一个州或地区！
2019-06-26 13:08:11,600 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-06-26 13:08:21,656 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-06-26 13:08:38,381 - INFO - register_us.py[:236] - LeanneaJudyc345@beads.link用户注册成功！
2019-06-26 13:08:39,159 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-06-26 13:08:43,317 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000385EC31C50>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/6f6c10e1508d00d2434aba57a270fd77
2019-06-26 13:08:44,318 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000385F8372B0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/6f6c10e1508d00d2434aba57a270fd77
2019-06-26 13:08:45,333 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000385F837C50>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/6f6c10e1508d00d2434aba57a270fd77
2019-06-26 13:10:08,728 - INFO - register_us.py[:149] - 等待超时，程序终止！
2019-06-26 13:11:47,634 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-06-26 13:13:42,212 - INFO - register_us.py[:215] - 从接口获取的StateOrRegion信息对应不上，默认为下拉列表的第一个州或地区！
2019-06-26 13:13:52,721 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-06-26 13:14:02,761 - INFO - register_us.py[:122] - 个人信息设置失败！failed,Quit!
2019-06-26 13:15:30,491 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-06-26 13:16:24,882 - INFO - register_us.py[:215] - 从接口获取的StateOrRegion信息对应不上，默认为下拉列表的第一个州或地区！
2019-06-26 13:16:34,082 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-06-26 13:16:44,164 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-06-26 13:17:01,015 - INFO - register_us.py[:236] - EbonyaZabbaic807@beads.name用户注册成功！
2019-06-26 13:17:02,386 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-06-26 13:17:06,548 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000385EC41B70>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/32b4f107e0a278f4a0c50a83d5e445e4
2019-06-26 13:17:07,559 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000385EC31240>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/32b4f107e0a278f4a0c50a83d5e445e4
2019-06-26 13:17:08,563 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000385EC21710>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/32b4f107e0a278f4a0c50a83d5e445e4
2019-06-26 13:22:17,244 - INFO - register_us.py[:149] - 等待超时，程序终止！
2019-06-26 13:27:26,973 - INFO - register_us.py[:149] - 等待超时，程序终止！
2019-06-26 13:29:39,709 - INFO - register_us.py[:145] - 注册出错，程序结束！
2019-06-26 13:35:41,975 - INFO - register_us.py[:149] - 等待超时，程序终止！
2019-06-26 13:37:16,344 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-06-26 13:38:15,467 - INFO - register_us.py[:215] - 从接口获取的StateOrRegion信息对应不上，默认为下拉列表的第一个州或地区！
2019-06-26 13:38:24,923 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-06-26 13:38:34,955 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-06-26 13:38:53,002 - INFO - register_us.py[:236] - WillowePacere582@beads.kim用户注册成功！
2019-06-26 13:38:54,123 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-06-26 13:38:58,330 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000385E7C0CF8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/30929771d6cb6b3f2dba82dff94e5175
2019-06-26 13:38:59,341 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000385E9E5E48>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/30929771d6cb6b3f2dba82dff94e5175
2019-06-26 13:39:00,373 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000385EC31908>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/30929771d6cb6b3f2dba82dff94e5175
2019-06-26 13:39:03,608 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-06-26 13:54:12,488 - INFO - register_us.py[:149] - 等待超时，程序终止！
2019-06-26 13:55:28,380 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-06-26 13:56:20,996 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-06-26 13:56:31,029 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-06-26 13:56:45,719 - INFO - register_us.py[:236] - BerniceeFlourc356@beads.red用户注册成功！
2019-06-26 13:56:46,861 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-06-26 13:56:51,029 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000385EC31F98>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/30596d3c79f6e48d6c1c82f754d2db5c
2019-06-26 13:56:52,062 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000385EC31CC0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/30596d3c79f6e48d6c1c82f754d2db5c
2019-06-26 13:56:53,077 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000385EC31D30>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/30596d3c79f6e48d6c1c82f754d2db5c
2019-06-26 13:58:07,750 - INFO - register_us.py[:126] - 注册出错，程序结束！
2019-06-26 13:58:21,725 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-06-26 14:09:47,761 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-06-26 14:10:42,567 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-06-26 14:10:52,597 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-06-26 14:11:17,089 - INFO - register_us.py[:236] - HidiaUrbana068@anker.site用户注册成功！
2019-06-26 14:11:17,911 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-06-26 14:11:21,068 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000385E9E5FD0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/b1f97a549c958c3626b21ebad12473bf
2019-06-26 14:11:22,085 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000385EC31978>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/b1f97a549c958c3626b21ebad12473bf
2019-06-26 14:11:23,116 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000385EC312B0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/b1f97a549c958c3626b21ebad12473bf
2019-06-26 14:12:54,002 - INFO - register_us.py[:126] - 注册出错，程序结束！
2019-06-26 14:18:51,204 - INFO - register_us.py[:149] - 等待超时，程序终止！
2019-06-26 14:21:10,560 - INFO - register_us.py[:145] - 注册出错，程序结束！
2019-06-26 14:22:24,092 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-06-26 14:23:07,157 - INFO - register_us.py[:215] - 从接口获取的StateOrRegion信息对应不上，默认为下拉列表的第一个州或地区！
2019-06-26 14:23:14,176 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-06-26 14:23:24,895 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-06-26 14:23:38,897 - INFO - register_us.py[:236] - RabieZechariahc016@anker.wiki用户注册成功！
2019-06-26 14:23:39,668 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-06-26 14:23:42,882 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000385EC4ABA8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/dbc7d970ea56ef192980bcc8138f64f5
2019-06-26 14:23:43,908 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000385E9FBB70>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/dbc7d970ea56ef192980bcc8138f64f5
2019-06-26 14:23:44,912 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000385E9FBC50>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/dbc7d970ea56ef192980bcc8138f64f5
2019-06-26 14:24:55,437 - INFO - register_us.py[:126] - 注册出错，程序结束！
2019-06-26 14:26:02,286 - INFO - register_us.py[:126] - 注册出错，程序结束！
2019-06-26 14:27:17,521 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-06-26 14:28:05,527 - INFO - register_us.py[:215] - 从接口获取的StateOrRegion信息对应不上，默认为下拉列表的第一个州或地区！
2019-06-26 14:28:14,667 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-06-26 14:28:24,691 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-06-26 14:28:38,812 - INFO - register_us.py[:236] - HerodcXerxesc327@anker.work用户注册成功！
2019-06-26 14:28:39,899 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-06-26 14:28:44,170 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000385EC41CF8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/b7f41eb55967cc612301ed69602a01d7
2019-06-26 14:28:45,173 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000385EC41B00>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/b7f41eb55967cc612301ed69602a01d7
2019-06-26 14:28:46,177 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000385EC41EF0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/b7f41eb55967cc612301ed69602a01d7
2019-06-26 14:30:36,230 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-06-26 14:31:30,403 - INFO - register_us.py[:215] - 从接口获取的StateOrRegion信息对应不上，默认为下拉列表的第一个州或地区！
2019-06-26 14:31:40,538 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-06-26 14:31:50,567 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-06-26 14:32:08,582 - INFO - register_us.py[:236] - WaldenaVondac763@shein.xin用户注册成功！
2019-06-26 14:32:10,586 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-06-26 14:32:13,719 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000385EC416D8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/76a662bc472f6b4907f6065a2dc57300
2019-06-26 14:32:14,724 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000385EC41D68>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/76a662bc472f6b4907f6065a2dc57300
2019-06-26 14:32:15,724 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000385F8370F0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/76a662bc472f6b4907f6065a2dc57300
2019-06-26 14:35:40,675 - INFO - register_us.py[:145] - 注册出错，程序结束！
2019-06-26 14:38:17,071 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-06-26 14:40:13,620 - INFO - register_us.py[:145] - 注册出错，程序结束！
2019-06-26 14:45:22,857 - INFO - register_us.py[:149] - 等待超时，程序终止！
2019-06-26 14:46:40,375 - INFO - register_us.py[:126] - 注册出错，程序结束！
2019-06-26 14:48:43,911 - INFO - register_us.py[:145] - 注册出错，程序结束！
2019-06-26 14:50:09,469 - INFO - register_us.py[:126] - 注册出错，程序结束！
2019-06-26 14:51:25,319 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-06-26 14:52:12,589 - INFO - register_us.py[:215] - 从接口获取的StateOrRegion信息对应不上，默认为下拉列表的第一个州或地区！
2019-06-26 14:52:18,143 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-06-26 14:52:28,172 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-06-26 14:52:43,002 - INFO - register_us.py[:236] - OshuncLangera123@zaful.biz用户注册成功！
2019-06-26 14:52:43,919 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-06-26 14:52:47,041 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000385EC31278>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/08fbca57c28510b1dd0f8887d90234c9
2019-06-26 14:52:48,045 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000385EC31E10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/08fbca57c28510b1dd0f8887d90234c9
2019-06-26 14:52:49,048 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000385EC41EB8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/08fbca57c28510b1dd0f8887d90234c9
2019-06-26 14:54:10,184 - INFO - register_us.py[:126] - 注册出错，程序结束！
2019-06-26 14:56:15,140 - INFO - register_us.py[:145] - 注册出错，程序结束！
2019-06-26 15:01:24,207 - INFO - register_us.py[:149] - 等待超时，程序终止！
2019-06-26 15:01:29,600 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-06-26 15:12:38,895 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-06-26 15:13:20,497 - INFO - register_us.py[:215] - 从接口获取的StateOrRegion信息对应不上，默认为下拉列表的第一个州或地区！
2019-06-26 15:13:27,742 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-06-26 15:13:37,771 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-06-26 15:13:52,778 - INFO - register_us.py[:236] - UzalaFalkc406@zaful.fun用户注册成功！
2019-06-26 15:13:54,444 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-06-26 15:13:57,617 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000385EC41F28>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/490c30cb195a661b037dcb542e349d4b
2019-06-26 15:13:58,617 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000385EC41CF8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/490c30cb195a661b037dcb542e349d4b
2019-06-26 15:13:59,618 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000385EC41EB8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/490c30cb195a661b037dcb542e349d4b
2019-06-26 15:15:33,898 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-06-26 15:16:46,339 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-06-26 15:16:56,370 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-06-26 15:16:13,833 - INFO - register_us.py[:236] - NeldacMaggiee794@ninebot.tv用户注册成功！
2019-06-26 15:16:15,436 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-06-26 15:16:19,626 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000385F8370F0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/27d596bb58f32f309b05af1b57345737
2019-06-26 15:16:20,642 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000385EC21CC0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/27d596bb58f32f309b05af1b57345737
2019-06-26 15:16:21,658 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000385EC21DA0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/27d596bb58f32f309b05af1b57345737
2019-06-26 15:17:49,660 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-06-26 15:18:54,107 - INFO - register_us.py[:145] - 注册出错，程序结束！
2019-06-26 15:21:04,679 - INFO - register_us.py[:145] - 注册出错，程序结束！
2019-06-26 15:26:14,625 - INFO - register_us.py[:149] - 等待超时，程序终止！
2019-06-26 15:29:39,817 - INFO - register_us.py[:145] - 注册出错，程序结束！
2019-06-26 15:31:09,069 - INFO - register_us.py[:126] - 注册出错，程序结束！
2019-06-26 15:32:32,988 - INFO - register_us.py[:126] - 注册出错，程序结束！
2019-06-26 15:35:18,791 - INFO - register_us.py[:145] - 注册出错，程序结束！
2019-06-26 15:36:50,123 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-06-26 15:37:55,615 - INFO - register_us.py[:215] - 从接口获取的StateOrRegion信息对应不上，默认为下拉列表的第一个州或地区！
2019-06-26 15:38:05,558 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-06-26 15:38:15,584 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-06-26 15:38:35,685 - INFO - register_us.py[:236] - IannacBirgittac143@nineboy.com.cn用户注册成功！
2019-06-26 15:38:36,701 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-06-26 15:38:40,860 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000385F8377B8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/56b11f8b1029ade36dd5fe9dcb11a89a
2019-06-26 15:38:41,868 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000385F837320>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/56b11f8b1029ade36dd5fe9dcb11a89a
2019-06-26 15:38:42,864 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000385F837898>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/56b11f8b1029ade36dd5fe9dcb11a89a
2019-06-26 15:38:45,876 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-06-26 15:50:03,683 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-06-26 15:51:01,120 - INFO - register_us.py[:215] - 从接口获取的StateOrRegion信息对应不上，默认为下拉列表的第一个州或地区！
2019-06-26 15:51:08,190 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-06-26 15:51:18,224 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-06-26 15:51:35,876 - INFO - register_us.py[:236] - EdgarcHebea570@nineboy.top用户注册成功！
2019-06-26 15:51:36,994 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-06-26 15:51:41,145 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000385EC31E48>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/c406df1434c5b818602a27a7b2e3961e
2019-06-26 15:51:42,164 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000385F837128>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/c406df1434c5b818602a27a7b2e3961e
2019-06-26 15:51:43,182 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000385F837978>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/c406df1434c5b818602a27a7b2e3961e
2019-06-26 15:56:50,830 - INFO - register_us.py[:149] - 等待超时，程序终止！
2019-06-26 15:58:25,518 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-06-26 15:59:52,182 - INFO - register_us.py[:215] - 从接口获取的StateOrRegion信息对应不上，默认为下拉列表的第一个州或地区！
2019-06-26 16:00:03,170 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-06-26 16:00:13,212 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-06-26 16:00:40,725 - INFO - register_us.py[:236] - ElgincBabettea273@nineboy.pro用户注册成功！
2019-06-26 16:00:41,537 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-06-26 16:00:44,659 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000385EC31E10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/a2ce5c0cfb248643c6aa299d86e44699
2019-06-26 16:00:45,671 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000385F837A58>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/a2ce5c0cfb248643c6aa299d86e44699
2019-06-26 16:00:46,673 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000385F837198>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/a2ce5c0cfb248643c6aa299d86e44699
2019-06-26 16:04:07,714 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-06-26 16:05:32,479 - INFO - register_us.py[:145] - 注册出错，程序结束！
2019-06-26 16:10:43,276 - INFO - register_us.py[:149] - 等待超时，程序终止！
2019-06-26 16:15:54,836 - INFO - register_us.py[:149] - 等待超时，程序终止！
2019-06-26 16:17:06,016 - INFO - register_us.py[:126] - 注册出错，程序结束！
2019-06-26 16:18:29,042 - INFO - register_us.py[:126] - 注册出错，程序结束！
2019-06-26 16:19:45,739 - INFO - register_us.py[:126] - 注册出错，程序结束！
2019-06-26 16:21:09,589 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-06-26 16:22:14,168 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-06-26 16:22:24,190 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-06-26 16:22:40,806 - INFO - register_us.py[:236] - TameTristone739@nineboy.vip用户注册成功！
2019-06-26 16:22:42,026 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-06-26 16:22:45,199 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000385EC31A20>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/9764995535066f980e0ff4bd1505b74d
2019-06-26 16:22:46,231 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000385E9FB358>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/9764995535066f980e0ff4bd1505b74d
2019-06-26 16:22:47,247 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000385EC4A518>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/9764995535066f980e0ff4bd1505b74d
2019-06-26 16:27:54,983 - INFO - register_us.py[:149] - 等待超时，程序终止！
2019-06-26 16:29:06,033 - INFO - register_us.py[:149] - 等待超时，程序终止！
2019-06-26 16:30:34,474 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-06-26 16:31:59,663 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-06-26 16:32:09,696 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-06-26 16:32:38,487 - INFO - register_us.py[:236] - WynnovecFynballac468@nineboy.net用户注册成功！
2019-06-26 16:32:39,654 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-06-26 16:32:42,780 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000385EC4AFD0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/c7ba5f62fc5b855a0db2f3bd8a0d9e86
2019-06-26 16:32:43,787 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000385EC4A9B0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/c7ba5f62fc5b855a0db2f3bd8a0d9e86
2019-06-26 16:32:44,782 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000385EC4ABE0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/c7ba5f62fc5b855a0db2f3bd8a0d9e86
2019-06-26 16:34:09,472 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-06-26 16:34:58,471 - INFO - register_us.py[:215] - 从接口获取的StateOrRegion信息对应不上，默认为下拉列表的第一个州或地区！
2019-06-26 16:35:07,732 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-06-26 16:35:17,765 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-06-26 16:35:31,758 - INFO - register_us.py[:236] - GraziaeZhermania249@nineboy.cc用户注册成功！
2019-06-26 16:35:32,566 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-06-26 16:35:35,700 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000385F837C88>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/ca3ac8113ece174135d52eb8ead8fc82
2019-06-26 16:35:36,703 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000385EC31940>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/ca3ac8113ece174135d52eb8ead8fc82
2019-06-26 16:35:37,706 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000385E9FBBE0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/ca3ac8113ece174135d52eb8ead8fc82
2019-06-26 16:42:27,930 - INFO - register_us.py[:149] - 等待超时，程序终止！
2019-06-26 16:53:27,796 - INFO - register_us.py[:149] - 等待超时，程序终止！
2019-06-26 16:55:21,810 - INFO - register_us.py[:126] - 注册出错，程序结束！
2019-06-26 17:00:51,619 - INFO - register_us.py[:149] - 等待超时，程序终止！
2019-06-26 17:03:53,916 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-06-26 17:06:39,996 - INFO - register_us.py[:145] - 注册出错，程序结束！
2019-06-26 17:08:32,460 - INFO - register_us.py[:126] - 注册出错，程序结束！
2019-06-26 17:09:54,472 - INFO - register_us.py[:149] - 等待超时，程序终止！
2019-06-26 17:15:58,276 - INFO - register_us.py[:149] - 等待超时，程序终止！
2019-06-26 17:22:16,798 - INFO - register_us.py[:149] - 等待超时，程序终止！
2019-06-26 17:23:29,201 - INFO - register_us.py[:126] - 注册出错，程序结束！
2019-06-26 17:28:38,829 - INFO - register_us.py[:149] - 等待超时，程序终止！
2019-06-26 17:29:51,166 - INFO - register_us.py[:126] - 注册出错，程序结束！
2019-06-26 17:36:43,354 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-06-26 17:41:37,420 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-06-26 17:41:47,435 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-06-26 17:42:53,826 - INFO - register_us.py[:236] - PaisecEmelec841@aukey.live用户注册成功！
2019-06-26 17:42:54,728 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-06-26 17:42:58,923 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000008D3AD6ACF8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/26d4edef41d317dc62801cf3d6738af5
2019-06-26 17:42:59,922 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000008D3AD7DC18>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/26d4edef41d317dc62801cf3d6738af5
2019-06-26 17:43:00,926 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000008D3AD7D748>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/26d4edef41d317dc62801cf3d6738af5
2019-06-26 17:44:28,908 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-06-26 17:45:26,100 - INFO - register_us.py[:215] - 从接口获取的StateOrRegion信息对应不上，默认为下拉列表的第一个州或地区！
2019-06-26 17:45:34,996 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-06-26 17:45:45,026 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-06-26 17:46:21,372 - INFO - register_us.py[:236] - ArchibaldaPoppya537@aukey.fun用户注册成功！
2019-06-26 17:46:22,383 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-06-26 17:46:26,539 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000008D3A9394A8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/1b33e13b272db1b0cb2453c8848a6487
2019-06-26 17:46:27,543 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000008D3AD6AB38>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/1b33e13b272db1b0cb2453c8848a6487
2019-06-26 17:46:28,551 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000008D3AD6A4E0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/1b33e13b272db1b0cb2453c8848a6487
2019-06-26 17:52:25,017 - INFO - register_us.py[:149] - 等待超时，程序终止！
2019-06-26 18:08:28,691 - INFO - register_us.py[:149] - 等待超时，程序终止！
2019-06-26 18:13:40,474 - INFO - register_us.py[:149] - 等待超时，程序终止！
2019-06-26 18:18:52,047 - INFO - register_us.py[:149] - 等待超时，程序终止！
2019-06-26 18:24:03,540 - INFO - register_us.py[:149] - 等待超时，程序终止！
2019-06-26 18:29:29,305 - INFO - register_us.py[:149] - 等待超时，程序终止！
2019-06-26 18:31:10,833 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-06-26 18:32:13,911 - INFO - register_us.py[:215] - 从接口获取的StateOrRegion信息对应不上，默认为下拉列表的第一个州或地区！
2019-06-26 18:32:21,454 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-06-26 18:32:31,488 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-06-26 18:32:51,316 - INFO - register_us.py[:236] - VeaaRonac934@nineboys.store用户注册成功！
2019-06-26 18:32:52,282 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-06-26 18:32:55,449 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C785034E48>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/08c8782808e8524eb1541efff79fb55a
2019-06-26 18:32:56,472 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C7850347B8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/08c8782808e8524eb1541efff79fb55a
2019-06-26 18:32:57,476 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C7850347F0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/08c8782808e8524eb1541efff79fb55a
2019-06-26 18:38:23,872 - INFO - register_us.py[:149] - 等待超时，程序终止！
2019-06-26 18:39:39,187 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-06-26 18:40:30,186 - INFO - register_us.py[:215] - 从接口获取的StateOrRegion信息对应不上，默认为下拉列表的第一个州或地区！
2019-06-26 18:40:39,763 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-06-26 18:40:49,801 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-06-26 18:41:10,047 - INFO - register_us.py[:236] - JosiaheJeannee485@nineboys.art用户注册成功！
2019-06-26 18:41:11,569 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-06-26 18:41:14,718 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C785034748>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/51ffe12b4484059d64b016b4304b8a58
2019-06-26 18:41:15,714 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C784C10080>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/51ffe12b4484059d64b016b4304b8a58
2019-06-26 18:41:16,717 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C784C10320>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/51ffe12b4484059d64b016b4304b8a58
2019-06-26 18:43:02,680 - INFO - register_us.py[:126] - 注册出错，程序结束！
2019-06-26 18:46:14,200 - INFO - register_us.py[:145] - 注册出错，程序结束！
2019-06-26 18:51:30,491 - INFO - register_us.py[:149] - 等待超时，程序终止！
2019-06-26 18:53:11,238 - INFO - register_us.py[:126] - 注册出错，程序结束！
2019-06-26 18:58:24,955 - INFO - register_us.py[:149] - 等待超时，程序终止！
2019-06-26 19:00:04,634 - INFO - register_us.py[:126] - 注册出错，程序结束！
2019-06-26 19:01:40,436 - INFO - register_us.py[:126] - 注册出错，程序结束！
2019-06-26 19:03:12,750 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-06-26 19:04:24,962 - INFO - register_us.py[:145] - 注册出错，程序结束！
2019-06-26 19:05:42,470 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-06-26 19:06:36,361 - INFO - register_us.py[:215] - 从接口获取的StateOrRegion信息对应不上，默认为下拉列表的第一个州或地区！
2019-06-26 19:06:44,013 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-06-26 19:06:54,050 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-06-26 19:07:10,383 - INFO - register_us.py[:236] - ZacheryeAmandae907@nineboys.info用户注册成功！
2019-06-26 19:07:11,214 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-06-26 19:07:14,348 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C785027908>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/9f9fecebaa84708683f1a1f7dfa473fd
2019-06-26 19:07:15,348 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C7850596D8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/9f9fecebaa84708683f1a1f7dfa473fd
2019-06-26 19:07:16,352 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C7850591D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/9f9fecebaa84708683f1a1f7dfa473fd
2019-06-26 19:08:29,370 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-06-26 19:09:23,189 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-06-26 19:09:33,226 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-06-26 19:09:47,835 - INFO - register_us.py[:236] - CaesarcRamsesc589@nineboys.top用户注册成功！
2019-06-26 19:09:48,850 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-06-26 19:09:51,987 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C784C10828>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/690f5afbea1c31d7bb31aad6aa4b85de
2019-06-26 19:09:52,992 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C78503D390>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/690f5afbea1c31d7bb31aad6aa4b85de
2019-06-26 19:09:53,995 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C784C205C0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/690f5afbea1c31d7bb31aad6aa4b85de
2019-06-26 19:09:58,518 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-06-26 19:20:05,260 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-06-26 19:30:33,007 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-06-26 19:40:36,392 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-03 10:00:16,614 - INFO - register_us.py[:145] - 注册出错，程序结束！
2019-07-03 10:05:32,393 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-07-03 10:07:16,085 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-07-03 10:07:26,109 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-03 10:07:38,767 - INFO - register_us.py[:236] - TalbotaMarjoriec931@geabest.online用户注册成功！
2019-07-03 10:07:40,122 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-07-03 10:07:43,285 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CB91AF28>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/be621758d4d6ca012509cc0e7a73f1e3
2019-07-03 10:07:44,307 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CB8FB6A0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/be621758d4d6ca012509cc0e7a73f1e3
2019-07-03 10:07:45,322 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CB8FBE10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/be621758d4d6ca012509cc0e7a73f1e3
2019-07-03 10:09:28,649 - INFO - register_us.py[:126] - 注册出错，程序结束！
2019-07-03 10:11:07,454 - INFO - register_us.py[:126] - 注册出错，程序结束！
2019-07-03 10:12:34,043 - INFO - register_us.py[:126] - 注册出错，程序结束！
2019-07-03 10:13:48,823 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-07-03 10:14:47,787 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-07-03 10:14:57,822 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-03 10:15:10,769 - INFO - register_us.py[:236] - FarrahcAlannae608@geabest.store用户注册成功！
2019-07-03 10:15:12,034 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-07-03 10:15:16,193 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD4CCC0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/555502ab3a116d985fd17d9077faced0
2019-07-03 10:15:17,192 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CB91A550>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/555502ab3a116d985fd17d9077faced0
2019-07-03 10:15:18,194 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CB91A8D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/555502ab3a116d985fd17d9077faced0
2019-07-03 10:20:43,137 - INFO - register_us.py[:149] - 等待超时，程序终止！
2019-07-03 10:26:10,262 - INFO - register_us.py[:149] - 等待超时，程序终止！
2019-07-03 10:27:22,572 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-07-03 10:28:22,832 - INFO - register_us.py[:215] - 从接口获取的StateOrRegion信息对应不上，默认为下拉列表的第一个州或地区！
2019-07-03 10:28:31,067 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-07-03 10:28:41,113 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-03 10:28:54,674 - INFO - register_us.py[:236] - YancycIdumeaa092@gets.vip用户注册成功！
2019-07-03 10:28:55,969 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-07-03 10:28:59,194 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD688D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/8e9e5fccac6eafee88b9c76c3a2d2400
2019-07-03 10:29:00,195 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CB930AC8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/8e9e5fccac6eafee88b9c76c3a2d2400
2019-07-03 10:29:01,203 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CB8FB9B0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/8e9e5fccac6eafee88b9c76c3a2d2400
2019-07-03 10:30:55,156 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-07-03 10:31:51,047 - INFO - register_us.py[:145] - 注册出错，程序结束！
2019-07-03 10:33:09,163 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-07-03 10:33:50,253 - INFO - register_us.py[:215] - 从接口获取的StateOrRegion信息对应不上，默认为下拉列表的第一个州或地区！
2019-07-03 10:33:56,799 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-07-03 10:34:06,832 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-03 10:34:19,623 - INFO - register_us.py[:236] - AbigailcMelec419@gets.fun用户注册成功！
2019-07-03 10:34:21,359 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-07-03 10:34:25,546 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD58828>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/dd94b907e235f15a2a624c18635834c4
2019-07-03 10:34:26,550 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD716D8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/dd94b907e235f15a2a624c18635834c4
2019-07-03 10:34:27,568 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD580B8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/dd94b907e235f15a2a624c18635834c4
2019-07-03 10:39:36,479 - INFO - register_us.py[:149] - 等待超时，程序终止！
2019-07-03 10:41:07,722 - INFO - register_us.py[:126] - 注册出错，程序结束！
2019-07-03 10:46:22,071 - INFO - register_us.py[:149] - 等待超时，程序终止！
2019-07-03 10:47:30,809 - INFO - register_us.py[:126] - 注册出错，程序结束！
2019-07-03 10:48:43,807 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-07-03 10:49:40,952 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-07-03 10:49:50,983 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-03 10:50:04,089 - INFO - register_us.py[:236] - MaddyeIdanac980@yyw.link用户注册成功！
2019-07-03 10:50:06,307 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-07-03 10:50:10,486 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD68898>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/daff589373b0f364918ad920954e86e4
2019-07-03 10:50:11,492 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD4C5F8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/daff589373b0f364918ad920954e86e4
2019-07-03 10:50:12,496 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD4C2B0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/daff589373b0f364918ad920954e86e4
2019-07-03 10:51:20,451 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-07-03 10:52:11,864 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-07-03 10:52:21,900 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-03 10:52:34,549 - INFO - register_us.py[:236] - HadleycJaidena680@beads.ren用户注册成功！
2019-07-03 10:52:35,443 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-07-03 10:52:39,598 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD68828>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/39f9076f1069e802bc757c3f057efcf9
2019-07-03 10:52:40,607 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD68908>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/39f9076f1069e802bc757c3f057efcf9
2019-07-03 10:52:41,614 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD68D30>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/39f9076f1069e802bc757c3f057efcf9
2019-07-03 10:54:07,072 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-07-03 11:04:31,401 - INFO - register_us.py[:149] - 等待超时，程序终止！
2019-07-03 11:05:57,499 - INFO - register_us.py[:126] - 注册出错，程序结束！
2019-07-03 11:07:13,910 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-07-03 11:08:01,529 - INFO - register_us.py[:215] - 从接口获取的StateOrRegion信息对应不上，默认为下拉列表的第一个州或地区！
2019-07-03 11:08:09,746 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-07-03 11:08:19,777 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-03 11:08:34,211 - INFO - register_us.py[:236] - DolfaJohnathane498@beads.group用户注册成功！
2019-07-03 11:08:35,026 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-07-03 11:08:39,177 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD66198>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/06224eb835a1f44ae8853ffdaa731d40
2019-07-03 11:08:40,189 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CB9416A0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/06224eb835a1f44ae8853ffdaa731d40
2019-07-03 11:08:41,197 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CB941898>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/06224eb835a1f44ae8853ffdaa731d40
2019-07-03 11:10:36,799 - INFO - register_us.py[:145] - 注册出错，程序结束！
2019-07-03 11:11:54,496 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-07-03 11:12:50,564 - INFO - register_us.py[:215] - 从接口获取的StateOrRegion信息对应不上，默认为下拉列表的第一个州或地区！
2019-07-03 11:12:56,576 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-07-03 11:12:06,528 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-03 11:12:21,054 - INFO - register_us.py[:236] - KianacJaninae698@beads.pub用户注册成功！
2019-07-03 11:12:21,778 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-07-03 11:12:24,924 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD58A20>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/1d7e0d8548292b38fc20f2214155063b
2019-07-03 11:12:25,927 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD68908>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/1d7e0d8548292b38fc20f2214155063b
2019-07-03 11:12:26,933 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD683C8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/1d7e0d8548292b38fc20f2214155063b
2019-07-03 11:17:34,266 - INFO - register_us.py[:149] - 等待超时，程序终止！
2019-07-03 11:19:02,575 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-07-03 11:20:17,293 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-07-03 11:20:27,332 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-03 11:20:50,074 - INFO - register_us.py[:236] - JanetteaQuinna973@beads.wang用户注册成功！
2019-07-03 11:20:52,623 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-07-03 11:20:55,750 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CB941898>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/882e4514c7379515fdc187f6f078137b
2019-07-03 11:20:56,753 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CB91A240>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/882e4514c7379515fdc187f6f078137b
2019-07-03 11:20:57,755 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD68B38>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/882e4514c7379515fdc187f6f078137b
2019-07-03 11:22:05,700 - INFO - register_us.py[:126] - 注册出错，程序结束！
2019-07-03 11:23:26,285 - INFO - register_us.py[:126] - 注册出错，程序结束！
2019-07-03 11:24:59,213 - INFO - register_us.py[:126] - 注册出错，程序结束！
2019-07-03 11:26:08,790 - INFO - register_us.py[:126] - 注册出错，程序结束！
2019-07-03 11:27:32,008 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-07-03 11:28:42,614 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-07-03 11:28:52,646 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-03 11:29:08,041 - INFO - register_us.py[:236] - KelilaaKylee473@beads.link用户注册成功！
2019-07-03 11:29:08,793 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-07-03 11:29:12,954 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD4C7B8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/3894818339660adeac0097d33dc70c4f
2019-07-03 11:29:13,962 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CB930400>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/3894818339660adeac0097d33dc70c4f
2019-07-03 11:29:14,965 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CB9306A0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/3894818339660adeac0097d33dc70c4f
2019-07-03 11:31:02,863 - INFO - register_us.py[:126] - 注册出错，程序结束！
2019-07-03 11:32:38,841 - INFO - register_us.py[:126] - 注册出错，程序结束！
2019-07-03 11:35:42,490 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-07-03 11:39:14,591 - INFO - register_us.py[:215] - 从接口获取的StateOrRegion信息对应不上，默认为下拉列表的第一个州或地区！
2019-07-03 11:39:45,576 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-07-03 11:39:55,603 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-03 11:40:35,967 - INFO - register_us.py[:236] - MahaliacConniee712@beads.name用户注册成功！
2019-07-03 11:40:37,484 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-07-03 11:40:40,613 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD71978>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/0faf7f048984e0bfad792657960235a1
2019-07-03 11:40:41,617 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD71FD0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/0faf7f048984e0bfad792657960235a1
2019-07-03 11:40:42,622 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD71668>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/0faf7f048984e0bfad792657960235a1
2019-07-03 11:41:53,208 - INFO - register_us.py[:126] - 注册出错，程序结束！
2019-07-03 11:43:05,610 - INFO - register_us.py[:126] - 注册出错，程序结束！
2019-07-03 11:48:15,519 - INFO - register_us.py[:149] - 等待超时，程序终止！
2019-07-03 11:49:25,649 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-07-03 11:50:21,432 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-07-03 11:50:31,474 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-03 11:50:44,180 - INFO - register_us.py[:236] - DennisecGarine846@beads.red用户注册成功！
2019-07-03 11:50:46,073 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-07-03 11:50:49,289 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CB8F3668>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/fd9ee2f8be0a650933d9f346bd7243e2
2019-07-03 11:50:50,305 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD71E80>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/fd9ee2f8be0a650933d9f346bd7243e2
2019-07-03 11:50:51,337 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD71240>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/fd9ee2f8be0a650933d9f346bd7243e2
2019-07-03 11:52:06,512 - INFO - register_us.py[:126] - 注册出错，程序结束！
2019-07-03 11:53:42,362 - INFO - register_us.py[:145] - 注册出错，程序结束！
2019-07-03 11:55:33,463 - INFO - register_us.py[:126] - 注册出错，程序结束！
2019-07-03 12:00:42,987 - INFO - register_us.py[:149] - 等待超时，程序终止！
2019-07-03 12:02:47,698 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-07-03 12:03:47,330 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-07-03 12:03:57,372 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-03 12:04:37,718 - INFO - register_us.py[:236] - ViviettecReidc682@anker.work用户注册成功！
2019-07-03 12:04:38,953 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-07-03 12:04:42,106 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD68B38>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/0520b3e5fe595b4812d83e54df70f714
2019-07-03 12:04:43,108 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD68160>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/0520b3e5fe595b4812d83e54df70f714
2019-07-03 12:04:44,109 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD68FD0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/0520b3e5fe595b4812d83e54df70f714
2019-07-03 12:06:48,029 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-07-03 12:07:44,022 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-07-03 12:07:54,074 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-03 12:08:07,900 - INFO - register_us.py[:236] - VitaliseRhetta962@shein.xin用户注册成功！
2019-07-03 12:08:09,044 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-07-03 12:08:13,562 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD68E80>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/57f3320093a869a5788038b87589e8d6
2019-07-03 12:08:14,565 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD586D8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/57f3320093a869a5788038b87589e8d6
2019-07-03 12:08:15,573 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD58240>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/57f3320093a869a5788038b87589e8d6
2019-07-03 12:09:29,197 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-07-03 12:10:23,390 - INFO - register_us.py[:215] - 从接口获取的StateOrRegion信息对应不上，默认为下拉列表的第一个州或地区！
2019-07-03 12:10:30,995 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-07-03 12:10:41,030 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-03 12:10:54,476 - INFO - register_us.py[:236] - VirginaeGalinac560@shein.wang用户注册成功！
2019-07-03 12:10:55,510 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-07-03 12:10:58,654 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CB8FBE10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/84d6291e8407616bd890372bb3470a77
2019-07-03 12:10:59,656 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CB8FB630>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/84d6291e8407616bd890372bb3470a77
2019-07-03 12:11:00,663 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CB930400>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/84d6291e8407616bd890372bb3470a77
2019-07-03 12:12:40,546 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-07-03 12:13:48,503 - INFO - register_us.py[:215] - 从接口获取的StateOrRegion信息对应不上，默认为下拉列表的第一个州或地区！
2019-07-03 12:19:03,275 - INFO - register_us.py[:149] - 等待超时，程序终止！
2019-07-03 12:20:35,678 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-07-03 12:22:00,826 - INFO - register_us.py[:215] - 从接口获取的StateOrRegion信息对应不上，默认为下拉列表的第一个州或地区！
2019-07-03 12:22:10,498 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-07-03 12:22:20,530 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-03 12:22:53,890 - INFO - register_us.py[:236] - PrentiscJonia943@zaful.mobi用户注册成功！
2019-07-03 12:22:54,811 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-07-03 12:22:58,056 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBB84B70>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/5704c9f514f2174f5453fa8973dadba5
2019-07-03 12:22:59,059 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBB906A0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/5704c9f514f2174f5453fa8973dadba5
2019-07-03 12:23:00,060 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBB901D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/5704c9f514f2174f5453fa8973dadba5
2019-07-03 12:24:12,087 - INFO - register_us.py[:126] - 注册出错，程序结束！
2019-07-03 12:29:22,929 - INFO - register_us.py[:149] - 等待超时，程序终止！
2019-07-03 12:30:37,313 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-07-03 12:31:41,418 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-07-03 12:31:51,459 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-03 12:32:33,045 - INFO - register_us.py[:236] - XaviorcDimaa648@zaful.biz用户注册成功！
2019-07-03 12:32:34,081 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-07-03 12:32:37,233 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CB91A390>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/0e57ede53da034cd78e51e030eebe770
2019-07-03 12:32:38,232 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD719B0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/0e57ede53da034cd78e51e030eebe770
2019-07-03 12:32:39,252 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD71EB8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/0e57ede53da034cd78e51e030eebe770
2019-07-03 12:34:17,766 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-07-03 12:39:36,989 - INFO - register_us.py[:145] - 注册出错，程序结束！
2019-07-03 12:45:05,750 - INFO - register_us.py[:149] - 等待超时，程序终止！
2019-07-03 12:46:18,786 - INFO - register_us.py[:126] - 注册出错，程序结束！
2019-07-03 12:52:03,262 - INFO - register_us.py[:149] - 等待超时，程序终止！
2019-07-03 12:57:14,144 - INFO - register_us.py[:149] - 等待超时，程序终止！
2019-07-03 13:00:18,179 - INFO - register_us.py[:145] - 注册出错，程序结束！
