2019-06-26 14:24:31,136 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-06-26 14:25:28,299 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-06-26 14:25:38,333 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-06-26 14:25:58,843 - INFO - register_de.py[:223] - OznieLandync607@anker.wiki用户注册成功！
2019-06-26 14:26:00,285 - INFO - register_de.py[:256] - 注册信息已成功入库！
2019-06-26 14:26:03,443 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000572367ABA8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/f0dff6bec0be17673ae026251f797ea8
2019-06-26 14:26:04,459 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000005723890080>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/f0dff6bec0be17673ae026251f797ea8
2019-06-26 14:26:05,490 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000005723890C50>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/f0dff6bec0be17673ae026251f797ea8
2019-06-26 14:27:53,797 - INFO - register_de.py[:123] - 注册出错，程序结束！
2019-06-26 14:29:07,264 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-06-26 14:34:58,042 - INFO - register_de.py[:127] - 等待超时，程序终止！
2019-06-26 14:36:09,284 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-06-26 14:37:36,190 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-06-26 14:38:24,664 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-06-26 14:38:34,691 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-06-26 14:38:49,138 - INFO - register_de.py[:223] - NydiacJayc127@shein.wang用户注册成功！
2019-06-26 14:38:50,568 - INFO - register_de.py[:256] - 注册信息已成功入库！
2019-06-26 14:38:54,699 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000572345D898>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/924aa36bd4151ae9fccd8267fe6523b2
2019-06-26 14:38:55,705 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000057238A8160>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/924aa36bd4151ae9fccd8267fe6523b2
2019-06-26 14:38:56,706 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000572345D0F0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/924aa36bd4151ae9fccd8267fe6523b2
2019-06-26 14:40:31,218 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-06-26 14:41:16,182 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-06-26 14:41:26,212 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-06-26 14:41:39,750 - INFO - register_de.py[:223] - JineAlannae693@shein.kim用户注册成功！
2019-06-26 14:41:41,007 - INFO - register_de.py[:256] - 注册信息已成功入库！
2019-06-26 14:41:44,134 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000572345DEF0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/fc334a2b1c2e20aca2641cda057740bf
2019-06-26 14:41:45,137 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000572367A6D8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/fc334a2b1c2e20aca2641cda057740bf
2019-06-26 14:41:46,139 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000572367A240>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/fc334a2b1c2e20aca2641cda057740bf
2019-06-26 14:43:23,189 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-06-26 14:46:20,778 - INFO - register_de.py[:123] - 注册出错，程序结束！
2019-06-26 14:47:33,965 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-06-26 14:48:14,422 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-06-26 14:48:24,466 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-06-26 14:48:39,885 - INFO - register_de.py[:223] - VyroneDamiana716@zaful.mobi用户注册成功！
2019-06-26 14:48:41,447 - INFO - register_de.py[:256] - 注册信息已成功入库！
2019-06-26 14:48:45,631 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000057236645F8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/e6930d319bc2cc4c3c77c60f3eb58aed
2019-06-26 14:48:46,647 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000057236647B8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/e6930d319bc2cc4c3c77c60f3eb58aed
2019-06-26 14:48:47,648 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000005723664518>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/e6930d319bc2cc4c3c77c60f3eb58aed
2019-06-26 14:54:35,374 - INFO - register_de.py[:127] - 等待超时，程序终止！
2019-06-26 14:56:36,635 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-06-26 14:58:27,747 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-06-26 14:58:37,779 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-06-26 14:59:17,941 - INFO - register_de.py[:223] - ZachryaAbbia496@zaful.xyz用户注册成功！
2019-06-26 14:59:18,946 - INFO - register_de.py[:256] - 注册信息已成功入库！
2019-06-26 14:59:23,098 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000005723664E80>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/00f9edadcdec247d461a68204fefa551
2019-06-26 14:59:24,108 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000005723890F60>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/00f9edadcdec247d461a68204fefa551
2019-06-26 14:59:25,120 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000005723890518>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/00f9edadcdec247d461a68204fefa551
2019-06-26 15:04:54,440 - INFO - register_de.py[:127] - 等待超时，程序终止！
2019-06-26 15:06:10,266 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-06-26 15:07:24,903 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-06-26 15:08:06,148 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-06-26 15:08:16,192 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-06-26 15:08:30,687 - INFO - register_de.py[:223] - UriaHartc081@zaful.net.cn用户注册成功！
2019-06-26 15:08:31,474 - INFO - register_de.py[:256] - 注册信息已成功入库！
2019-06-26 15:08:34,617 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000057238B17B8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/d1b51737e1fee460f8bbfb5b3c51f119
2019-06-26 15:08:35,649 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000572367A6D8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/d1b51737e1fee460f8bbfb5b3c51f119
2019-06-26 15:08:36,664 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000005723448D30>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/d1b51737e1fee460f8bbfb5b3c51f119
2019-06-26 15:09:54,400 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-06-26 15:10:42,176 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-06-26 15:10:52,222 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-06-26 15:11:09,726 - INFO - register_de.py[:223] - ZereshaVinaa789@zaful.work用户注册成功！
2019-06-26 15:11:11,697 - INFO - register_de.py[:256] - 注册信息已成功入库！
2019-06-26 15:11:14,809 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000057238C9978>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/aeb765dc4cd18fe603c47e8a797f8732
2019-06-26 15:11:15,840 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000572345D438>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/aeb765dc4cd18fe603c47e8a797f8732
2019-06-26 15:11:16,871 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000572345D828>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/aeb765dc4cd18fe603c47e8a797f8732
2019-06-26 15:11:21,389 - INFO - register_de.py[:330] - 当前无注册任务，程序[sleep 10m]...
2019-06-26 15:21:28,928 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-06-26 15:26:40,696 - INFO - register_de.py[:127] - 等待超时，程序终止！
2019-06-26 15:27:58,105 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-06-26 15:28:44,154 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-06-26 15:28:54,185 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-06-26 15:29:11,106 - INFO - register_de.py[:223] - GertieeWaltraude862@ninebot.ltd用户注册成功！
2019-06-26 15:29:13,156 - INFO - register_de.py[:256] - 注册信息已成功入库！
2019-06-26 15:29:17,315 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000057238A8908>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/90ebe361a9e63cf3349a7c5ee9d003d4
2019-06-26 15:29:18,333 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000057238A85F8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/90ebe361a9e63cf3349a7c5ee9d003d4
2019-06-26 15:29:19,347 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000057238A8D30>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/90ebe361a9e63cf3349a7c5ee9d003d4
2019-06-26 15:30:30,741 - INFO - register_de.py[:127] - 等待超时，程序终止！
2019-06-26 15:32:04,681 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-06-26 15:33:35,216 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-06-26 15:33:45,314 - INFO - register_de.py[:100] - 个人信息设置失败！failed,Quit!
2019-06-26 15:35:56,339 - INFO - register_de.py[:123] - 注册出错，程序结束！
2019-06-26 15:41:06,778 - INFO - register_de.py[:127] - 等待超时，程序终止！
2019-06-26 15:42:41,618 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-06-26 15:44:52,626 - INFO - register_de.py[:123] - 注册出错，程序结束！
2019-06-26 15:46:04,156 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-06-26 15:48:15,936 - INFO - register_de.py[:123] - 注册出错，程序结束！
2019-06-26 15:49:45,770 - INFO - register_de.py[:127] - 等待超时，程序终止！
2019-06-26 15:51:06,776 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-06-26 15:51:58,515 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-06-26 15:52:08,572 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-06-26 15:52:32,567 - INFO - register_de.py[:223] - LethaaHunigc651@nineboy.top用户注册成功！
2019-06-26 15:52:33,772 - INFO - register_de.py[:256] - 注册信息已成功入库！
2019-06-26 15:52:37,896 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000057238B1C50>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/c4938717608e49c8a680e017ebae42cd
2019-06-26 15:52:38,899 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000057238904A8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/c4938717608e49c8a680e017ebae42cd
2019-06-26 15:52:39,904 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000057238B1978>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/c4938717608e49c8a680e017ebae42cd
2019-06-26 15:54:31,364 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-06-26 15:56:27,360 - INFO - register_de.py[:123] - 注册出错，程序结束！
2019-06-26 15:58:11,175 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-06-26 15:59:27,974 - INFO - register_de.py[:123] - 注册出错，程序结束！
2019-06-26 16:02:03,989 - INFO - register_de.py[:123] - 注册出错，程序结束！
2019-06-26 16:04:09,547 - INFO - register_de.py[:123] - 注册出错，程序结束！
2019-06-26 16:05:19,909 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-06-26 16:06:47,243 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-06-26 16:07:33,026 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-06-26 16:07:43,064 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-06-26 16:07:57,331 - INFO - register_de.py[:223] - LeoneIric309@nineboy.site用户注册成功！
2019-06-26 16:07:58,696 - INFO - register_de.py[:256] - 注册信息已成功入库！
2019-06-26 16:08:02,854 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000057238B20F0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/9f84c3b9dfe20ecbbcd26beca1e01a82
2019-06-26 16:08:03,859 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000057238B2358>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/9f84c3b9dfe20ecbbcd26beca1e01a82
2019-06-26 16:08:04,852 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000057238B22E8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/9f84c3b9dfe20ecbbcd26beca1e01a82
2019-06-26 16:09:17,479 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-06-26 16:10:42,626 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-06-26 16:13:20,037 - INFO - register_de.py[:123] - 注册出错，程序结束！
2019-06-26 16:14:36,449 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-06-26 16:16:07,939 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-06-26 16:17:22,367 - INFO - register_de.py[:123] - 注册出错，程序结束！
2019-06-26 16:20:31,646 - INFO - register_de.py[:123] - 注册出错，程序结束！
2019-06-26 16:23:07,440 - INFO - register_de.py[:123] - 注册出错，程序结束！
2019-06-26 16:24:35,347 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-06-26 16:25:34,095 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-06-26 16:25:44,125 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-06-26 16:26:11,517 - INFO - register_de.py[:223] - NanciaCleavea325@nineboy.biz用户注册成功！
2019-06-26 16:26:14,076 - INFO - register_de.py[:256] - 注册信息已成功入库！
2019-06-26 16:26:17,213 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000057238C92B0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/d2dcc332f2a46976ae9b8f3bb6f05468
2019-06-26 16:26:18,221 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000057238A8470>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/d2dcc332f2a46976ae9b8f3bb6f05468
2019-06-26 16:26:19,222 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000005723890F28>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/d2dcc332f2a46976ae9b8f3bb6f05468
2019-06-26 16:30:01,450 - INFO - register_de.py[:123] - 注册出错，程序结束！
2019-06-26 16:31:29,505 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-06-26 16:36:38,640 - INFO - register_de.py[:127] - 等待超时，程序终止！
2019-06-26 16:38:07,818 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-06-26 16:48:58,357 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-06-26 16:54:41,438 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-06-26 16:56:52,476 - INFO - register_de.py[:123] - 注册出错，程序结束！
2019-06-26 17:02:16,821 - INFO - register_de.py[:127] - 等待超时，程序终止！
2019-06-26 17:03:52,097 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-06-26 17:05:23,885 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-06-26 17:06:15,789 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-06-26 17:06:25,825 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-06-26 17:06:45,287 - INFO - register_de.py[:223] - IlsecPattie716@aukey.online用户注册成功！
2019-06-26 17:06:46,139 - INFO - register_de.py[:256] - 注册信息已成功入库！
2019-06-26 17:06:49,327 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007F0ED6BA90>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/5ee3e700e2f5623772973af3b97a029c
2019-06-26 17:06:50,327 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007F0E91A748>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/5ee3e700e2f5623772973af3b97a029c
2019-06-26 17:06:51,328 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007F0E91AE10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/5ee3e700e2f5623772973af3b97a029c
2019-06-26 17:08:13,898 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-06-26 17:09:36,814 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-06-26 17:11:19,481 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-06-26 17:13:00,785 - INFO - register_de.py[:123] - 注册出错，程序结束！
2019-06-26 17:18:07,379 - INFO - register_de.py[:123] - 注册出错，程序结束！
2019-06-26 17:20:20,811 - INFO - register_de.py[:123] - 注册出错，程序结束！
2019-06-26 17:25:40,093 - INFO - register_de.py[:123] - 注册出错，程序结束！
2019-06-26 17:28:23,340 - INFO - register_de.py[:123] - 注册出错，程序结束！
2019-06-26 17:29:33,020 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-06-26 17:35:29,753 - INFO - register_de.py[:127] - 等待超时，程序终止！
2019-06-26 17:37:59,456 - INFO - register_de.py[:123] - 注册出错，程序结束！
2019-06-26 17:39:18,573 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-06-26 17:40:36,783 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-06-26 17:41:15,390 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-06-26 17:41:25,425 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-06-26 17:41:40,182 - INFO - register_de.py[:223] - ArtemiseLaWanaa928@aukey.live用户注册成功！
2019-06-26 17:41:41,259 - INFO - register_de.py[:256] - 注册信息已成功入库！
2019-06-26 17:41:45,450 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007F0EB81828>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/5a51f73a18ac9ebe6c499688911d3293
2019-06-26 17:41:46,465 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007F0EB283C8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/5a51f73a18ac9ebe6c499688911d3293
2019-06-26 17:41:47,488 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007F0EB81198>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/5a51f73a18ac9ebe6c499688911d3293
2019-06-26 17:47:36,012 - INFO - register_de.py[:127] - 等待超时，程序终止！
2019-06-26 17:48:55,429 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-06-26 17:50:55,834 - INFO - register_de.py[:127] - 等待超时，程序终止！
2019-06-26 17:51:01,766 - INFO - register_de.py[:330] - 当前无注册任务，程序[sleep 10m]...
2019-06-26 17:58:03,046 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-06-26 17:59:03,826 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-06-26 17:59:13,863 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-06-26 17:59:35,380 - INFO - register_de.py[:223] - RobbieeWendsya576@aukey.ltd用户注册成功！
2019-06-26 17:59:37,586 - INFO - register_de.py[:256] - 注册信息已成功入库！
2019-06-26 17:59:40,728 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C19D0CE588>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/495674d93de70ec78ae214cf5e9aa941
2019-06-26 17:59:41,744 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C19D0CE4E0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/495674d93de70ec78ae214cf5e9aa941
2019-06-26 17:59:42,761 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C19D2EB0F0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/495674d93de70ec78ae214cf5e9aa941
2019-06-26 18:00:57,517 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-06-26 18:01:44,548 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-06-26 18:01:54,591 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-06-26 18:02:08,241 - INFO - register_de.py[:223] - PammeliaZenea528@aukey.net.cn用户注册成功！
2019-06-26 18:02:08,929 - INFO - register_de.py[:256] - 注册信息已成功入库！
2019-06-26 18:02:12,118 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C19CE9A710>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/5bb2286252dedd152452cba21f448ec8
2019-06-26 18:02:13,119 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C19D0CEA20>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/5bb2286252dedd152452cba21f448ec8
2019-06-26 18:02:14,150 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C19D0CEDA0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/5bb2286252dedd152452cba21f448ec8
2019-06-26 18:03:40,684 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-06-26 18:05:08,534 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-06-26 18:06:19,764 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-06-26 18:07:39,547 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-06-26 18:08:50,270 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-06-26 18:09:30,824 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-06-26 18:09:40,855 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-06-26 18:09:55,869 - INFO - register_de.py[:223] - KeshiaaLaszloc436@aukey.mobi用户注册成功！
2019-06-26 18:10:01,253 - INFO - register_de.py[:256] - 注册信息已成功入库！
2019-06-26 18:10:04,575 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C19D30BD68>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/a637bc4bb18b66a078de2a7c59f42f87
2019-06-26 18:10:05,578 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C19D30D240>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/a637bc4bb18b66a078de2a7c59f42f87
2019-06-26 18:10:06,581 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C19D311908>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/a637bc4bb18b66a078de2a7c59f42f87
2019-06-26 18:11:40,435 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-06-26 18:12:34,030 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-06-26 18:12:44,060 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-06-26 18:13:01,757 - INFO - register_de.py[:223] - IvalynaParkera246@nineboys.co用户注册成功！
2019-06-26 18:13:04,195 - INFO - register_de.py[:256] - 注册信息已成功入库！
2019-06-26 18:13:07,343 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C19B9D56D8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/f9df9af0964677cbdca44e5cc8452a77
2019-06-26 18:13:08,348 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C19D0C0F60>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/f9df9af0964677cbdca44e5cc8452a77
2019-06-26 18:13:09,347 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C19D0C0898>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/f9df9af0964677cbdca44e5cc8452a77
2019-06-26 18:14:49,464 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-06-26 18:16:09,987 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-06-26 18:21:27,476 - INFO - register_de.py[:127] - 等待超时，程序终止！
2019-06-26 18:26:37,120 - INFO - register_de.py[:127] - 等待超时，程序终止！
2019-06-26 18:27:54,552 - INFO - register_de.py[:127] - 等待超时，程序终止！
2019-06-26 18:33:57,307 - INFO - register_de.py[:127] - 等待超时，程序终止！
2019-06-26 18:35:35,398 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-06-26 18:36:47,038 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-06-26 18:42:09,488 - INFO - register_de.py[:127] - 等待超时，程序终止！
2019-06-26 18:47:23,499 - INFO - register_de.py[:127] - 等待超时，程序终止！
2019-06-26 18:50:04,417 - INFO - register_de.py[:123] - 注册出错，程序结束！
2019-06-26 18:52:20,692 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-06-26 18:53:26,849 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-06-26 18:53:36,878 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-06-26 18:54:17,056 - INFO - register_de.py[:223] - NahoreEdiee821@nineboys.site用户注册成功！
2019-06-26 18:54:19,993 - INFO - register_de.py[:256] - 注册信息已成功入库！
2019-06-26 18:54:23,117 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C19D311C18>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/6941001e971f5aba255b00386e4520a3
2019-06-26 18:54:24,121 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C19D3110F0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/6941001e971f5aba255b00386e4520a3
2019-06-26 18:54:25,124 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C19D3110B8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/6941001e971f5aba255b00386e4520a3
2019-06-26 18:55:40,097 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-06-26 18:56:54,692 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-06-26 18:57:04,723 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-06-26 18:57:21,343 - INFO - register_de.py[:223] - LenoraeNikitaa720@nineboys.pro用户注册成功！
2019-06-26 18:57:22,157 - INFO - register_de.py[:256] - 注册信息已成功入库！
2019-06-26 18:57:25,309 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C19D2FE0B8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/36b970b175db2d164189a4839cdf5bca
2019-06-26 18:57:26,321 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C19D2FEF28>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/36b970b175db2d164189a4839cdf5bca
2019-06-26 18:57:27,325 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C19D2FEB38>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/36b970b175db2d164189a4839cdf5bca
2019-06-26 18:58:53,895 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-06-26 18:59:41,339 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-06-26 18:59:51,364 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-06-26 19:00:05,686 - INFO - register_de.py[:223] - GeorgiacOceane754@nineboys.org用户注册成功！
2019-06-26 19:00:07,698 - INFO - register_de.py[:256] - 注册信息已成功入库！
2019-06-26 19:00:10,840 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C19D30D160>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/852a51127a78fd82b8a441aa2a92c786
2019-06-26 19:00:11,862 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C19D0CE6D8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/852a51127a78fd82b8a441aa2a92c786
2019-06-26 19:00:12,888 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C19D0CEBE0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/852a51127a78fd82b8a441aa2a92c786
2019-06-26 19:05:21,200 - INFO - register_de.py[:127] - 等待超时，程序终止！
2019-06-26 19:10:36,583 - INFO - register_de.py[:127] - 等待超时，程序终止！
2019-06-26 19:13:21,032 - INFO - register_de.py[:123] - 注册出错，程序结束！
2019-06-26 19:14:43,252 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-06-26 19:16:38,462 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-06-26 19:18:42,300 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-06-26 19:18:52,329 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-06-26 19:19:07,922 - INFO - register_de.py[:223] - RyancRosalbaa803@nineboys.tech用户注册成功！
2019-06-26 19:19:09,359 - INFO - register_de.py[:256] - 注册信息已成功入库！
2019-06-26 19:19:12,516 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C19D30DD30>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/999742dfda2144eae2afe0bdb2c2206a
2019-06-26 19:19:13,517 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C19D2EB1D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/999742dfda2144eae2afe0bdb2c2206a
2019-06-26 19:19:14,533 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C19D30D668>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/999742dfda2144eae2afe0bdb2c2206a
2019-06-26 19:20:48,668 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-06-26 19:22:29,709 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-06-26 19:23:22,848 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-06-26 19:23:32,871 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-06-26 19:23:50,713 - INFO - register_de.py[:223] - TavecRandolpha379@nineboys.ltd用户注册成功！
2019-06-26 19:23:51,692 - INFO - register_de.py[:256] - 注册信息已成功入库！
2019-06-26 19:23:55,865 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C19D2EBF28>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/22a460b7537528205258c8d16cc925b0
2019-06-26 19:23:56,882 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C19CE92940>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/22a460b7537528205258c8d16cc925b0
2019-06-26 19:23:57,898 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C19CE92710>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/22a460b7537528205258c8d16cc925b0
2019-06-26 19:25:07,036 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-06-26 19:26:48,819 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-06-26 19:28:15,544 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-06-26 19:29:49,661 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-06-26 19:30:40,069 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-06-26 19:30:50,103 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-06-26 19:31:06,174 - INFO - register_de.py[:223] - OsmonteRansoma695@nineboys.group用户注册成功！
2019-06-26 19:31:07,332 - INFO - register_de.py[:256] - 注册信息已成功入库！
2019-06-26 19:31:11,491 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C19D30B160>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/2107f07dd2f385a8db968f8d9e8ef044
2019-06-26 19:31:12,523 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C19D30B5C0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/2107f07dd2f385a8db968f8d9e8ef044
2019-06-26 19:31:13,539 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C19D2EB588>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/2107f07dd2f385a8db968f8d9e8ef044
2019-06-26 19:32:40,624 - INFO - register_de.py[:127] - 等待超时，程序终止！
2019-06-26 19:34:05,716 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-06-26 19:35:31,241 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-06-26 19:36:58,052 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-06-26 19:37:38,278 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-06-26 19:37:48,319 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-06-26 19:38:02,569 - INFO - register_de.py[:223] - JaniaeOctaviae743@nineboys.xyz用户注册成功！
2019-06-26 19:38:04,923 - INFO - register_de.py[:256] - 注册信息已成功入库！
2019-06-26 19:38:09,081 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C19CE929B0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/2a72d0f570807bab70c186043eea0760
2019-06-26 19:38:10,097 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C19D0CE710>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/2a72d0f570807bab70c186043eea0760
2019-06-26 19:38:11,097 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C19D0CEA58>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/2a72d0f570807bab70c186043eea0760
2019-06-26 19:39:22,256 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-06-26 19:40:34,579 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-06-26 19:43:12,961 - INFO - register_de.py[:123] - 注册出错，程序结束！
2019-06-26 19:45:02,990 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-06-26 19:47:50,692 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-06-26 19:48:32,949 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-06-26 19:48:42,986 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-06-26 19:48:59,276 - INFO - register_de.py[:223] - GrabielaeSimona621@nineboys.cn用户注册成功！
2019-06-26 19:49:02,898 - INFO - register_de.py[:256] - 注册信息已成功入库！
2019-06-26 19:49:07,062 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C19D0C0AC8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/929b3eabcece45a8b28d57f08bf6fa14
2019-06-26 19:49:08,079 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C19D30D390>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/929b3eabcece45a8b28d57f08bf6fa14
2019-06-26 19:49:09,079 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C19D30D160>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/929b3eabcece45a8b28d57f08bf6fa14
2019-06-26 19:54:57,625 - INFO - register_de.py[:127] - 等待超时，程序终止！
2019-06-26 19:56:48,377 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-06-26 19:58:03,100 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-06-26 19:58:45,921 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-06-26 19:58:55,967 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-06-26 19:59:13,148 - INFO - register_de.py[:223] - AabbyeeOrelc596@nineboys.club用户注册成功！
2019-06-26 19:59:14,825 - INFO - register_de.py[:256] - 注册信息已成功入库！
2019-06-26 19:59:18,999 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C19D14CE10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/0240f5c310044bf3d9a0ad253066877d
2019-06-26 19:59:20,015 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C19D14C390>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/0240f5c310044bf3d9a0ad253066877d
2019-06-26 19:59:21,031 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C19D159A90>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/0240f5c310044bf3d9a0ad253066877d
2019-06-26 20:02:21,851 - INFO - register_de.py[:123] - 注册出错，程序结束！
2019-06-26 20:05:03,875 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-06-26 20:06:31,226 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-06-26 20:06:41,252 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-06-26 20:07:49,286 - INFO - register_de.py[:223] - MarvcIbneiahc718@nineboys.fun用户注册成功！
2019-06-26 20:07:50,652 - INFO - register_de.py[:256] - 注册信息已成功入库！
2019-06-26 20:07:53,825 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C19D151B70>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/77bc38d2f7311115603026336ae128c4
2019-06-26 20:07:54,842 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C19D311710>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/77bc38d2f7311115603026336ae128c4
2019-06-26 20:07:55,858 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C19D1510F0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/77bc38d2f7311115603026336ae128c4
2019-06-26 20:14:07,194 - INFO - register_de.py[:127] - 等待超时，程序终止！
2019-06-26 20:15:35,088 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-06-26 20:16:17,843 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-06-26 20:16:27,876 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-06-26 20:16:43,918 - INFO - register_de.py[:223] - StarlingcTyrona984@nineboy.club用户注册成功！
2019-06-26 20:16:45,151 - INFO - register_de.py[:256] - 注册信息已成功入库！
2019-06-26 20:16:48,308 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C19D30B860>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/cfd0d1a5247923198eff1879c9d277ad
2019-06-26 20:16:49,308 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C19D30D400>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/cfd0d1a5247923198eff1879c9d277ad
2019-06-26 20:16:50,340 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C19D14C358>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/cfd0d1a5247923198eff1879c9d277ad
2019-06-26 20:18:28,746 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-06-26 20:19:32,065 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-06-26 20:19:42,298 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-06-26 20:20:04,628 - INFO - register_de.py[:223] - ThembaeDulciea502@nineboy.co用户注册成功！
2019-06-26 20:20:11,319 - INFO - register_de.py[:256] - 注册信息已成功入库！
2019-06-26 20:20:15,881 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C19D30BFD0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/5db6d09eabf47dff47fc11ebdf5ea3a2
2019-06-26 20:20:16,888 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C19D0A8F60>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/5db6d09eabf47dff47fc11ebdf5ea3a2
2019-06-26 20:20:17,891 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C19D0A8828>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/5db6d09eabf47dff47fc11ebdf5ea3a2
2019-06-26 20:21:52,770 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-06-26 20:22:49,952 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-06-26 20:22:59,984 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-06-26 20:23:16,987 - INFO - register_de.py[:223] - LloydeDulceaa391@nineboy.store用户注册成功！
2019-06-26 20:23:21,573 - INFO - register_de.py[:256] - 注册信息已成功入库！
2019-06-26 20:23:25,740 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C19D2EB320>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/f9401d8d496df47741c0fa3dd32e7b18
2019-06-26 20:23:26,752 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C19D159FD0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/f9401d8d496df47741c0fa3dd32e7b18
2019-06-26 20:23:27,752 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C19D151F60>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/f9401d8d496df47741c0fa3dd32e7b18
2019-06-26 20:24:44,258 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-06-26 20:27:21,364 - INFO - register_de.py[:123] - 注册出错，程序结束！
2019-06-26 20:30:19,229 - INFO - register_de.py[:123] - 注册出错，程序结束！
2019-06-26 20:31:53,182 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-06-26 20:33:57,801 - INFO - register_de.py[:123] - 注册出错，程序结束！
2019-06-26 20:35:34,335 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-06-26 20:40:44,169 - INFO - register_de.py[:127] - 等待超时，程序终止！
2019-06-26 20:46:32,397 - INFO - register_de.py[:127] - 等待超时，程序终止！
2019-06-26 20:51:43,638 - INFO - register_de.py[:127] - 等待超时，程序终止！
2019-06-26 20:53:11,432 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-06-26 20:54:01,827 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-06-26 20:54:11,859 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-06-26 20:54:29,832 - INFO - register_de.py[:223] - AlizeaAnnaliesee251@nineboy.group用户注册成功！
2019-06-26 20:54:31,278 - INFO - register_de.py[:256] - 注册信息已成功入库！
2019-06-26 20:54:35,428 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C19D14CDA0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/dcf76010ba17efdd60965ab4a05030db
2019-06-26 20:54:36,422 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C19D311748>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/dcf76010ba17efdd60965ab4a05030db
2019-06-26 20:54:37,425 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C19D311A58>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/dcf76010ba17efdd60965ab4a05030db
2019-06-26 20:56:44,055 - INFO - register_de.py[:123] - 注册出错，程序结束！
2019-06-26 20:58:21,528 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-06-26 21:04:12,640 - INFO - register_de.py[:127] - 等待超时，程序终止！
2019-06-26 21:05:51,341 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-06-26 21:06:44,080 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-06-26 21:06:54,107 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-06-26 21:07:11,127 - INFO - register_de.py[:223] - VikieMarciac539@nineboy.ltd用户注册成功！
2019-06-26 21:07:12,641 - INFO - register_de.py[:256] - 注册信息已成功入库！
2019-06-26 21:07:15,786 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C19D159DA0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/95d9a35fb2416a52e631ed6ca8244d75
2019-06-26 21:07:16,788 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C19D14CFD0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/95d9a35fb2416a52e631ed6ca8244d75
2019-06-26 21:07:17,786 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C19D14CC88>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/95d9a35fb2416a52e631ed6ca8244d75
2019-06-26 21:08:30,566 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-06-26 21:09:10,113 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-06-26 21:09:20,146 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-06-26 21:09:35,506 - INFO - register_de.py[:223] - OdellacHerodc368@nineboy.art用户注册成功！
2019-06-26 21:09:53,036 - INFO - register_de.py[:256] - 注册信息已成功入库！
2019-06-26 21:09:56,138 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C19D0A87F0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/882ce7c690b9727210a0778781569eb1
2019-06-26 21:09:57,134 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C19CE92978>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/882ce7c690b9727210a0778781569eb1
2019-06-26 21:09:58,141 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C19CE92BA8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/882ce7c690b9727210a0778781569eb1
2019-06-26 21:12:46,102 - INFO - register_de.py[:123] - 注册出错，程序结束！
2019-06-26 21:18:30,654 - INFO - register_de.py[:127] - 等待超时，程序终止！
2019-06-26 21:19:46,447 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-06-26 21:20:27,710 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-06-26 21:20:37,740 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-06-26 21:20:51,168 - INFO - register_de.py[:223] - KishacOhadc218@geabest.club用户注册成功！
2019-06-26 21:20:52,099 - INFO - register_de.py[:256] - 注册信息已成功入库！
2019-06-26 21:20:56,240 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C19D174080>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/b7f10d9d34622346e2ddb283639086b0
2019-06-26 21:20:57,247 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C19D174710>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/b7f10d9d34622346e2ddb283639086b0
2019-06-26 21:20:58,242 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C19D159358>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/b7f10d9d34622346e2ddb283639086b0
2019-06-26 21:22:48,369 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-06-26 21:23:58,158 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-06-26 21:24:08,208 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-06-26 21:24:25,462 - INFO - register_de.py[:223] - OmareQuixotee432@geabest.ltd用户注册成功！
2019-06-26 21:24:27,381 - INFO - register_de.py[:256] - 注册信息已成功入库！
2019-06-26 21:24:30,544 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C19D14C0F0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/2c3b8bf2a86767e83fcc2303fb073f1d
2019-06-26 21:24:31,552 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C19D14C9B0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/2c3b8bf2a86767e83fcc2303fb073f1d
2019-06-26 21:24:32,562 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C19D14CE48>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/2c3b8bf2a86767e83fcc2303fb073f1d
2019-06-26 21:29:42,364 - INFO - register_de.py[:127] - 等待超时，程序终止！
2019-06-26 21:34:50,443 - INFO - register_de.py[:127] - 等待超时，程序终止！
2019-06-26 21:36:18,100 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-06-26 21:37:37,519 - INFO - register_de.py[:127] - 等待超时，程序终止！
2019-06-26 21:38:49,931 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-06-26 21:43:59,516 - INFO - register_de.py[:127] - 等待超时，程序终止！
2019-06-26 21:49:11,693 - INFO - register_de.py[:127] - 等待超时，程序终止！
2019-06-26 21:52:02,893 - INFO - register_de.py[:123] - 注册出错，程序结束！
2019-06-26 21:54:16,743 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-06-26 21:55:08,496 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-06-26 21:55:18,535 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-06-26 21:55:39,529 - INFO - register_de.py[:223] - WafacRangera523@geabest.info用户注册成功！
2019-06-26 21:55:44,048 - INFO - register_de.py[:256] - 注册信息已成功入库！
2019-06-26 21:55:48,182 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C19D159C50>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/5537c17b2cac29a05894c687728a9028
2019-06-26 21:55:49,186 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C19D30DB70>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/5537c17b2cac29a05894c687728a9028
2019-06-26 21:55:50,194 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C19D30D2E8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/5537c17b2cac29a05894c687728a9028
2019-06-26 21:58:10,063 - INFO - register_de.py[:123] - 注册出错，程序结束！
2019-06-26 21:59:59,368 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-06-26 22:01:41,244 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-06-26 22:01:51,282 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-06-26 22:02:18,897 - INFO - register_de.py[:223] - WhitbycWilmae237@geabest.pro用户注册成功！
2019-06-26 22:02:23,780 - INFO - register_de.py[:256] - 注册信息已成功入库！
2019-06-26 22:02:26,922 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C19D30BF60>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/ad4e0846f93aa8edf4c0bca18486b73f
2019-06-26 22:02:27,938 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C19D1748D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/ad4e0846f93aa8edf4c0bca18486b73f
2019-06-26 22:02:28,938 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C19D159198>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/ad4e0846f93aa8edf4c0bca18486b73f
2019-06-26 22:03:49,961 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-06-26 22:06:27,303 - INFO - register_de.py[:123] - 注册出错，程序结束！
2019-06-26 22:11:38,728 - INFO - register_de.py[:127] - 等待超时，程序终止！
2019-06-26 22:13:02,168 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-06-26 22:14:57,808 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-06-26 22:20:07,611 - INFO - register_de.py[:127] - 等待超时，程序终止！
2019-06-26 22:21:42,335 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-06-26 22:22:31,424 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-06-26 22:22:41,444 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-06-26 22:23:00,250 - INFO - register_de.py[:223] - ZeldacFidellaa213@geabest.mobi用户注册成功！
2019-06-26 22:23:01,496 - INFO - register_de.py[:256] - 注册信息已成功入库！
2019-06-26 22:23:05,717 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C19D1749E8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/e299143eafbad2c07444aa25064bc075
2019-06-26 22:23:06,733 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C19D30BD68>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/e299143eafbad2c07444aa25064bc075
2019-06-26 22:23:07,764 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C19D30BCC0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/e299143eafbad2c07444aa25064bc075
2019-06-26 22:28:47,589 - INFO - register_de.py[:127] - 等待超时，程序终止！
2019-06-26 22:31:35,822 - INFO - register_de.py[:123] - 注册出错，程序结束！
2019-06-26 22:33:00,569 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-06-26 22:33:45,582 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-06-26 22:33:55,621 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-06-26 22:34:12,103 - INFO - register_de.py[:223] - WaltoneEffiee428@geabest.com.cn用户注册成功！
2019-06-26 22:34:14,517 - INFO - register_de.py[:256] - 注册信息已成功入库！
2019-06-26 22:34:18,659 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C19D151A20>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/4597e73b85f847e7ad03031fac9983cd
2019-06-26 22:34:19,691 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C19D0CE2E8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/4597e73b85f847e7ad03031fac9983cd
2019-06-26 22:34:20,706 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C19D0CE828>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/4597e73b85f847e7ad03031fac9983cd
2019-06-26 22:35:44,680 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-06-26 22:37:01,722 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-06-26 22:38:24,441 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-06-26 22:39:07,850 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-06-26 22:39:17,877 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-06-26 22:39:33,489 - INFO - register_de.py[:223] - DaisyaZekie105@geabest.cc用户注册成功！
2019-06-26 22:39:34,798 - INFO - register_de.py[:256] - 注册信息已成功入库！
2019-06-26 22:39:38,972 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C19D30B588>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/842f8a127fd8ae1736a23f187c70cea2
2019-06-26 22:39:40,003 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C19D2FEA20>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/842f8a127fd8ae1736a23f187c70cea2
2019-06-26 22:39:41,019 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C19D0C0630>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/842f8a127fd8ae1736a23f187c70cea2
2019-06-26 22:40:04,497 - INFO - register_de.py[:330] - 当前无注册任务，程序[sleep 10m]...
2019-06-26 22:50:09,544 - INFO - register_de.py[:330] - 当前无注册任务，程序[sleep 10m]...
2019-06-26 23:00:21,187 - INFO - register_de.py[:330] - 当前无注册任务，程序[sleep 10m]...
2019-06-26 23:10:25,499 - INFO - register_de.py[:330] - 当前无注册任务，程序[sleep 10m]...
2019-06-26 23:20:31,265 - INFO - register_de.py[:330] - 当前无注册任务，程序[sleep 10m]...
2019-07-03 09:59:17,607 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-07-03 10:00:26,968 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-07-03 10:00:36,999 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-07-03 10:00:53,500 - INFO - register_de.py[:223] - FrankcKimballa549@geabest.online用户注册成功！
2019-07-03 10:00:56,245 - INFO - register_de.py[:256] - 注册信息已成功入库！
2019-07-03 10:00:59,372 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007715CA15C0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/1db439a89c14fbf38587ae4426ab2b73
2019-07-03 10:01:00,382 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007715CA1A90>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/1db439a89c14fbf38587ae4426ab2b73
2019-07-03 10:01:01,389 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000077160AC390>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/1db439a89c14fbf38587ae4426ab2b73
2019-07-03 10:02:47,976 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-03 10:05:16,933 - INFO - register_de.py[:123] - 注册出错，程序结束！
2019-07-03 10:06:50,044 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-07-03 10:07:42,895 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-07-03 10:07:52,914 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-07-03 10:08:12,316 - INFO - register_de.py[:223] - RonaldaHarrietc967@geabest.vip用户注册成功！
2019-07-03 10:08:13,359 - INFO - register_de.py[:256] - 注册信息已成功入库！
2019-07-03 10:08:16,508 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000077160BD2E8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/56f990bd159e94b1eed025ffe8608a81
2019-07-03 10:08:17,514 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007715C91B70>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/56f990bd159e94b1eed025ffe8608a81
2019-07-03 10:08:18,516 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007715CA19E8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/56f990bd159e94b1eed025ffe8608a81
2019-07-03 10:12:15,711 - INFO - register_de.py[:123] - 注册出错，程序结束！
2019-07-03 10:13:44,109 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-03 10:17:01,935 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-07-03 10:19:41,410 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-07-03 10:19:51,454 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-07-03 10:20:34,796 - INFO - register_de.py[:223] - TevincRhodae463@geabest.store用户注册成功！
2019-07-03 10:20:35,957 - INFO - register_de.py[:256] - 注册信息已成功入库！
2019-07-03 10:20:39,079 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000077160AC828>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/996fc96e69b816a1ffc900d94fc28ccd
2019-07-03 10:20:40,082 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007715C91B38>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/996fc96e69b816a1ffc900d94fc28ccd
2019-07-03 10:20:41,087 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007715C91DD8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/996fc96e69b816a1ffc900d94fc28ccd
2019-07-03 10:22:06,032 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-03 10:23:15,388 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-07-03 10:23:57,542 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-07-03 10:24:07,571 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-07-03 10:24:20,805 - INFO - register_de.py[:223] - FrewencJimmyc812@yyw.ltd用户注册成功！
2019-07-03 10:24:21,798 - INFO - register_de.py[:256] - 注册信息已成功入库！
2019-07-03 10:24:25,934 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007715C53F98>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/7d04ba5788d6d7afb070cb2189f244ad
2019-07-03 10:24:26,937 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007715CA1BE0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/7d04ba5788d6d7afb070cb2189f244ad
2019-07-03 10:24:27,944 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007715CA1EB8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/7d04ba5788d6d7afb070cb2189f244ad
2019-07-03 10:26:36,953 - INFO - register_de.py[:123] - 注册出错，程序结束！
2019-07-03 10:27:59,848 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-03 10:29:46,154 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-03 10:31:39,197 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-07-03 10:32:32,548 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-07-03 10:32:42,583 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-07-03 10:33:04,594 - INFO - register_de.py[:223] - KierstencAnyae301@gets.fun用户注册成功！
2019-07-03 10:33:05,946 - INFO - register_de.py[:256] - 注册信息已成功入库！
2019-07-03 10:33:09,132 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000077160CFE48>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/4720d4c625e40b6b76b207855099f87c
2019-07-03 10:33:10,133 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000077160ACB38>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/4720d4c625e40b6b76b207855099f87c
2019-07-03 10:33:11,137 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000077160ACB00>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/4720d4c625e40b6b76b207855099f87c
2019-07-03 10:35:19,816 - INFO - register_de.py[:123] - 注册出错，程序结束！
2019-07-03 10:36:15,544 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-07-03 10:36:55,802 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-07-03 10:37:05,833 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-07-03 10:37:21,674 - INFO - register_de.py[:223] - RickeycDalite987@yyw.wiki用户注册成功！
2019-07-03 10:37:23,586 - INFO - register_de.py[:256] - 注册信息已成功入库！
2019-07-03 10:37:27,736 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000077160CFEB8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/77cf885e7c922ac405af51b8f719d7c1
2019-07-03 10:37:28,735 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000077160CFA90>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/77cf885e7c922ac405af51b8f719d7c1
2019-07-03 10:37:29,739 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000077160CFA58>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/77cf885e7c922ac405af51b8f719d7c1
2019-07-03 10:39:11,833 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-07-03 10:47:31,939 - INFO - register_de.py[:127] - 等待超时，程序终止！
2019-07-03 10:48:47,852 - INFO - register_de.py[:127] - 等待超时，程序终止！
2019-07-03 10:53:59,079 - INFO - register_de.py[:127] - 等待超时，程序终止！
2019-07-03 10:55:16,773 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-03 10:56:25,654 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-03 10:58:35,164 - INFO - register_de.py[:123] - 注册出错，程序结束！
2019-07-03 10:59:44,842 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-03 11:01:01,795 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-03 11:02:22,130 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-07-03 11:03:08,817 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-07-03 11:03:18,856 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-07-03 11:03:37,164 - INFO - register_de.py[:223] - DamonaaBeryle178@beads.ink用户注册成功！
2019-07-03 11:03:38,298 - INFO - register_de.py[:256] - 注册信息已成功入库！
2019-07-03 11:03:41,435 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007715CA1A90>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/4e3a907dccb11c024c1f5fd416fa508e
2019-07-03 11:03:42,432 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000077160DA3C8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/4e3a907dccb11c024c1f5fd416fa508e
2019-07-03 11:03:43,440 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000077160DAF60>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/4e3a907dccb11c024c1f5fd416fa508e
2019-07-03 11:04:54,011 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-03 11:06:02,460 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-03 11:07:57,148 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-03 11:10:35,923 - INFO - register_de.py[:123] - 注册出错，程序结束！
2019-07-03 11:15:01,273 - INFO - register_de.py[:127] - 等待超时，程序终止！
2019-07-03 11:20:13,952 - INFO - register_de.py[:127] - 等待超时，程序终止！
2019-07-03 11:25:24,486 - INFO - register_de.py[:127] - 等待超时，程序终止！
2019-07-03 11:26:53,586 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-07-03 11:28:17,327 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-07-03 11:28:27,372 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-07-03 11:29:17,082 - INFO - register_de.py[:223] - BartramcAmira531@beads.link用户注册成功！
2019-07-03 11:29:17,886 - INFO - register_de.py[:256] - 注册信息已成功入库！
2019-07-03 11:29:21,025 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007715C79320>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/a5387fe9582c7127bb0c0655120a99eb
2019-07-03 11:29:22,047 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000077160DA0B8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/a5387fe9582c7127bb0c0655120a99eb
2019-07-03 11:29:23,053 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000077160DA198>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/a5387fe9582c7127bb0c0655120a99eb
2019-07-03 11:30:46,797 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-03 11:31:57,056 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-03 11:34:09,638 - INFO - register_de.py[:123] - 注册出错，程序结束！
2019-07-03 11:35:20,080 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-03 11:36:28,718 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-03 11:37:39,376 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-03 11:43:25,749 - INFO - register_de.py[:127] - 等待超时，程序终止！
2019-07-03 11:44:41,233 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-07-03 11:45:38,434 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-07-03 11:45:48,477 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-07-03 11:46:05,409 - INFO - register_de.py[:223] - KalebaXavierc051@beads.kim用户注册成功！
2019-07-03 11:46:15,979 - INFO - register_de.py[:256] - 注册信息已成功入库！
2019-07-03 11:46:20,124 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007716937F98>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/1e09cc094a5eb420c9fb303be6668083
2019-07-03 11:46:21,119 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000077160DADD8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/1e09cc094a5eb420c9fb303be6668083
2019-07-03 11:46:22,125 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007716937E48>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/1e09cc094a5eb420c9fb303be6668083
2019-07-03 11:47:46,856 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-03 11:49:26,227 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-03 11:50:52,634 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-03 11:52:18,623 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-07-03 11:53:12,750 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-07-03 11:53:22,778 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-07-03 11:53:41,351 - INFO - register_de.py[:223] - HallaQuinlana058@anker.site用户注册成功！
2019-07-03 11:53:42,635 - INFO - register_de.py[:256] - 注册信息已成功入库！
