2019-07-15 15:20:49,147 - INFO - review_us_pool.py[:486] - ********************************pool sleep 3s************************************
2019-07-15 15:20:50,913 - INFO - review_us_pool.py[:480] - 成功获取到1条待评论的数据！
2019-07-15 15:22:20,805 - INFO - review_us_pool.py[:246] - [taskid: 2235]等待超时,或者元素位未完全加载导致定位出错!
2019-07-15 15:22:20,805 - INFO - review_us_pool.py[:247] - [taskid: 2235]关闭当前浏览器，结束当前线程！
2019-07-15 15:22:20,805 - INFO - review_us_pool.py[:248] - [taskid: 2235]系统会自动生成新的线程来执行留评任务！
2019-07-15 15:22:27,043 - INFO - review_us_pool.py[:486] - ********************************pool sleep 3s************************************
2019-07-15 15:22:28,730 - INFO - review_us_pool.py[:480] - 成功获取到1条待评论的数据！
2019-07-15 15:24:03,276 - INFO - review_us_pool.py[:417] - [taskid: 2235]账户登录日志已成功插入！
2019-07-15 15:24:06,606 - INFO - review_us_pool.py[:423] - [taskid: 2235]对应账户的header和cookies字段已成功修改!
2019-07-15 15:24:32,597 - INFO - review_us_pool.py[:201] - [taskid: 2235]找到目标订单所在的tbody!
2019-07-15 15:24:32,680 - INFO - review_us_pool.py[:238] - [taskid: 2235]卖家尚未发货，暂时不能留评，程序退出！
2019-07-15 15:24:35,835 - INFO - review_us_pool.py[:242] - [taskid: 2235]当前账户操作完毕，关闭当前浏览器！
2019-07-15 15:24:36,850 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C07A5A1CC0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/f4a5c1e102ddf1c1b78ec65109dd3441
2019-07-15 15:24:37,882 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C07ABA5358>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/f4a5c1e102ddf1c1b78ec65109dd3441
2019-07-15 15:24:38,898 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C07ABA55C0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/f4a5c1e102ddf1c1b78ec65109dd3441
2019-07-15 15:24:42,994 - INFO - review_us_pool.py[:486] - ********************************pool sleep 3s************************************
2019-07-15 15:24:44,306 - INFO - review_us_pool.py[:480] - 成功获取到1条待评论的数据！
2019-07-15 15:28:47,894 - INFO - review_us_pool.py[:246] - [taskid: 2235]等待超时,或者元素位未完全加载导致定位出错!
2019-07-15 15:28:47,894 - INFO - review_us_pool.py[:247] - [taskid: 2235]关闭当前浏览器，结束当前线程！
2019-07-15 15:28:47,894 - INFO - review_us_pool.py[:248] - [taskid: 2235]系统会自动生成新的线程来执行留评任务！
2019-07-15 15:28:53,193 - INFO - review_us_pool.py[:486] - ********************************pool sleep 3s************************************
2019-07-15 15:28:53,818 - INFO - review_us_pool.py[:480] - 成功获取到1条待评论的数据！
2019-07-15 15:32:15,731 - INFO - review_us_pool.py[:246] - [taskid: 2235]等待超时,或者元素位未完全加载导致定位出错!
2019-07-15 15:32:15,731 - INFO - review_us_pool.py[:247] - [taskid: 2235]关闭当前浏览器，结束当前线程！
2019-07-15 15:32:15,731 - INFO - review_us_pool.py[:248] - [taskid: 2235]系统会自动生成新的线程来执行留评任务！
2019-07-15 15:32:22,045 - INFO - review_us_pool.py[:486] - ********************************pool sleep 3s************************************
2019-07-15 15:32:25,609 - INFO - review_us_pool.py[:480] - 成功获取到1条待评论的数据！
2019-07-15 15:35:58,838 - INFO - review_us_pool.py[:246] - [taskid: 2235]等待超时,或者元素位未完全加载导致定位出错!
2019-07-15 15:35:58,838 - INFO - review_us_pool.py[:247] - [taskid: 2235]关闭当前浏览器，结束当前线程！
2019-07-15 15:35:58,838 - INFO - review_us_pool.py[:248] - [taskid: 2235]系统会自动生成新的线程来执行留评任务！
2019-07-15 15:36:04,121 - INFO - review_us_pool.py[:486] - ********************************pool sleep 3s************************************
2019-07-15 15:36:05,903 - INFO - review_us_pool.py[:480] - 成功获取到1条待评论的数据！
2019-07-15 15:38:39,804 - INFO - review_us_pool.py[:246] - [taskid: 2235]等待超时,或者元素位未完全加载导致定位出错!
2019-07-15 15:38:39,805 - INFO - review_us_pool.py[:247] - [taskid: 2235]关闭当前浏览器，结束当前线程！
2019-07-15 15:38:39,805 - INFO - review_us_pool.py[:248] - [taskid: 2235]系统会自动生成新的线程来执行留评任务！
2019-07-15 15:38:46,104 - INFO - review_us_pool.py[:486] - ********************************pool sleep 3s************************************
2019-07-15 15:38:47,166 - INFO - review_us_pool.py[:480] - 成功获取到1条待评论的数据！
2019-07-15 15:39:56,795 - INFO - review_us_pool.py[:246] - [taskid: 2235]等待超时,或者元素位未完全加载导致定位出错!
2019-07-15 15:39:56,796 - INFO - review_us_pool.py[:247] - [taskid: 2235]关闭当前浏览器，结束当前线程！
2019-07-15 15:39:56,797 - INFO - review_us_pool.py[:248] - [taskid: 2235]系统会自动生成新的线程来执行留评任务！
2019-07-15 15:40:03,146 - INFO - review_us_pool.py[:486] - ********************************pool sleep 3s************************************
2019-07-15 15:40:03,676 - INFO - review_us_pool.py[:480] - 成功获取到1条待评论的数据！
2019-07-15 15:41:27,480 - INFO - review_us_pool.py[:246] - [taskid: 2235]等待超时,或者元素位未完全加载导致定位出错!
2019-07-15 15:41:27,480 - INFO - review_us_pool.py[:247] - [taskid: 2235]关闭当前浏览器，结束当前线程！
2019-07-15 15:41:27,480 - INFO - review_us_pool.py[:248] - [taskid: 2235]系统会自动生成新的线程来执行留评任务！
2019-07-15 15:41:32,733 - INFO - review_us_pool.py[:486] - ********************************pool sleep 3s************************************
2019-07-15 15:41:37,578 - INFO - review_us_pool.py[:480] - 成功获取到1条待评论的数据！
2019-07-15 15:43:08,895 - INFO - review_us_pool.py[:417] - [taskid: 2235]账户登录日志已成功插入！
2019-07-15 15:43:10,941 - INFO - review_us_pool.py[:423] - [taskid: 2235]对应账户的header和cookies字段已成功修改!
2019-07-15 15:43:33,357 - INFO - review_us_pool.py[:201] - [taskid: 2235]找到目标订单所在的tbody!
2019-07-15 15:43:33,441 - INFO - review_us_pool.py[:238] - [taskid: 2235]卖家尚未发货，暂时不能留评，程序退出！
2019-07-15 15:43:35,638 - INFO - review_us_pool.py[:242] - [taskid: 2235]当前账户操作完毕，关闭当前浏览器！
2019-07-15 15:43:36,639 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000009F2E11C50>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/49978735493e71f153b33a4b967f5ff2
2019-07-15 15:43:37,671 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000009F30352E8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/49978735493e71f153b33a4b967f5ff2
2019-07-15 15:43:38,687 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000009F3035550>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/49978735493e71f153b33a4b967f5ff2
2019-07-15 15:43:42,829 - INFO - review_us_pool.py[:486] - ********************************pool sleep 3s************************************
2019-07-15 15:43:43,595 - INFO - review_us_pool.py[:480] - 成功获取到1条待评论的数据！
2019-07-15 15:45:15,134 - INFO - review_us_pool.py[:417] - [taskid: 2235]账户登录日志已成功插入！
2019-07-15 15:45:15,973 - INFO - review_us_pool.py[:423] - [taskid: 2235]对应账户的header和cookies字段已成功修改!
2019-07-15 15:45:38,507 - INFO - review_us_pool.py[:201] - [taskid: 2235]找到目标订单所在的tbody!
2019-07-15 15:45:38,595 - INFO - review_us_pool.py[:238] - [taskid: 2235]卖家尚未发货，暂时不能留评，程序退出！
2019-07-15 15:45:40,767 - INFO - review_us_pool.py[:242] - [taskid: 2235]当前账户操作完毕，关闭当前浏览器！
2019-07-15 15:45:41,767 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000DE5A9A1CC0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/5ada74606d0102b0ec3015a8fcb63e15
2019-07-15 15:45:42,768 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000DE5ABC5208>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/5ada74606d0102b0ec3015a8fcb63e15
2019-07-15 15:45:43,768 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000DE5ABC55C0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/5ada74606d0102b0ec3015a8fcb63e15
2019-07-15 15:45:47,926 - INFO - review_us_pool.py[:486] - ********************************pool sleep 3s************************************
2019-07-15 15:45:48,504 - INFO - review_us_pool.py[:480] - 成功获取到1条待评论的数据！
2019-07-15 15:47:23,023 - INFO - review_us_pool.py[:417] - [taskid: 2235]账户登录日志已成功插入！
2019-07-15 15:47:33,737 - INFO - review_us_pool.py[:423] - [taskid: 2235]对应账户的header和cookies字段已成功修改!
2019-07-15 15:47:59,002 - INFO - review_us_pool.py[:201] - [taskid: 2235]找到目标订单所在的tbody!
2019-07-15 15:47:59,088 - INFO - review_us_pool.py[:238] - [taskid: 2235]卖家尚未发货，暂时不能留评，程序退出！
2019-07-15 15:48:01,266 - INFO - review_us_pool.py[:242] - [taskid: 2235]当前账户操作完毕，关闭当前浏览器！
2019-07-15 15:48:02,282 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C696851CC0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/aa595eb3682148225096afc53e57217d
2019-07-15 15:48:03,298 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C696E55358>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/aa595eb3682148225096afc53e57217d
2019-07-15 15:48:04,314 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C696E555C0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/aa595eb3682148225096afc53e57217d
2019-07-15 15:48:08,425 - INFO - review_us_pool.py[:486] - ********************************pool sleep 3s************************************
2019-07-15 15:48:12,630 - INFO - review_us_pool.py[:480] - 成功获取到1条待评论的数据！
2019-07-15 15:51:24,900 - INFO - review_us_pool.py[:246] - [taskid: 2235]等待超时,或者元素位未完全加载导致定位出错!
2019-07-15 15:51:24,900 - INFO - review_us_pool.py[:247] - [taskid: 2235]关闭当前浏览器，结束当前线程！
2019-07-15 15:51:24,900 - INFO - review_us_pool.py[:248] - [taskid: 2235]系统会自动生成新的线程来执行留评任务！
2019-07-15 15:51:31,154 - INFO - review_us_pool.py[:486] - ********************************pool sleep 3s************************************
2019-07-15 15:51:32,732 - INFO - review_us_pool.py[:480] - 成功获取到1条待评论的数据！
2019-07-15 15:55:01,641 - INFO - review_us_pool.py[:246] - [taskid: 2235]等待超时,或者元素位未完全加载导致定位出错!
2019-07-15 15:55:01,642 - INFO - review_us_pool.py[:247] - [taskid: 2235]关闭当前浏览器，结束当前线程！
2019-07-15 15:55:01,643 - INFO - review_us_pool.py[:248] - [taskid: 2235]系统会自动生成新的线程来执行留评任务！
2019-07-15 15:55:07,964 - INFO - review_us_pool.py[:486] - ********************************pool sleep 3s************************************
2019-07-15 15:55:08,542 - INFO - review_us_pool.py[:480] - 成功获取到1条待评论的数据！
2019-07-15 15:56:35,637 - INFO - review_us_pool.py[:417] - [taskid: 2235]账户登录日志已成功插入！
2019-07-15 15:56:37,752 - INFO - review_us_pool.py[:423] - [taskid: 2235]对应账户的header和cookies字段已成功修改!
2019-07-15 15:56:55,024 - INFO - review_us_pool.py[:201] - [taskid: 2235]找到目标订单所在的tbody!
2019-07-15 15:56:55,096 - INFO - review_us_pool.py[:238] - [taskid: 2235]卖家尚未发货，暂时不能留评，程序退出！
2019-07-15 15:56:57,272 - INFO - review_us_pool.py[:242] - [taskid: 2235]当前账户操作完毕，关闭当前浏览器！
2019-07-15 15:56:58,306 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000001CC3261C18>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/08506596a122492f496e2464e4a500be
2019-07-15 15:56:59,320 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000001CC327E0B8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/08506596a122492f496e2464e4a500be
2019-07-15 15:57:00,337 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000001CC34857B8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/08506596a122492f496e2464e4a500be
2019-07-15 15:57:04,447 - INFO - review_us_pool.py[:486] - ********************************pool sleep 3s************************************
2019-07-15 15:57:05,619 - INFO - review_us_pool.py[:480] - 成功获取到1条待评论的数据！
2019-07-15 15:58:31,210 - INFO - review_us_pool.py[:417] - [taskid: 2235]账户登录日志已成功插入！
2019-07-15 15:58:31,904 - INFO - review_us_pool.py[:423] - [taskid: 2235]对应账户的header和cookies字段已成功修改!
2019-07-15 15:58:52,570 - INFO - review_us_pool.py[:201] - [taskid: 2235]找到目标订单所在的tbody!
2019-07-15 15:58:52,657 - INFO - review_us_pool.py[:238] - [taskid: 2235]卖家尚未发货，暂时不能留评，程序退出！
2019-07-15 15:58:54,863 - INFO - review_us_pool.py[:242] - [taskid: 2235]当前账户操作完毕，关闭当前浏览器！
2019-07-15 15:58:55,879 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000022B8ABFCC0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/eac621f9d9390fc7ad6a78e6811d597c
2019-07-15 15:58:56,896 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000022B8ADE2B0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/eac621f9d9390fc7ad6a78e6811d597c
2019-07-15 15:58:57,911 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000022B8ADE908>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/eac621f9d9390fc7ad6a78e6811d597c
2019-07-15 15:59:02,132 - INFO - review_us_pool.py[:486] - ********************************pool sleep 3s************************************
2019-07-15 15:59:03,225 - INFO - review_us_pool.py[:480] - 成功获取到1条待评论的数据！
2019-07-15 16:01:21,261 - INFO - review_us_pool.py[:417] - [taskid: 2235]账户登录日志已成功插入！
2019-07-15 16:01:25,998 - INFO - review_us_pool.py[:423] - [taskid: 2235]对应账户的header和cookies字段已成功修改!
2019-07-15 16:03:39,253 - INFO - review_us_pool.py[:201] - [taskid: 2235]找到目标订单所在的tbody!
2019-07-15 16:03:39,331 - INFO - review_us_pool.py[:238] - [taskid: 2235]卖家尚未发货，暂时不能留评，程序退出！
2019-07-15 16:03:41,488 - INFO - review_us_pool.py[:242] - [taskid: 2235]当前账户操作完毕，关闭当前浏览器！
2019-07-15 16:03:42,489 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007871811CC0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/34c17d1b108c83a28d7987c88d537f25
2019-07-15 16:03:43,505 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000787182E5F8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/34c17d1b108c83a28d7987c88d537f25
2019-07-15 16:03:44,521 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000787182E6A0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/34c17d1b108c83a28d7987c88d537f25
2019-07-15 16:03:48,647 - INFO - review_us_pool.py[:486] - ********************************pool sleep 3s************************************
2019-07-15 16:03:49,163 - INFO - review_us_pool.py[:480] - 成功获取到1条待评论的数据！
2019-07-15 16:05:20,343 - INFO - review_us_pool.py[:417] - [taskid: 2235]账户登录日志已成功插入！
2019-07-15 16:05:21,152 - INFO - review_us_pool.py[:423] - [taskid: 2235]对应账户的header和cookies字段已成功修改!
2019-07-15 16:05:43,595 - INFO - review_us_pool.py[:201] - [taskid: 2235]找到目标订单所在的tbody!
2019-07-15 16:05:43,679 - INFO - review_us_pool.py[:238] - [taskid: 2235]卖家尚未发货，暂时不能留评，程序退出！
2019-07-15 16:05:45,816 - INFO - review_us_pool.py[:242] - [taskid: 2235]当前账户操作完毕，关闭当前浏览器！
2019-07-15 16:05:46,832 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000359C65FCF8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/b1758cabbb5341f3d1ea82d7c902a48f
2019-07-15 16:05:47,848 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000359C8859B0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/b1758cabbb5341f3d1ea82d7c902a48f
2019-07-15 16:05:48,880 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000359C885DA0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/b1758cabbb5341f3d1ea82d7c902a48f
2019-07-15 16:05:53,006 - INFO - review_us_pool.py[:486] - ********************************pool sleep 3s************************************
2019-07-15 16:05:54,163 - INFO - review_us_pool.py[:480] - 成功获取到1条待评论的数据！
2019-07-15 16:07:45,953 - INFO - review_us_pool.py[:417] - [taskid: 2235]账户登录日志已成功插入！
2019-07-15 16:07:49,703 - INFO - review_us_pool.py[:423] - [taskid: 2235]对应账户的header和cookies字段已成功修改!
2019-07-15 16:08:21,468 - INFO - review_us_pool.py[:201] - [taskid: 2235]找到目标订单所在的tbody!
2019-07-15 16:08:21,552 - INFO - review_us_pool.py[:238] - [taskid: 2235]卖家尚未发货，暂时不能留评，程序退出！
2019-07-15 16:08:24,724 - INFO - review_us_pool.py[:242] - [taskid: 2235]当前账户操作完毕，关闭当前浏览器！
2019-07-15 16:08:25,740 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000079A34AFCC0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/1bef1c109e32d67ee5589e2394148f02
2019-07-15 16:08:26,756 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000079A34CE198>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/1bef1c109e32d67ee5589e2394148f02
2019-07-15 16:08:27,772 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000079A3AB5898>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/1bef1c109e32d67ee5589e2394148f02
2019-07-15 16:08:31,930 - INFO - review_us_pool.py[:486] - ********************************pool sleep 3s************************************
2019-07-15 16:08:33,368 - INFO - review_us_pool.py[:480] - 成功获取到1条待评论的数据！
2019-07-15 16:10:22,585 - INFO - review_us_pool.py[:417] - [taskid: 2235]账户登录日志已成功插入！
2019-07-15 16:10:23,271 - INFO - review_us_pool.py[:423] - [taskid: 2235]对应账户的header和cookies字段已成功修改!
2019-07-15 16:10:56,863 - INFO - review_us_pool.py[:201] - [taskid: 2235]找到目标订单所在的tbody!
2019-07-15 16:10:56,949 - INFO - review_us_pool.py[:238] - [taskid: 2235]卖家尚未发货，暂时不能留评，程序退出！
2019-07-15 16:10:59,177 - INFO - review_us_pool.py[:242] - [taskid: 2235]当前账户操作完毕，关闭当前浏览器！
2019-07-15 16:11:00,193 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000028D74CFCF8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/9a38dc6c3488cc77cc7a9651c0af5825
2019-07-15 16:11:01,209 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000028D74EE390>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/9a38dc6c3488cc77cc7a9651c0af5825
2019-07-15 16:11:02,241 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000028D74EE3C8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/9a38dc6c3488cc77cc7a9651c0af5825
2019-07-15 16:11:06,384 - INFO - review_us_pool.py[:486] - ********************************pool sleep 3s************************************
2019-07-15 16:11:07,087 - INFO - review_us_pool.py[:480] - 成功获取到1条待评论的数据！
2019-07-15 16:12:25,898 - INFO - review_us_pool.py[:417] - [taskid: 2235]账户登录日志已成功插入！
2019-07-15 16:12:29,721 - INFO - review_us_pool.py[:423] - [taskid: 2235]对应账户的header和cookies字段已成功修改!
2019-07-15 16:12:47,042 - INFO - review_us_pool.py[:201] - [taskid: 2235]找到目标订单所在的tbody!
2019-07-15 16:12:47,120 - INFO - review_us_pool.py[:238] - [taskid: 2235]卖家尚未发货，暂时不能留评，程序退出！
2019-07-15 16:12:50,290 - INFO - review_us_pool.py[:242] - [taskid: 2235]当前账户操作完毕，关闭当前浏览器！
2019-07-15 16:12:51,321 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000003B9664FC88>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/ca6a842a2bc8472b5cd19bfbcfc6e81a
2019-07-15 16:12:52,336 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000003B9666E278>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/ca6a842a2bc8472b5cd19bfbcfc6e81a
2019-07-15 16:12:53,353 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000003B9666E8D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/ca6a842a2bc8472b5cd19bfbcfc6e81a
2019-07-15 16:12:57,557 - INFO - review_us_pool.py[:486] - ********************************pool sleep 3s************************************
2019-07-15 16:12:58,495 - INFO - review_us_pool.py[:480] - 成功获取到1条待评论的数据！
2019-07-15 16:15:25,654 - INFO - review_us_pool.py[:246] - [taskid: 2235]等待超时,或者元素位未完全加载导致定位出错!
2019-07-15 16:15:25,654 - INFO - review_us_pool.py[:247] - [taskid: 2235]关闭当前浏览器，结束当前线程！
2019-07-15 16:15:25,654 - INFO - review_us_pool.py[:248] - [taskid: 2235]系统会自动生成新的线程来执行留评任务！
2019-07-15 16:15:30,984 - INFO - review_us_pool.py[:486] - ********************************pool sleep 3s************************************
2019-07-15 16:15:32,250 - INFO - review_us_pool.py[:480] - 成功获取到1条待评论的数据！
2019-07-15 16:19:28,091 - INFO - review_us_pool.py[:246] - [taskid: 2235]等待超时,或者元素位未完全加载导致定位出错!
2019-07-15 16:19:28,092 - INFO - review_us_pool.py[:247] - [taskid: 2235]关闭当前浏览器，结束当前线程！
2019-07-15 16:19:28,093 - INFO - review_us_pool.py[:248] - [taskid: 2235]系统会自动生成新的线程来执行留评任务！
2019-07-15 16:19:34,364 - INFO - review_us_pool.py[:486] - ********************************pool sleep 3s************************************
2019-07-15 16:19:35,286 - INFO - review_us_pool.py[:480] - 成功获取到1条待评论的数据！
2019-07-15 16:21:30,555 - INFO - review_us_pool.py[:417] - [taskid: 2235]账户登录日志已成功插入！
2019-07-15 16:21:31,447 - INFO - review_us_pool.py[:423] - [taskid: 2235]对应账户的header和cookies字段已成功修改!
2019-07-15 16:23:06,084 - INFO - review_us_pool.py[:201] - [taskid: 2235]找到目标订单所在的tbody!
2019-07-15 16:23:06,154 - INFO - review_us_pool.py[:238] - [taskid: 2235]卖家尚未发货，暂时不能留评，程序退出！
2019-07-15 16:23:09,358 - INFO - review_us_pool.py[:242] - [taskid: 2235]当前账户操作完毕，关闭当前浏览器！
2019-07-15 16:23:10,375 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000006BC0AAFCC0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/c16e58cdb208297e71182ae0841682bb
2019-07-15 16:23:11,406 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000006BC0ACE198>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/c16e58cdb208297e71182ae0841682bb
2019-07-15 16:23:12,423 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000006BC10B5630>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/c16e58cdb208297e71182ae0841682bb
2019-07-15 16:23:16,612 - INFO - review_us_pool.py[:486] - ********************************pool sleep 3s************************************
2019-07-15 16:23:18,847 - INFO - review_us_pool.py[:480] - 成功获取到1条待评论的数据！
2019-07-15 16:24:42,657 - INFO - review_us_pool.py[:417] - [taskid: 2235]账户登录日志已成功插入！
2019-07-15 16:24:43,383 - INFO - review_us_pool.py[:423] - [taskid: 2235]对应账户的header和cookies字段已成功修改!
2019-07-15 16:25:03,294 - INFO - review_us_pool.py[:201] - [taskid: 2235]找到目标订单所在的tbody!
2019-07-15 16:25:03,373 - INFO - review_us_pool.py[:238] - [taskid: 2235]卖家尚未发货，暂时不能留评，程序退出！
2019-07-15 16:25:05,523 - INFO - review_us_pool.py[:242] - [taskid: 2235]当前账户操作完毕，关闭当前浏览器！
2019-07-15 16:25:06,524 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000DBC80CFCF8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/0d11584acd8e6df7fcd7a26078844bae
2019-07-15 16:25:07,540 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000DBC80EE3C8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/0d11584acd8e6df7fcd7a26078844bae
2019-07-15 16:25:08,556 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000DBC80EE908>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/0d11584acd8e6df7fcd7a26078844bae
2019-07-15 16:25:12,745 - INFO - review_us_pool.py[:486] - ********************************pool sleep 3s************************************
2019-07-15 16:25:13,214 - INFO - review_us_pool.py[:480] - 成功获取到1条待评论的数据！
2019-07-15 16:27:15,565 - INFO - review_us_pool.py[:417] - [taskid: 2235]账户登录日志已成功插入！
2019-07-15 16:27:16,289 - INFO - review_us_pool.py[:423] - [taskid: 2235]对应账户的header和cookies字段已成功修改!
2019-07-15 16:28:00,458 - INFO - review_us_pool.py[:201] - [taskid: 2235]找到目标订单所在的tbody!
2019-07-15 16:28:00,545 - INFO - review_us_pool.py[:238] - [taskid: 2235]卖家尚未发货，暂时不能留评，程序退出！
2019-07-15 16:28:02,685 - INFO - review_us_pool.py[:242] - [taskid: 2235]当前账户操作完毕，关闭当前浏览器！
2019-07-15 16:28:03,701 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000D9808BFCC0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/35fa20a3347b0045434a10e2efe1aae6
2019-07-15 16:28:04,716 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000D9808DE198>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/35fa20a3347b0045434a10e2efe1aae6
2019-07-15 16:28:05,732 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000D980EC5898>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/35fa20a3347b0045434a10e2efe1aae6
2019-07-15 16:28:09,953 - INFO - review_us_pool.py[:486] - ********************************pool sleep 3s************************************
2019-07-15 16:28:11,062 - INFO - review_us_pool.py[:480] - 成功获取到1条待评论的数据！
2019-07-15 16:29:30,269 - INFO - review_us_pool.py[:417] - [taskid: 2235]账户登录日志已成功插入！
2019-07-15 16:29:30,947 - INFO - review_us_pool.py[:423] - [taskid: 2235]对应账户的header和cookies字段已成功修改!
2019-07-15 16:29:48,867 - INFO - review_us_pool.py[:201] - [taskid: 2235]找到目标订单所在的tbody!
2019-07-15 16:29:48,949 - INFO - review_us_pool.py[:238] - [taskid: 2235]卖家尚未发货，暂时不能留评，程序退出！
2019-07-15 16:29:52,121 - INFO - review_us_pool.py[:242] - [taskid: 2235]当前账户操作完毕，关闭当前浏览器！
2019-07-15 16:29:53,137 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000031042CFCC0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/2308673749af6b894ba1bee17e7a0814
2019-07-15 16:29:54,153 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000031044F5978>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/2308673749af6b894ba1bee17e7a0814
2019-07-15 16:29:55,154 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000031044F5D68>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/2308673749af6b894ba1bee17e7a0814
2019-07-15 16:29:59,281 - INFO - review_us_pool.py[:486] - ********************************pool sleep 3s************************************
2019-07-15 16:29:59,780 - INFO - review_us_pool.py[:480] - 成功获取到1条待评论的数据！
2019-07-15 16:31:16,774 - INFO - review_us_pool.py[:417] - [taskid: 2235]账户登录日志已成功插入！
2019-07-15 16:31:17,434 - INFO - review_us_pool.py[:423] - [taskid: 2235]对应账户的header和cookies字段已成功修改!
2019-07-15 16:31:36,357 - INFO - review_us_pool.py[:201] - [taskid: 2235]找到目标订单所在的tbody!
2019-07-15 16:31:36,437 - INFO - review_us_pool.py[:238] - [taskid: 2235]卖家尚未发货，暂时不能留评，程序退出！
2019-07-15 16:31:39,615 - INFO - review_us_pool.py[:242] - [taskid: 2235]当前账户操作完毕，关闭当前浏览器！
2019-07-15 16:31:40,631 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000DC468E1CC0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/8081ca1df5825a4a1427d1d87254394e
2019-07-15 16:31:41,647 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000DC468FE9B0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/8081ca1df5825a4a1427d1d87254394e
2019-07-15 16:31:42,663 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000DC468FE7B8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/8081ca1df5825a4a1427d1d87254394e
2019-07-15 16:31:46,884 - INFO - review_us_pool.py[:486] - ********************************pool sleep 3s************************************
2019-07-15 16:31:48,165 - INFO - review_us_pool.py[:480] - 成功获取到1条待评论的数据！
2019-07-15 16:33:18,475 - INFO - review_us_pool.py[:246] - [taskid: 2235]等待超时,或者元素位未完全加载导致定位出错!
2019-07-15 16:33:18,475 - INFO - review_us_pool.py[:247] - [taskid: 2235]关闭当前浏览器，结束当前线程！
2019-07-15 16:33:18,475 - INFO - review_us_pool.py[:248] - [taskid: 2235]系统会自动生成新的线程来执行留评任务！
2019-07-15 16:33:23,806 - INFO - review_us_pool.py[:486] - ********************************pool sleep 3s************************************
2019-07-15 16:33:24,837 - INFO - review_us_pool.py[:480] - 成功获取到1条待评论的数据！
2019-07-15 16:34:44,349 - INFO - review_us_pool.py[:417] - [taskid: 2235]账户登录日志已成功插入！
2019-07-15 16:34:46,019 - INFO - review_us_pool.py[:423] - [taskid: 2235]对应账户的header和cookies字段已成功修改!
2019-07-15 16:35:05,440 - INFO - review_us_pool.py[:201] - [taskid: 2235]找到目标订单所在的tbody!
2019-07-15 16:35:05,525 - INFO - review_us_pool.py[:238] - [taskid: 2235]卖家尚未发货，暂时不能留评，程序退出！
2019-07-15 16:35:08,677 - INFO - review_us_pool.py[:242] - [taskid: 2235]当前账户操作完毕，关闭当前浏览器！
2019-07-15 16:35:09,710 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000053D3291CC0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/e9b92e6ee011d1f4e5c5e2ba103c13ec
2019-07-15 16:35:10,741 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000053D32AE2E8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/e9b92e6ee011d1f4e5c5e2ba103c13ec
2019-07-15 16:35:11,756 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000053D34B5898>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/e9b92e6ee011d1f4e5c5e2ba103c13ec
2019-07-15 16:35:15,946 - INFO - review_us_pool.py[:486] - ********************************pool sleep 3s************************************
2019-07-15 16:35:16,524 - INFO - review_us_pool.py[:480] - 成功获取到1条待评论的数据！
2019-07-15 16:37:27,194 - INFO - review_us_pool.py[:417] - [taskid: 2235]账户登录日志已成功插入！
2019-07-15 16:37:28,360 - INFO - review_us_pool.py[:423] - [taskid: 2235]对应账户的header和cookies字段已成功修改!
2019-07-15 16:38:13,218 - INFO - review_us_pool.py[:201] - [taskid: 2235]找到目标订单所在的tbody!
2019-07-15 16:38:13,296 - INFO - review_us_pool.py[:238] - [taskid: 2235]卖家尚未发货，暂时不能留评，程序退出！
2019-07-15 16:38:16,451 - INFO - review_us_pool.py[:242] - [taskid: 2235]当前账户操作完毕，关闭当前浏览器！
2019-07-15 16:38:17,482 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000FA0C631CC0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/139f4e99fbbb362a1c00b3da272304b5
2019-07-15 16:38:18,513 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000FA0CC35470>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/139f4e99fbbb362a1c00b3da272304b5
2019-07-15 16:38:19,530 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000FA0CC35A90>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/139f4e99fbbb362a1c00b3da272304b5
2019-07-15 16:38:23,688 - INFO - review_us_pool.py[:486] - ********************************pool sleep 3s************************************
2019-07-15 16:38:24,344 - INFO - review_us_pool.py[:480] - 成功获取到1条待评论的数据！
2019-07-15 16:41:30,141 - INFO - review_us_pool.py[:417] - [taskid: 2235]账户登录日志已成功插入！
2019-07-15 16:41:30,959 - INFO - review_us_pool.py[:423] - [taskid: 2235]对应账户的header和cookies字段已成功修改!
2019-07-15 16:42:11,478 - INFO - review_us_pool.py[:242] - [taskid: 2235]当前账户操作完毕，关闭当前浏览器！
2019-07-15 16:42:16,715 - INFO - review_us_pool.py[:486] - ********************************pool sleep 3s************************************
2019-07-15 16:42:17,152 - INFO - review_us_pool.py[:480] - 成功获取到1条待评论的数据！
2019-07-15 16:45:57,277 - INFO - review_us_pool.py[:246] - [taskid: 2235]等待超时,或者元素位未完全加载导致定位出错!
2019-07-15 16:45:57,277 - INFO - review_us_pool.py[:247] - [taskid: 2235]关闭当前浏览器，结束当前线程！
2019-07-15 16:45:57,277 - INFO - review_us_pool.py[:248] - [taskid: 2235]系统会自动生成新的线程来执行留评任务！
2019-07-15 16:46:02,592 - INFO - review_us_pool.py[:486] - ********************************pool sleep 3s************************************
2019-07-15 16:46:03,499 - INFO - review_us_pool.py[:480] - 成功获取到1条待评论的数据！
2019-07-15 16:47:38,855 - INFO - review_us_pool.py[:417] - [taskid: 2235]账户登录日志已成功插入！
2019-07-15 16:47:41,343 - INFO - review_us_pool.py[:423] - [taskid: 2235]对应账户的header和cookies字段已成功修改!
2019-07-15 16:48:07,844 - INFO - review_us_pool.py[:201] - [taskid: 2235]找到目标订单所在的tbody!
2019-07-15 16:48:07,929 - INFO - review_us_pool.py[:238] - [taskid: 2235]卖家尚未发货，暂时不能留评，程序退出！
2019-07-15 16:48:10,104 - INFO - review_us_pool.py[:242] - [taskid: 2235]当前账户操作完毕，关闭当前浏览器！
2019-07-15 16:48:11,120 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000053034BFCC0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/260b5c27e17beb1454384af1b0cafce2
2019-07-15 16:48:12,152 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000005303AC5358>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/260b5c27e17beb1454384af1b0cafce2
2019-07-15 16:48:13,168 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000005303AC55C0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/260b5c27e17beb1454384af1b0cafce2
2019-07-15 16:48:17,280 - INFO - review_us_pool.py[:486] - ********************************pool sleep 3s************************************
2019-07-15 16:48:18,514 - INFO - review_us_pool.py[:480] - 成功获取到1条待评论的数据！
2019-07-15 16:49:34,147 - INFO - review_us_pool.py[:417] - [taskid: 2235]账户登录日志已成功插入！
2019-07-15 16:49:35,260 - INFO - review_us_pool.py[:423] - [taskid: 2235]对应账户的header和cookies字段已成功修改!
2019-07-15 16:49:53,614 - INFO - review_us_pool.py[:201] - [taskid: 2235]找到目标订单所在的tbody!
2019-07-15 16:49:53,693 - INFO - review_us_pool.py[:238] - [taskid: 2235]卖家尚未发货，暂时不能留评，程序退出！
2019-07-15 16:49:56,840 - INFO - review_us_pool.py[:242] - [taskid: 2235]当前账户操作完毕，关闭当前浏览器！
2019-07-15 16:49:57,856 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000F250AB1C50>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/e3039d423b532898b430b92735f41f0e
2019-07-15 16:49:58,872 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000F250ACE400>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/e3039d423b532898b430b92735f41f0e
2019-07-15 16:49:59,888 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000F250CD5828>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/e3039d423b532898b430b92735f41f0e
2019-07-15 16:50:03,999 - INFO - review_us_pool.py[:486] - ********************************pool sleep 3s************************************
2019-07-15 16:50:04,639 - INFO - review_us_pool.py[:480] - 成功获取到1条待评论的数据！
2019-07-15 16:53:31,684 - INFO - review_us_pool.py[:103] - [taskid: 2235]登录时发现滑块验证码，程序退出！
2019-07-15 16:53:35,896 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000002EFD0DFCF8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/ad3b3faa9eb1b3eec235d3ad584fc69a/element
2019-07-15 16:53:36,912 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000002EFD0FE668>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/ad3b3faa9eb1b3eec235d3ad584fc69a/element
2019-07-15 16:53:37,929 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000002EFD0FE9B0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/ad3b3faa9eb1b3eec235d3ad584fc69a/element
2019-07-15 16:53:42,149 - INFO - review_us_pool.py[:486] - ********************************pool sleep 3s************************************
2019-07-15 16:53:43,290 - INFO - review_us_pool.py[:480] - 成功获取到1条待评论的数据！
2019-07-15 16:55:00,211 - INFO - review_us_pool.py[:417] - [taskid: 2235]账户登录日志已成功插入！
2019-07-15 16:55:00,906 - INFO - review_us_pool.py[:423] - [taskid: 2235]对应账户的header和cookies字段已成功修改!
2019-07-15 16:55:19,478 - INFO - review_us_pool.py[:201] - [taskid: 2235]找到目标订单所在的tbody!
2019-07-15 16:55:19,557 - INFO - review_us_pool.py[:238] - [taskid: 2235]卖家尚未发货，暂时不能留评，程序退出！
2019-07-15 16:55:21,717 - INFO - review_us_pool.py[:242] - [taskid: 2235]当前账户操作完毕，关闭当前浏览器！
2019-07-15 16:55:22,733 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000DD8742FCC0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/9372e9e07984549dbe18c1e44c8bfc87
2019-07-15 16:55:23,766 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000DD8744E2B0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/9372e9e07984549dbe18c1e44c8bfc87
2019-07-15 16:55:24,781 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000DD8744E668>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/9372e9e07984549dbe18c1e44c8bfc87
2019-07-15 16:55:29,002 - INFO - review_us_pool.py[:486] - ********************************pool sleep 3s************************************
2019-07-15 16:55:29,908 - INFO - review_us_pool.py[:480] - 成功获取到1条待评论的数据！
2019-07-15 16:59:17,404 - INFO - review_us_pool.py[:246] - [taskid: 2235]等待超时,或者元素位未完全加载导致定位出错!
2019-07-15 16:59:17,405 - INFO - review_us_pool.py[:247] - [taskid: 2235]关闭当前浏览器，结束当前线程！
2019-07-15 16:59:17,406 - INFO - review_us_pool.py[:248] - [taskid: 2235]系统会自动生成新的线程来执行留评任务！
2019-07-15 16:59:23,689 - INFO - review_us_pool.py[:486] - ********************************pool sleep 3s************************************
2019-07-15 16:59:24,158 - INFO - review_us_pool.py[:480] - 成功获取到1条待评论的数据！
2019-07-15 17:00:41,425 - INFO - review_us_pool.py[:417] - [taskid: 2235]账户登录日志已成功插入！
2019-07-15 17:00:43,033 - INFO - review_us_pool.py[:423] - [taskid: 2235]对应账户的header和cookies字段已成功修改!
2019-07-15 17:01:01,562 - INFO - review_us_pool.py[:201] - [taskid: 2235]找到目标订单所在的tbody!
2019-07-15 17:01:01,652 - INFO - review_us_pool.py[:238] - [taskid: 2235]卖家尚未发货，暂时不能留评，程序退出！
2019-07-15 17:01:04,817 - INFO - review_us_pool.py[:242] - [taskid: 2235]当前账户操作完毕，关闭当前浏览器！
2019-07-15 17:01:05,850 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000008B5808FC88>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/0ddf117c9af58a8b2c1b7b1a9732cb1c
2019-07-15 17:01:06,881 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000008B580AE438>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/0ddf117c9af58a8b2c1b7b1a9732cb1c
2019-07-15 17:01:07,912 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000008B582B5860>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/0ddf117c9af58a8b2c1b7b1a9732cb1c
2019-07-15 17:01:12,117 - INFO - review_us_pool.py[:486] - ********************************pool sleep 3s************************************
2019-07-15 17:01:12,556 - INFO - review_us_pool.py[:480] - 成功获取到1条待评论的数据！
2019-07-15 17:03:01,512 - INFO - review_us_pool.py[:417] - [taskid: 2235]账户登录日志已成功插入！
2019-07-15 17:03:02,185 - INFO - review_us_pool.py[:423] - [taskid: 2235]对应账户的header和cookies字段已成功修改!
2019-07-15 17:03:20,267 - INFO - review_us_pool.py[:201] - [taskid: 2235]找到目标订单所在的tbody!
2019-07-15 17:03:20,356 - INFO - review_us_pool.py[:238] - [taskid: 2235]卖家尚未发货，暂时不能留评，程序退出！
2019-07-15 17:03:23,533 - INFO - review_us_pool.py[:242] - [taskid: 2235]当前账户操作完毕，关闭当前浏览器！
2019-07-15 17:03:24,548 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000009395C5FC88>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/bbf94eb4402e499dc670b6062d21ae9e
2019-07-15 17:03:25,549 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000009396265320>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/bbf94eb4402e499dc670b6062d21ae9e
2019-07-15 17:03:26,549 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000009396265588>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/bbf94eb4402e499dc670b6062d21ae9e
2019-07-15 17:03:30,755 - INFO - review_us_pool.py[:486] - ********************************pool sleep 3s************************************
2019-07-15 17:03:31,317 - INFO - review_us_pool.py[:480] - 成功获取到1条待评论的数据！
2019-07-15 17:05:27,492 - INFO - review_us_pool.py[:246] - [taskid: 2235]等待超时,或者元素位未完全加载导致定位出错!
2019-07-15 17:05:27,492 - INFO - review_us_pool.py[:247] - [taskid: 2235]关闭当前浏览器，结束当前线程！
2019-07-15 17:05:27,492 - INFO - review_us_pool.py[:248] - [taskid: 2235]系统会自动生成新的线程来执行留评任务！
2019-07-15 17:05:32,807 - INFO - review_us_pool.py[:486] - ********************************pool sleep 3s************************************
2019-07-15 17:05:33,510 - INFO - review_us_pool.py[:480] - 成功获取到1条待评论的数据！
2019-07-15 17:07:02,253 - INFO - review_us_pool.py[:417] - [taskid: 2235]账户登录日志已成功插入！
2019-07-15 17:07:03,363 - INFO - review_us_pool.py[:423] - [taskid: 2235]对应账户的header和cookies字段已成功修改!
2019-07-15 17:07:23,746 - INFO - review_us_pool.py[:201] - [taskid: 2235]找到目标订单所在的tbody!
2019-07-15 17:07:23,823 - INFO - review_us_pool.py[:238] - [taskid: 2235]卖家尚未发货，暂时不能留评，程序退出！
2019-07-15 17:07:26,020 - INFO - review_us_pool.py[:242] - [taskid: 2235]当前账户操作完毕，关闭当前浏览器！
2019-07-15 17:07:27,036 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000B16B7F1CC0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/1bf67dadd4d29a971cc9f1847984b313
2019-07-15 17:07:28,053 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000B16B80E470>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/1bf67dadd4d29a971cc9f1847984b313
2019-07-15 17:07:29,068 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000B16BA15898>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/1bf67dadd4d29a971cc9f1847984b313
2019-07-15 17:07:33,257 - INFO - review_us_pool.py[:486] - ********************************pool sleep 3s************************************
2019-07-15 17:07:36,790 - INFO - review_us_pool.py[:480] - 成功获取到1条待评论的数据！
2019-07-15 17:08:54,369 - INFO - review_us_pool.py[:417] - [taskid: 2235]账户登录日志已成功插入！
2019-07-15 17:08:55,076 - INFO - review_us_pool.py[:423] - [taskid: 2235]对应账户的header和cookies字段已成功修改!
2019-07-15 17:09:14,229 - INFO - review_us_pool.py[:201] - [taskid: 2235]找到目标订单所在的tbody!
2019-07-15 17:09:14,323 - INFO - review_us_pool.py[:238] - [taskid: 2235]卖家尚未发货，暂时不能留评，程序退出！
2019-07-15 17:09:17,479 - INFO - review_us_pool.py[:242] - [taskid: 2235]当前账户操作完毕，关闭当前浏览器！
2019-07-15 17:09:18,495 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000CAAB67FCF8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/b092006404044b2849a6ed1e22cb2dae
2019-07-15 17:09:19,511 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000CAAB69E4A8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/b092006404044b2849a6ed1e22cb2dae
2019-07-15 17:09:20,527 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000CAAB8A58D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/b092006404044b2849a6ed1e22cb2dae
2019-07-15 17:09:24,669 - INFO - review_us_pool.py[:486] - ********************************pool sleep 3s************************************
2019-07-15 17:09:25,497 - INFO - review_us_pool.py[:480] - 成功获取到1条待评论的数据！
2019-07-15 17:10:55,807 - INFO - review_us_pool.py[:246] - [taskid: 2235]等待超时,或者元素位未完全加载导致定位出错!
2019-07-15 17:10:55,807 - INFO - review_us_pool.py[:247] - [taskid: 2235]关闭当前浏览器，结束当前线程！
2019-07-15 17:10:55,807 - INFO - review_us_pool.py[:248] - [taskid: 2235]系统会自动生成新的线程来执行留评任务！
2019-07-15 17:11:01,060 - INFO - review_us_pool.py[:486] - ********************************pool sleep 3s************************************
2019-07-15 17:11:02,841 - INFO - review_us_pool.py[:480] - 成功获取到1条待评论的数据！
2019-07-15 17:16:08,298 - INFO - review_us_pool.py[:103] - [taskid: 2235]登录时发现滑块验证码，程序退出！
2019-07-15 17:16:11,485 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000244D43FCF8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/4fee2186bbc40c98eb464a40196482e4/element
2019-07-15 17:16:12,501 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000244D45E668>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/4fee2186bbc40c98eb464a40196482e4/element
2019-07-15 17:16:13,516 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000244D45E9B0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/4fee2186bbc40c98eb464a40196482e4/element
2019-07-15 17:16:17,721 - INFO - review_us_pool.py[:486] - ********************************pool sleep 3s************************************
2019-07-15 17:16:18,909 - INFO - review_us_pool.py[:480] - 成功获取到1条待评论的数据！
2019-07-15 17:17:43,959 - INFO - review_us_pool.py[:417] - [taskid: 2235]账户登录日志已成功插入！
2019-07-15 17:17:44,622 - INFO - review_us_pool.py[:423] - [taskid: 2235]对应账户的header和cookies字段已成功修改!
2019-07-15 17:18:03,826 - INFO - review_us_pool.py[:201] - [taskid: 2235]找到目标订单所在的tbody!
2019-07-15 17:18:03,898 - INFO - review_us_pool.py[:238] - [taskid: 2235]卖家尚未发货，暂时不能留评，程序退出！
2019-07-15 17:18:06,079 - INFO - review_us_pool.py[:242] - [taskid: 2235]当前账户操作完毕，关闭当前浏览器！
2019-07-15 17:18:07,094 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000B5FF95FC88>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/adc150e0ef43afc2bc540e7cb0eaa566
2019-07-15 17:18:08,111 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000B5FFB85320>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/adc150e0ef43afc2bc540e7cb0eaa566
2019-07-15 17:18:09,142 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000B5FFB85588>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/adc150e0ef43afc2bc540e7cb0eaa566
2019-07-15 17:18:13,285 - INFO - review_us_pool.py[:486] - ********************************pool sleep 3s************************************
2019-07-15 17:18:13,988 - INFO - review_us_pool.py[:480] - 成功获取到1条待评论的数据！
2019-07-15 17:20:31,611 - INFO - review_us_pool.py[:417] - [taskid: 2235]账户登录日志已成功插入！
2019-07-15 17:20:32,833 - INFO - review_us_pool.py[:423] - [taskid: 2235]对应账户的header和cookies字段已成功修改!
2019-07-15 17:21:19,033 - INFO - review_us_pool.py[:201] - [taskid: 2235]找到目标订单所在的tbody!
2019-07-15 17:21:19,122 - INFO - review_us_pool.py[:238] - [taskid: 2235]卖家尚未发货，暂时不能留评，程序退出！
2019-07-15 17:21:22,288 - INFO - review_us_pool.py[:242] - [taskid: 2235]当前账户操作完毕，关闭当前浏览器！
2019-07-15 17:21:23,320 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000D5D7801CC0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/a9d8249ef20c965f1f4979b3821ec27f
2019-07-15 17:21:24,352 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000D5D781E390>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/a9d8249ef20c965f1f4979b3821ec27f
2019-07-15 17:21:25,383 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000D5D781E898>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/a9d8249ef20c965f1f4979b3821ec27f
2019-07-15 17:21:29,526 - INFO - review_us_pool.py[:486] - ********************************pool sleep 3s************************************
2019-07-15 17:21:30,166 - INFO - review_us_pool.py[:480] - 成功获取到1条待评论的数据！
2019-07-15 17:22:48,734 - INFO - review_us_pool.py[:417] - [taskid: 2235]账户登录日志已成功插入！
2019-07-15 17:22:49,438 - INFO - review_us_pool.py[:423] - [taskid: 2235]对应账户的header和cookies字段已成功修改!
2019-07-15 17:23:08,021 - INFO - review_us_pool.py[:201] - [taskid: 2235]找到目标订单所在的tbody!
2019-07-15 17:23:08,102 - INFO - review_us_pool.py[:238] - [taskid: 2235]卖家尚未发货，暂时不能留评，程序退出！
2019-07-15 17:23:10,249 - INFO - review_us_pool.py[:242] - [taskid: 2235]当前账户操作完毕，关闭当前浏览器！
2019-07-15 17:23:11,250 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000006C5C52FCF8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/ba99dd69b81fb51938cb2189fa9ec9b5
2019-07-15 17:23:12,281 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000006C5C54E2E8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/ba99dd69b81fb51938cb2189fa9ec9b5
2019-07-15 17:23:13,298 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000006C5C54E940>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/ba99dd69b81fb51938cb2189fa9ec9b5
2019-07-15 17:23:17,424 - INFO - review_us_pool.py[:486] - ********************************pool sleep 3s************************************
2019-07-15 17:23:17,862 - INFO - review_us_pool.py[:480] - 成功获取到1条待评论的数据！
2019-07-15 17:25:40,904 - INFO - review_us_pool.py[:246] - [taskid: 2235]等待超时,或者元素位未完全加载导致定位出错!
2019-07-15 17:25:40,904 - INFO - review_us_pool.py[:247] - [taskid: 2235]关闭当前浏览器，结束当前线程！
2019-07-15 17:25:40,904 - INFO - review_us_pool.py[:248] - [taskid: 2235]系统会自动生成新的线程来执行留评任务！
2019-07-15 17:25:47,219 - INFO - review_us_pool.py[:486] - ********************************pool sleep 3s************************************
2019-07-15 17:25:48,079 - INFO - review_us_pool.py[:480] - 成功获取到1条待评论的数据！
2019-07-15 17:27:21,338 - INFO - review_us_pool.py[:417] - [taskid: 2235]账户登录日志已成功插入！
2019-07-15 17:27:22,153 - INFO - review_us_pool.py[:423] - [taskid: 2235]对应账户的header和cookies字段已成功修改!
2019-07-15 17:27:49,087 - INFO - review_us_pool.py[:201] - [taskid: 2235]找到目标订单所在的tbody!
2019-07-15 17:27:49,175 - INFO - review_us_pool.py[:238] - [taskid: 2235]卖家尚未发货，暂时不能留评，程序退出！
2019-07-15 17:27:51,371 - INFO - review_us_pool.py[:242] - [taskid: 2235]当前账户操作完毕，关闭当前浏览器！
2019-07-15 17:27:52,401 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000004B8F061C50>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/3b52cf05b14f4d3091616fa4f99fcefd
2019-07-15 17:27:53,433 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000004B8F6652E8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/3b52cf05b14f4d3091616fa4f99fcefd
2019-07-15 17:27:54,449 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000004B8F665550>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/3b52cf05b14f4d3091616fa4f99fcefd
2019-07-15 17:27:58,576 - INFO - review_us_pool.py[:486] - ********************************pool sleep 3s************************************
2019-07-15 17:27:59,013 - INFO - review_us_pool.py[:480] - 成功获取到1条待评论的数据！
2019-07-15 17:29:35,463 - INFO - review_us_pool.py[:417] - [taskid: 2235]账户登录日志已成功插入！
2019-07-15 17:29:37,635 - INFO - review_us_pool.py[:423] - [taskid: 2235]对应账户的header和cookies字段已成功修改!
2019-07-15 17:30:09,176 - INFO - review_us_pool.py[:201] - [taskid: 2235]找到目标订单所在的tbody!
2019-07-15 17:30:09,248 - INFO - review_us_pool.py[:238] - [taskid: 2235]卖家尚未发货，暂时不能留评，程序退出！
2019-07-15 17:30:11,377 - INFO - review_us_pool.py[:242] - [taskid: 2235]当前账户操作完毕，关闭当前浏览器！
2019-07-15 17:30:12,409 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000655C3D1C50>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/e894b38e3b0ccd702542b5e78286a8f0
2019-07-15 17:30:13,440 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000655C9D5908>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/e894b38e3b0ccd702542b5e78286a8f0
2019-07-15 17:30:14,473 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000655C9D5CF8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/e894b38e3b0ccd702542b5e78286a8f0
2019-07-15 17:30:18,646 - INFO - review_us_pool.py[:486] - ********************************pool sleep 3s************************************
2019-07-15 17:30:19,115 - INFO - review_us_pool.py[:480] - 成功获取到1条待评论的数据！
2019-07-15 17:31:49,623 - INFO - review_us_pool.py[:246] - [taskid: 2235]等待超时,或者元素位未完全加载导致定位出错!
2019-07-15 17:31:49,623 - INFO - review_us_pool.py[:247] - [taskid: 2235]关闭当前浏览器，结束当前线程！
2019-07-15 17:31:49,623 - INFO - review_us_pool.py[:248] - [taskid: 2235]系统会自动生成新的线程来执行留评任务！
2019-07-15 17:31:55,939 - INFO - review_us_pool.py[:486] - ********************************pool sleep 3s************************************
2019-07-15 17:31:56,938 - INFO - review_us_pool.py[:480] - 成功获取到1条待评论的数据！
2019-07-15 17:33:22,046 - INFO - review_us_pool.py[:417] - [taskid: 2235]账户登录日志已成功插入！
2019-07-15 17:33:23,553 - INFO - review_us_pool.py[:423] - [taskid: 2235]对应账户的header和cookies字段已成功修改!
2019-07-15 17:33:41,727 - INFO - review_us_pool.py[:201] - [taskid: 2235]找到目标订单所在的tbody!
2019-07-15 17:33:41,807 - INFO - review_us_pool.py[:238] - [taskid: 2235]卖家尚未发货，暂时不能留评，程序退出！
2019-07-15 17:33:44,977 - INFO - review_us_pool.py[:242] - [taskid: 2235]当前账户操作完毕，关闭当前浏览器！
2019-07-15 17:33:45,976 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000089C74C1C18>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/af51c4a37041a0358912e3796754411f
2019-07-15 17:33:46,992 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000089C76E5908>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/af51c4a37041a0358912e3796754411f
2019-07-15 17:33:48,009 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000089C76E5CF8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/af51c4a37041a0358912e3796754411f
2019-07-15 17:33:52,213 - INFO - review_us_pool.py[:486] - ********************************pool sleep 3s************************************
2019-07-15 17:33:53,167 - INFO - review_us_pool.py[:480] - 成功获取到1条待评论的数据！
2019-07-15 17:36:27,705 - INFO - review_us_pool.py[:103] - [taskid: 2235]登录时发现滑块验证码，程序退出！
2019-07-15 17:36:30,856 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000B49293FC88>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/80a5e98f7e5edad1b495c44e6f480625/element
2019-07-15 17:36:31,871 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000B49295E5F8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/80a5e98f7e5edad1b495c44e6f480625/element
2019-07-15 17:36:32,903 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000B49295E940>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/80a5e98f7e5edad1b495c44e6f480625/element
2019-07-15 17:36:37,029 - INFO - review_us_pool.py[:486] - ********************************pool sleep 3s************************************
2019-07-15 17:36:40,640 - INFO - review_us_pool.py[:480] - 成功获取到1条待评论的数据！
2019-07-15 17:38:35,371 - INFO - review_us_pool.py[:417] - [taskid: 2235]账户登录日志已成功插入！
2019-07-15 17:38:36,201 - INFO - review_us_pool.py[:423] - [taskid: 2235]对应账户的header和cookies字段已成功修改!
2019-07-15 17:39:16,046 - INFO - review_us_pool.py[:201] - [taskid: 2235]找到目标订单所在的tbody!
2019-07-15 17:39:16,130 - INFO - review_us_pool.py[:238] - [taskid: 2235]卖家尚未发货，暂时不能留评，程序退出！
2019-07-15 17:39:18,281 - INFO - review_us_pool.py[:242] - [taskid: 2235]当前账户操作完毕，关闭当前浏览器！
2019-07-15 17:39:19,298 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000E89194FCF8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/939b527e0b862b83853957bc68263e6a
2019-07-15 17:39:20,329 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000E89196E470>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/939b527e0b862b83853957bc68263e6a
2019-07-15 17:39:21,329 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000E89196E6A0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/939b527e0b862b83853957bc68263e6a
2019-07-15 17:39:25,456 - INFO - review_us_pool.py[:486] - ********************************pool sleep 3s************************************
2019-07-15 17:39:25,940 - INFO - review_us_pool.py[:480] - 成功获取到1条待评论的数据！
2019-07-15 17:40:58,282 - INFO - review_us_pool.py[:417] - [taskid: 2235]账户登录日志已成功插入！
2019-07-15 17:41:00,015 - INFO - review_us_pool.py[:423] - [taskid: 2235]对应账户的header和cookies字段已成功修改!
2019-07-15 17:41:22,872 - INFO - review_us_pool.py[:201] - [taskid: 2235]找到目标订单所在的tbody!
2019-07-15 17:41:22,951 - INFO - review_us_pool.py[:238] - [taskid: 2235]卖家尚未发货，暂时不能留评，程序退出！
2019-07-15 17:41:26,105 - INFO - review_us_pool.py[:242] - [taskid: 2235]当前账户操作完毕，关闭当前浏览器！
2019-07-15 17:41:27,120 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000620FC9FCC0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/5ce0db0c228245a1ace22d573ab2ebb0
2019-07-15 17:41:28,137 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000062102A5358>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/5ce0db0c228245a1ace22d573ab2ebb0
2019-07-15 17:41:29,152 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000062102A55C0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/5ce0db0c228245a1ace22d573ab2ebb0
2019-07-15 17:41:33,389 - INFO - review_us_pool.py[:486] - ********************************pool sleep 3s************************************
2019-07-15 17:41:34,358 - INFO - review_us_pool.py[:480] - 成功获取到1条待评论的数据！
2019-07-15 17:45:03,445 - INFO - review_us_pool.py[:246] - [taskid: 2235]等待超时,或者元素位未完全加载导致定位出错!
2019-07-15 17:45:03,445 - INFO - review_us_pool.py[:247] - [taskid: 2235]关闭当前浏览器，结束当前线程！
2019-07-15 17:45:03,445 - INFO - review_us_pool.py[:248] - [taskid: 2235]系统会自动生成新的线程来执行留评任务！
2019-07-15 17:45:09,713 - INFO - review_us_pool.py[:486] - ********************************pool sleep 3s************************************
2019-07-15 17:45:10,198 - INFO - review_us_pool.py[:480] - 成功获取到1条待评论的数据！
2019-07-15 17:46:41,131 - INFO - review_us_pool.py[:246] - [taskid: 2235]等待超时,或者元素位未完全加载导致定位出错!
2019-07-15 17:46:41,131 - INFO - review_us_pool.py[:247] - [taskid: 2235]关闭当前浏览器，结束当前线程！
2019-07-15 17:46:41,131 - INFO - review_us_pool.py[:248] - [taskid: 2235]系统会自动生成新的线程来执行留评任务！
2019-07-15 17:46:47,477 - INFO - review_us_pool.py[:486] - ********************************pool sleep 3s************************************
2019-07-15 17:46:47,977 - INFO - review_us_pool.py[:480] - 成功获取到1条待评论的数据！
2019-07-15 17:50:46,156 - INFO - review_us_pool.py[:417] - [taskid: 2235]账户登录日志已成功插入！
2019-07-15 17:50:46,805 - INFO - review_us_pool.py[:423] - [taskid: 2235]对应账户的header和cookies字段已成功修改!
2019-07-15 17:51:09,013 - INFO - review_us_pool.py[:201] - [taskid: 2235]找到目标订单所在的tbody!
2019-07-15 17:51:09,096 - INFO - review_us_pool.py[:238] - [taskid: 2235]卖家尚未发货，暂时不能留评，程序退出！
2019-07-15 17:51:11,263 - INFO - review_us_pool.py[:242] - [taskid: 2235]当前账户操作完毕，关闭当前浏览器！
2019-07-15 17:51:12,280 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000522402FCF8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/c62cc89148cf93158bb8f53d1fc5ed83
2019-07-15 17:51:13,311 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000005224635390>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/c62cc89148cf93158bb8f53d1fc5ed83
2019-07-15 17:51:14,344 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000052246355C0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/c62cc89148cf93158bb8f53d1fc5ed83
2019-07-15 17:51:18,548 - INFO - review_us_pool.py[:486] - ********************************pool sleep 3s************************************
2019-07-15 17:51:19,157 - INFO - review_us_pool.py[:480] - 成功获取到1条待评论的数据！
2019-07-15 17:52:49,380 - INFO - review_us_pool.py[:246] - [taskid: 2235]等待超时,或者元素位未完全加载导致定位出错!
2019-07-15 17:52:49,380 - INFO - review_us_pool.py[:247] - [taskid: 2235]关闭当前浏览器，结束当前线程！
2019-07-15 17:52:49,380 - INFO - review_us_pool.py[:248] - [taskid: 2235]系统会自动生成新的线程来执行留评任务！
2019-07-15 17:52:55,726 - INFO - review_us_pool.py[:486] - ********************************pool sleep 3s************************************
2019-07-15 17:52:56,445 - INFO - review_us_pool.py[:480] - 成功获取到1条待评论的数据！
2019-07-15 17:56:08,532 - INFO - review_us_pool.py[:417] - [taskid: 2235]账户登录日志已成功插入！
2019-07-15 17:56:09,129 - INFO - review_us_pool.py[:423] - [taskid: 2235]对应账户的header和cookies字段已成功修改!
2019-07-15 17:58:38,175 - INFO - review_us_pool.py[:201] - [taskid: 2235]找到目标订单所在的tbody!
2019-07-15 17:58:38,260 - INFO - review_us_pool.py[:238] - [taskid: 2235]卖家尚未发货，暂时不能留评，程序退出！
2019-07-15 17:58:41,437 - INFO - review_us_pool.py[:242] - [taskid: 2235]当前账户操作完毕，关闭当前浏览器！
2019-07-15 17:58:42,471 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000F47DFEFCC0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/756ba1fbbeee2d730eeb3d8e60f37c48
2019-07-15 17:58:43,501 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000F47E00E438>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/756ba1fbbeee2d730eeb3d8e60f37c48
2019-07-15 17:58:44,532 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000F47E00E470>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/756ba1fbbeee2d730eeb3d8e60f37c48
2019-07-15 17:58:48,706 - INFO - review_us_pool.py[:486] - ********************************pool sleep 3s************************************
2019-07-15 17:58:49,800 - INFO - review_us_pool.py[:480] - 成功获取到1条待评论的数据！
2019-07-15 18:00:11,755 - INFO - review_us_pool.py[:417] - [taskid: 2235]账户登录日志已成功插入！
2019-07-15 18:00:12,385 - INFO - review_us_pool.py[:423] - [taskid: 2235]对应账户的header和cookies字段已成功修改!
2019-07-15 18:00:30,267 - INFO - review_us_pool.py[:201] - [taskid: 2235]找到目标订单所在的tbody!
2019-07-15 18:00:30,350 - INFO - review_us_pool.py[:238] - [taskid: 2235]卖家尚未发货，暂时不能留评，程序退出！
2019-07-15 18:00:32,526 - INFO - review_us_pool.py[:242] - [taskid: 2235]当前账户操作完毕，关闭当前浏览器！
2019-07-15 18:00:33,541 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000CC868EFCC0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/2f8fd4f3694fa961f3b3bd54028bda85
2019-07-15 18:00:34,573 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000CC8690E470>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/2f8fd4f3694fa961f3b3bd54028bda85
2019-07-15 18:00:35,589 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000CC86B15898>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/2f8fd4f3694fa961f3b3bd54028bda85
2019-07-15 18:00:39,763 - INFO - review_us_pool.py[:486] - ********************************pool sleep 3s************************************
2019-07-15 18:00:41,935 - INFO - review_us_pool.py[:480] - 成功获取到1条待评论的数据！
2019-07-15 18:02:12,875 - INFO - review_us_pool.py[:246] - [taskid: 2235]等待超时,或者元素位未完全加载导致定位出错!
2019-07-15 18:02:12,875 - INFO - review_us_pool.py[:247] - [taskid: 2235]关闭当前浏览器，结束当前线程！
2019-07-15 18:02:12,875 - INFO - review_us_pool.py[:248] - [taskid: 2235]系统会自动生成新的线程来执行留评任务！
2019-07-15 18:02:19,097 - INFO - review_us_pool.py[:486] - ********************************pool sleep 3s************************************
2019-07-15 18:02:20,018 - INFO - review_us_pool.py[:480] - 成功获取到1条待评论的数据！
2019-07-15 18:05:14,505 - INFO - review_us_pool.py[:417] - [taskid: 2235]账户登录日志已成功插入！
2019-07-15 18:05:15,256 - INFO - review_us_pool.py[:423] - [taskid: 2235]对应账户的header和cookies字段已成功修改!
2019-07-15 18:06:07,521 - INFO - review_us_pool.py[:201] - [taskid: 2235]找到目标订单所在的tbody!
2019-07-15 18:06:07,605 - INFO - review_us_pool.py[:238] - [taskid: 2235]卖家尚未发货，暂时不能留评，程序退出！
2019-07-15 18:06:10,780 - INFO - review_us_pool.py[:242] - [taskid: 2235]当前账户操作完毕，关闭当前浏览器！
2019-07-15 18:06:11,795 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000019A494FC88>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/535ee27681c59bb52bf29c8a7c484333
2019-07-15 18:06:12,811 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000019A496E160>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/535ee27681c59bb52bf29c8a7c484333
2019-07-15 18:06:13,828 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000019A4B75860>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/535ee27681c59bb52bf29c8a7c484333
2019-07-15 18:06:17,986 - INFO - review_us_pool.py[:486] - ********************************pool sleep 3s************************************
2019-07-15 18:06:19,986 - INFO - review_us_pool.py[:480] - 成功获取到1条待评论的数据！
2019-07-15 18:09:23,951 - INFO - review_us_pool.py[:246] - [taskid: 2235]等待超时,或者元素位未完全加载导致定位出错!
2019-07-15 18:09:23,951 - INFO - review_us_pool.py[:247] - [taskid: 2235]关闭当前浏览器，结束当前线程！
2019-07-15 18:09:23,951 - INFO - review_us_pool.py[:248] - [taskid: 2235]系统会自动生成新的线程来执行留评任务！
2019-07-15 18:09:30,204 - INFO - review_us_pool.py[:486] - ********************************pool sleep 3s************************************
2019-07-15 18:09:30,610 - INFO - review_us_pool.py[:480] - 成功获取到1条待评论的数据！
2019-07-15 18:11:07,606 - INFO - review_us_pool.py[:417] - [taskid: 2235]账户登录日志已成功插入！
2019-07-15 18:11:08,194 - INFO - review_us_pool.py[:423] - [taskid: 2235]对应账户的header和cookies字段已成功修改!
2019-07-15 18:11:33,797 - INFO - review_us_pool.py[:201] - [taskid: 2235]找到目标订单所在的tbody!
2019-07-15 18:11:33,880 - INFO - review_us_pool.py[:238] - [taskid: 2235]卖家尚未发货，暂时不能留评，程序退出！
2019-07-15 18:11:37,084 - INFO - review_us_pool.py[:242] - [taskid: 2235]当前账户操作完毕，关闭当前浏览器！
2019-07-15 18:11:38,101 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000026BF2FCC0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/c6ff3586a5966eb216a2804c6f4ad892
2019-07-15 18:11:39,132 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000026C535358>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/c6ff3586a5966eb216a2804c6f4ad892
2019-07-15 18:11:40,149 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000026C5355C0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/c6ff3586a5966eb216a2804c6f4ad892
2019-07-15 18:11:44,322 - INFO - review_us_pool.py[:486] - ********************************pool sleep 3s************************************
2019-07-15 18:11:45,087 - INFO - review_us_pool.py[:480] - 成功获取到1条待评论的数据！
2019-07-15 18:14:06,666 - INFO - review_us_pool.py[:417] - [taskid: 2235]账户登录日志已成功插入！
2019-07-15 18:14:07,585 - INFO - review_us_pool.py[:423] - [taskid: 2235]对应账户的header和cookies字段已成功修改!
2019-07-15 18:14:34,829 - INFO - review_us_pool.py[:201] - [taskid: 2235]找到目标订单所在的tbody!
