2019-07-15 18:14:45,336 - INFO - review_us_pool.py[:486] - ********************************pool sleep 3s************************************
2019-07-15 18:14:45,790 - INFO - review_us_pool.py[:480] - 成功获取到1条待评论的数据！
2019-07-15 18:16:22,632 - INFO - review_us_pool.py[:417] - [taskid: 2235]账户登录日志已成功插入！
2019-07-15 18:16:23,359 - INFO - review_us_pool.py[:423] - [taskid: 2235]对应账户的header和cookies字段已成功修改!
2019-07-15 18:17:05,412 - INFO - review_us_pool.py[:201] - [taskid: 2235]找到目标订单所在的tbody!
2019-07-15 18:17:05,495 - INFO - review_us_pool.py[:238] - [taskid: 2235]卖家尚未发货，暂时不能留评，程序退出！
2019-07-15 18:17:07,657 - INFO - review_us_pool.py[:242] - [taskid: 2235]当前账户操作完毕，关闭当前浏览器！
2019-07-15 18:17:08,689 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000BCF1F4FCF8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/3edf66180034fcaf28464cf86d8bd03e
2019-07-15 18:17:09,722 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000BCF2555240>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/3edf66180034fcaf28464cf86d8bd03e
2019-07-15 18:17:10,737 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000BCF25556D8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/3edf66180034fcaf28464cf86d8bd03e
2019-07-15 18:17:14,864 - INFO - review_us_pool.py[:486] - ********************************pool sleep 3s************************************
2019-07-15 18:17:16,802 - INFO - review_us_pool.py[:480] - 成功获取到1条待评论的数据！
2019-07-15 18:18:48,859 - INFO - review_us_pool.py[:246] - [taskid: 2235]等待超时,或者元素位未完全加载导致定位出错!
2019-07-15 18:18:48,859 - INFO - review_us_pool.py[:247] - [taskid: 2235]关闭当前浏览器，结束当前线程！
2019-07-15 18:18:48,859 - INFO - review_us_pool.py[:248] - [taskid: 2235]系统会自动生成新的线程来执行留评任务！
2019-07-15 18:18:55,079 - INFO - review_us_pool.py[:486] - ********************************pool sleep 3s************************************
2019-07-15 18:18:55,798 - INFO - review_us_pool.py[:480] - 成功获取到1条待评论的数据！
2019-07-15 18:21:25,863 - INFO - review_us_pool.py[:246] - [taskid: 2235]等待超时,或者元素位未完全加载导致定位出错!
2019-07-15 18:21:25,863 - INFO - review_us_pool.py[:247] - [taskid: 2235]关闭当前浏览器，结束当前线程！
2019-07-15 18:21:25,863 - INFO - review_us_pool.py[:248] - [taskid: 2235]系统会自动生成新的线程来执行留评任务！
2019-07-15 18:21:32,116 - INFO - review_us_pool.py[:486] - ********************************pool sleep 3s************************************
2019-07-15 18:21:34,695 - INFO - review_us_pool.py[:480] - 成功获取到1条待评论的数据！
2019-07-15 18:22:30,150 - INFO - review_us_pool.py[:246] - [taskid: 2235]等待超时,或者元素位未完全加载导致定位出错!
2019-07-15 18:22:30,150 - INFO - review_us_pool.py[:247] - [taskid: 2235]关闭当前浏览器，结束当前线程！
2019-07-15 18:22:30,150 - INFO - review_us_pool.py[:248] - [taskid: 2235]系统会自动生成新的线程来执行留评任务！
2019-07-15 18:22:36,387 - INFO - review_us_pool.py[:486] - ********************************pool sleep 3s************************************
2019-07-15 18:22:37,232 - INFO - review_us_pool.py[:480] - 成功获取到1条待评论的数据！
2019-07-15 18:24:00,744 - INFO - review_us_pool.py[:417] - [taskid: 2235]账户登录日志已成功插入！
2019-07-15 18:24:01,426 - INFO - review_us_pool.py[:423] - [taskid: 2235]对应账户的header和cookies字段已成功修改!
2019-07-15 18:24:19,937 - INFO - review_us_pool.py[:201] - [taskid: 2235]找到目标订单所在的tbody!
2019-07-15 18:24:20,016 - INFO - review_us_pool.py[:238] - [taskid: 2235]卖家尚未发货，暂时不能留评，程序退出！
2019-07-15 18:24:23,166 - INFO - review_us_pool.py[:242] - [taskid: 2235]当前账户操作完毕，关闭当前浏览器！
2019-07-15 18:24:24,181 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000572CBAFCF8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/cdc117a87c3669711db6cbf5f20cba82
2019-07-15 18:24:25,213 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000572CBCE470>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/cdc117a87c3669711db6cbf5f20cba82
2019-07-15 18:24:26,229 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000572CBCE668>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/cdc117a87c3669711db6cbf5f20cba82
2019-07-15 18:24:30,418 - INFO - review_us_pool.py[:486] - ********************************pool sleep 3s************************************
2019-07-15 18:24:30,965 - INFO - review_us_pool.py[:480] - 成功获取到1条待评论的数据！
2019-07-15 18:26:03,569 - INFO - review_us_pool.py[:246] - [taskid: 2235]等待超时,或者元素位未完全加载导致定位出错!
2019-07-15 18:26:03,569 - INFO - review_us_pool.py[:247] - [taskid: 2235]关闭当前浏览器，结束当前线程！
2019-07-15 18:26:03,569 - INFO - review_us_pool.py[:248] - [taskid: 2235]系统会自动生成新的线程来执行留评任务！
2019-07-15 18:26:09,805 - INFO - review_us_pool.py[:486] - ********************************pool sleep 3s************************************
2019-07-15 18:26:10,211 - INFO - review_us_pool.py[:480] - 成功获取到1条待评论的数据！
2019-07-15 18:27:28,675 - INFO - review_us_pool.py[:417] - [taskid: 2235]账户登录日志已成功插入！
2019-07-15 18:27:29,437 - INFO - review_us_pool.py[:423] - [taskid: 2235]对应账户的header和cookies字段已成功修改!
2019-07-15 18:27:47,894 - INFO - review_us_pool.py[:201] - [taskid: 2235]找到目标订单所在的tbody!
2019-07-15 18:27:47,977 - INFO - review_us_pool.py[:238] - [taskid: 2235]卖家尚未发货，暂时不能留评，程序退出！
2019-07-15 18:27:51,127 - INFO - review_us_pool.py[:242] - [taskid: 2235]当前账户操作完毕，关闭当前浏览器！
2019-07-15 18:27:52,143 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000008D46A61CF8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/ff5d31aaadf623c20d237189a5dffd84
2019-07-15 18:27:53,159 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000008D46C859B0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/ff5d31aaadf623c20d237189a5dffd84
2019-07-15 18:27:54,176 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000008D46C85DA0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/ff5d31aaadf623c20d237189a5dffd84
2019-07-15 18:27:58,364 - INFO - review_us_pool.py[:486] - ********************************pool sleep 3s************************************
2019-07-15 18:28:00,474 - INFO - review_us_pool.py[:480] - 成功获取到1条待评论的数据！
2019-07-15 18:32:21,750 - INFO - review_us_pool.py[:246] - [taskid: 2235]等待超时,或者元素位未完全加载导致定位出错!
2019-07-15 18:32:21,750 - INFO - review_us_pool.py[:247] - [taskid: 2235]关闭当前浏览器，结束当前线程！
2019-07-15 18:32:21,750 - INFO - review_us_pool.py[:248] - [taskid: 2235]系统会自动生成新的线程来执行留评任务！
2019-07-15 18:32:28,035 - INFO - review_us_pool.py[:486] - ********************************pool sleep 3s************************************
2019-07-15 18:32:28,597 - INFO - review_us_pool.py[:480] - 成功获取到1条待评论的数据！
2019-07-15 18:36:50,081 - INFO - review_us_pool.py[:246] - [taskid: 2235]等待超时,或者元素位未完全加载导致定位出错!
2019-07-15 18:36:50,081 - INFO - review_us_pool.py[:247] - [taskid: 2235]关闭当前浏览器，结束当前线程！
2019-07-15 18:36:50,081 - INFO - review_us_pool.py[:248] - [taskid: 2235]系统会自动生成新的线程来执行留评任务！
2019-07-15 18:36:56,396 - INFO - review_us_pool.py[:486] - ********************************pool sleep 3s************************************
2019-07-15 18:38:28,435 - INFO - review_us_pool.py[:490] - 任务系统出错，程序[sleep 30s]...
2019-07-15 18:38:59,432 - INFO - review_us_pool.py[:480] - 成功获取到1条待评论的数据！
2019-07-15 18:40:17,616 - INFO - review_us_pool.py[:417] - [taskid: 2235]账户登录日志已成功插入！
2019-07-15 18:40:18,212 - INFO - review_us_pool.py[:423] - [taskid: 2235]对应账户的header和cookies字段已成功修改!
2019-07-15 18:40:36,207 - INFO - review_us_pool.py[:201] - [taskid: 2235]找到目标订单所在的tbody!
2019-07-15 18:40:36,295 - INFO - review_us_pool.py[:238] - [taskid: 2235]卖家尚未发货，暂时不能留评，程序退出！
2019-07-15 18:40:39,500 - INFO - review_us_pool.py[:242] - [taskid: 2235]当前账户操作完毕，关闭当前浏览器！
2019-07-15 18:40:40,516 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000004E974EFCC0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/c46bc5799b360d2ca594c85fd5ff00ed
2019-07-15 18:40:41,532 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000004E9750E2B0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/c46bc5799b360d2ca594c85fd5ff00ed
2019-07-15 18:40:42,549 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000004E9750E588>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/c46bc5799b360d2ca594c85fd5ff00ed
2019-07-15 18:40:46,737 - INFO - review_us_pool.py[:486] - ********************************pool sleep 3s************************************
2019-07-15 18:40:47,378 - INFO - review_us_pool.py[:480] - 成功获取到1条待评论的数据！
2019-07-15 18:43:12,573 - INFO - review_us_pool.py[:246] - [taskid: 2235]等待超时,或者元素位未完全加载导致定位出错!
2019-07-15 18:43:12,573 - INFO - review_us_pool.py[:247] - [taskid: 2235]关闭当前浏览器，结束当前线程！
2019-07-15 18:43:12,573 - INFO - review_us_pool.py[:248] - [taskid: 2235]系统会自动生成新的线程来执行留评任务！
2019-07-15 18:43:18,872 - INFO - review_us_pool.py[:486] - ********************************pool sleep 3s************************************
2019-07-15 18:43:19,294 - INFO - review_us_pool.py[:480] - 成功获取到1条待评论的数据！
2019-07-15 18:46:17,657 - INFO - review_us_pool.py[:417] - [taskid: 2235]账户登录日志已成功插入！
2019-07-15 18:46:18,923 - INFO - review_us_pool.py[:423] - [taskid: 2235]对应账户的header和cookies字段已成功修改!
2019-07-15 18:47:14,745 - INFO - review_us_pool.py[:201] - [taskid: 2235]找到目标订单所在的tbody!
2019-07-15 18:47:14,828 - INFO - review_us_pool.py[:238] - [taskid: 2235]卖家尚未发货，暂时不能留评，程序退出！
2019-07-15 18:47:17,994 - INFO - review_us_pool.py[:242] - [taskid: 2235]当前账户操作完毕，关闭当前浏览器！
2019-07-15 18:47:19,010 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000E618021CC0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/76a6dbf56f1de86e3b847d81129a5eac
2019-07-15 18:47:20,042 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000E61803E358>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/76a6dbf56f1de86e3b847d81129a5eac
2019-07-15 18:47:21,073 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000E61803E668>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/76a6dbf56f1de86e3b847d81129a5eac
2019-07-15 18:47:25,247 - INFO - review_us_pool.py[:486] - ********************************pool sleep 3s************************************
2019-07-15 18:47:26,450 - INFO - review_us_pool.py[:480] - 成功获取到1条待评论的数据！
2019-07-15 18:49:13,809 - INFO - review_us_pool.py[:417] - [taskid: 2235]账户登录日志已成功插入！
2019-07-15 18:49:14,434 - INFO - review_us_pool.py[:423] - [taskid: 2235]对应账户的header和cookies字段已成功修改!
2019-07-15 18:49:48,296 - INFO - review_us_pool.py[:201] - [taskid: 2235]找到目标订单所在的tbody!
2019-07-15 18:49:48,386 - INFO - review_us_pool.py[:238] - [taskid: 2235]卖家尚未发货，暂时不能留评，程序退出！
2019-07-15 18:49:50,558 - INFO - review_us_pool.py[:242] - [taskid: 2235]当前账户操作完毕，关闭当前浏览器！
2019-07-15 18:49:51,589 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000F7F9C61CC0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/b6177d2e587cf213d46a219f243aa9c7
2019-07-15 18:49:52,621 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000F7F9C7E400>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/b6177d2e587cf213d46a219f243aa9c7
2019-07-15 18:49:53,637 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000F7F9C7E128>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/b6177d2e587cf213d46a219f243aa9c7
2019-07-15 18:49:57,827 - INFO - review_us_pool.py[:486] - ********************************pool sleep 3s************************************
2019-07-15 18:50:07,299 - INFO - review_us_pool.py[:480] - 成功获取到1条待评论的数据！
2019-07-15 18:51:30,865 - INFO - review_us_pool.py[:417] - [taskid: 2235]账户登录日志已成功插入！
2019-07-15 18:51:31,704 - INFO - review_us_pool.py[:423] - [taskid: 2235]对应账户的header和cookies字段已成功修改!
2019-07-15 18:51:50,360 - INFO - review_us_pool.py[:201] - [taskid: 2235]找到目标订单所在的tbody!
2019-07-15 18:51:50,440 - INFO - review_us_pool.py[:238] - [taskid: 2235]卖家尚未发货，暂时不能留评，程序退出！
2019-07-15 18:51:53,624 - INFO - review_us_pool.py[:242] - [taskid: 2235]当前账户操作完毕，关闭当前浏览器！
2019-07-15 18:51:54,640 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000008DFB8CFC88>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/9296fde13e56f168109be05dea0dc60f
2019-07-15 18:51:55,655 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000008DFBAF5320>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/9296fde13e56f168109be05dea0dc60f
2019-07-15 18:51:56,671 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000008DFBAF5588>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/9296fde13e56f168109be05dea0dc60f
2019-07-15 18:52:00,783 - INFO - review_us_pool.py[:486] - ********************************pool sleep 3s************************************
2019-07-15 18:52:01,470 - INFO - review_us_pool.py[:480] - 成功获取到1条待评论的数据！
2019-07-15 18:53:32,313 - INFO - review_us_pool.py[:246] - [taskid: 2235]等待超时,或者元素位未完全加载导致定位出错!
2019-07-15 18:53:32,313 - INFO - review_us_pool.py[:247] - [taskid: 2235]关闭当前浏览器，结束当前线程！
2019-07-15 18:53:32,313 - INFO - review_us_pool.py[:248] - [taskid: 2235]系统会自动生成新的线程来执行留评任务！
2019-07-15 18:53:37,550 - INFO - review_us_pool.py[:486] - ********************************pool sleep 3s************************************
2019-07-15 18:53:38,629 - INFO - review_us_pool.py[:480] - 成功获取到1条待评论的数据！
2019-07-15 18:55:24,047 - INFO - review_us_pool.py[:417] - [taskid: 2235]账户登录日志已成功插入！
2019-07-15 18:55:34,205 - INFO - review_us_pool.py[:423] - [taskid: 2235]对应账户的header和cookies字段已成功修改!
2019-07-15 18:56:00,543 - INFO - review_us_pool.py[:201] - [taskid: 2235]找到目标订单所在的tbody!
2019-07-15 18:56:00,625 - INFO - review_us_pool.py[:238] - [taskid: 2235]卖家尚未发货，暂时不能留评，程序退出！
2019-07-15 18:56:02,789 - INFO - review_us_pool.py[:242] - [taskid: 2235]当前账户操作完毕，关闭当前浏览器！
2019-07-15 18:56:03,821 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000841F08FCC0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/430c41f1b86610104a8b0754a4acc672
2019-07-15 18:56:04,853 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000841F0AE198>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/430c41f1b86610104a8b0754a4acc672
2019-07-15 18:56:05,869 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000841F695828>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/430c41f1b86610104a8b0754a4acc672
2019-07-15 18:56:10,042 - INFO - review_us_pool.py[:486] - ********************************pool sleep 3s************************************
2019-07-15 18:56:10,449 - INFO - review_us_pool.py[:480] - 成功获取到1条待评论的数据！
2019-07-15 18:58:47,199 - INFO - review_us_pool.py[:246] - [taskid: 2235]等待超时,或者元素位未完全加载导致定位出错!
2019-07-15 18:58:47,199 - INFO - review_us_pool.py[:247] - [taskid: 2235]关闭当前浏览器，结束当前线程！
2019-07-15 18:58:47,199 - INFO - review_us_pool.py[:248] - [taskid: 2235]系统会自动生成新的线程来执行留评任务！
2019-07-15 18:58:52,484 - INFO - review_us_pool.py[:486] - ********************************pool sleep 3s************************************
2019-07-15 18:58:53,327 - INFO - review_us_pool.py[:480] - 成功获取到1条待评论的数据！
2019-07-15 19:00:45,811 - INFO - review_us_pool.py[:417] - [taskid: 2235]账户登录日志已成功插入！
2019-07-15 19:00:46,977 - INFO - review_us_pool.py[:423] - [taskid: 2235]对应账户的header和cookies字段已成功修改!
2019-07-15 19:01:15,452 - INFO - review_us_pool.py[:201] - [taskid: 2235]找到目标订单所在的tbody!
2019-07-15 19:01:15,540 - INFO - review_us_pool.py[:238] - [taskid: 2235]卖家尚未发货，暂时不能留评，程序退出！
2019-07-15 19:01:18,715 - INFO - review_us_pool.py[:242] - [taskid: 2235]当前账户操作完毕，关闭当前浏览器！
2019-07-15 19:01:19,748 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000038AD27FCC0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/01881e6fb09b63ed3a61d4bbb2a7840f
2019-07-15 19:01:20,763 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000038AD29E198>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/01881e6fb09b63ed3a61d4bbb2a7840f
2019-07-15 19:01:21,779 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000038AD885898>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/01881e6fb09b63ed3a61d4bbb2a7840f
2019-07-15 19:01:25,921 - INFO - review_us_pool.py[:486] - ********************************pool sleep 3s************************************
2019-07-15 19:01:26,999 - INFO - review_us_pool.py[:480] - 成功获取到1条待评论的数据！
2019-07-15 19:03:11,754 - INFO - review_us_pool.py[:417] - [taskid: 2235]账户登录日志已成功插入！
2019-07-15 19:03:12,354 - INFO - review_us_pool.py[:423] - [taskid: 2235]对应账户的header和cookies字段已成功修改!
2019-07-15 19:03:40,420 - INFO - review_us_pool.py[:201] - [taskid: 2235]找到目标订单所在的tbody!
2019-07-15 19:03:40,502 - INFO - review_us_pool.py[:238] - [taskid: 2235]卖家尚未发货，暂时不能留评，程序退出！
2019-07-15 19:03:43,662 - INFO - review_us_pool.py[:242] - [taskid: 2235]当前账户操作完毕，关闭当前浏览器！
2019-07-15 19:03:44,693 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000E02369FCF8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/87f3cf977394df3248355a4eccc1d125
2019-07-15 19:03:45,710 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000E0236BE588>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/87f3cf977394df3248355a4eccc1d125
2019-07-15 19:03:46,741 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000E0236BE6A0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/87f3cf977394df3248355a4eccc1d125
2019-07-15 19:03:50,946 - INFO - review_us_pool.py[:486] - ********************************pool sleep 3s************************************
2019-07-15 19:03:51,571 - INFO - review_us_pool.py[:480] - 成功获取到1条待评论的数据！
2019-07-15 19:05:09,409 - INFO - review_us_pool.py[:103] - [taskid: 2235]登录时发现滑块验证码，程序退出！
2019-07-15 19:05:13,630 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000734517FC50>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/25a4c1ca03c7b2690e335b7491b57648/element
2019-07-15 19:05:14,646 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000734519E5C0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/25a4c1ca03c7b2690e335b7491b57648/element
2019-07-15 19:05:15,647 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000734519E908>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/25a4c1ca03c7b2690e335b7491b57648/element
2019-07-15 19:05:19,789 - INFO - review_us_pool.py[:486] - ********************************pool sleep 3s************************************
2019-07-15 19:05:20,414 - INFO - review_us_pool.py[:480] - 成功获取到1条待评论的数据！
2019-07-15 19:08:04,774 - INFO - review_us_pool.py[:246] - [taskid: 2235]等待超时,或者元素位未完全加载导致定位出错!
2019-07-15 19:08:04,775 - INFO - review_us_pool.py[:247] - [taskid: 2235]关闭当前浏览器，结束当前线程！
2019-07-15 19:08:04,775 - INFO - review_us_pool.py[:248] - [taskid: 2235]系统会自动生成新的线程来执行留评任务！
2019-07-15 19:08:10,050 - INFO - review_us_pool.py[:486] - ********************************pool sleep 3s************************************
2019-07-15 19:08:10,956 - INFO - review_us_pool.py[:480] - 成功获取到1条待评论的数据！
2019-07-15 19:10:48,646 - INFO - review_us_pool.py[:246] - [taskid: 2235]等待超时,或者元素位未完全加载导致定位出错!
2019-07-15 19:10:48,646 - INFO - review_us_pool.py[:247] - [taskid: 2235]关闭当前浏览器，结束当前线程！
2019-07-15 19:10:48,646 - INFO - review_us_pool.py[:248] - [taskid: 2235]系统会自动生成新的线程来执行留评任务！
2019-07-15 19:10:54,915 - INFO - review_us_pool.py[:486] - ********************************pool sleep 3s************************************
2019-07-15 19:10:55,587 - INFO - review_us_pool.py[:480] - 成功获取到1条待评论的数据！
2019-07-15 19:12:20,752 - INFO - review_us_pool.py[:417] - [taskid: 2235]账户登录日志已成功插入！
2019-07-15 19:12:21,348 - INFO - review_us_pool.py[:423] - [taskid: 2235]对应账户的header和cookies字段已成功修改!
2019-07-15 19:12:40,118 - INFO - review_us_pool.py[:201] - [taskid: 2235]找到目标订单所在的tbody!
2019-07-15 19:12:40,194 - INFO - review_us_pool.py[:238] - [taskid: 2235]卖家尚未发货，暂时不能留评，程序退出！
2019-07-15 19:12:43,376 - INFO - review_us_pool.py[:242] - [taskid: 2235]当前账户操作完毕，关闭当前浏览器！
2019-07-15 19:12:44,392 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000DC9559FCC0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/49a30408028a4dde3bc33727d7d6cea5
2019-07-15 19:12:45,408 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000DC957C5358>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/49a30408028a4dde3bc33727d7d6cea5
2019-07-15 19:12:46,409 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000DC957C55C0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/49a30408028a4dde3bc33727d7d6cea5
2019-07-15 19:12:50,582 - INFO - review_us_pool.py[:486] - ********************************pool sleep 3s************************************
2019-07-15 19:12:52,536 - INFO - review_us_pool.py[:480] - 成功获取到1条待评论的数据！
2019-07-15 19:14:22,261 - INFO - review_us_pool.py[:246] - [taskid: 2235]等待超时,或者元素位未完全加载导致定位出错!
2019-07-15 19:14:22,261 - INFO - review_us_pool.py[:247] - [taskid: 2235]关闭当前浏览器，结束当前线程！
2019-07-15 19:14:22,261 - INFO - review_us_pool.py[:248] - [taskid: 2235]系统会自动生成新的线程来执行留评任务！
2019-07-15 19:14:28,514 - INFO - review_us_pool.py[:486] - ********************************pool sleep 3s************************************
2019-07-15 19:14:29,295 - INFO - review_us_pool.py[:480] - 成功获取到1条待评论的数据！
2019-07-15 19:18:03,236 - INFO - review_us_pool.py[:246] - [taskid: 2235]等待超时,或者元素位未完全加载导致定位出错!
2019-07-15 19:18:03,236 - INFO - review_us_pool.py[:247] - [taskid: 2235]关闭当前浏览器，结束当前线程！
2019-07-15 19:18:03,236 - INFO - review_us_pool.py[:248] - [taskid: 2235]系统会自动生成新的线程来执行留评任务！
2019-07-15 19:18:09,520 - INFO - review_us_pool.py[:486] - ********************************pool sleep 3s************************************
2019-07-15 19:18:10,614 - INFO - review_us_pool.py[:480] - 成功获取到1条待评论的数据！
2019-07-15 19:20:15,364 - INFO - review_us_pool.py[:246] - [taskid: 2235]等待超时,或者元素位未完全加载导致定位出错!
2019-07-15 19:20:15,364 - INFO - review_us_pool.py[:247] - [taskid: 2235]关闭当前浏览器，结束当前线程！
2019-07-15 19:20:15,364 - INFO - review_us_pool.py[:248] - [taskid: 2235]系统会自动生成新的线程来执行留评任务！
2019-07-15 19:20:21,680 - INFO - review_us_pool.py[:486] - ********************************pool sleep 3s************************************
2019-07-15 19:20:22,258 - INFO - review_us_pool.py[:480] - 成功获取到1条待评论的数据！
2019-07-15 19:21:52,938 - INFO - review_us_pool.py[:246] - [taskid: 2235]等待超时,或者元素位未完全加载导致定位出错!
2019-07-15 19:21:52,938 - INFO - review_us_pool.py[:247] - [taskid: 2235]关闭当前浏览器，结束当前线程！
2019-07-15 19:21:52,938 - INFO - review_us_pool.py[:248] - [taskid: 2235]系统会自动生成新的线程来执行留评任务！
2019-07-15 19:21:59,253 - INFO - review_us_pool.py[:486] - ********************************pool sleep 3s************************************
2019-07-15 19:22:09,007 - INFO - review_us_pool.py[:480] - 成功获取到1条待评论的数据！
2019-07-15 19:23:30,266 - INFO - review_us_pool.py[:246] - [taskid: 2235]等待超时,或者元素位未完全加载导致定位出错!
2019-07-15 19:23:30,266 - INFO - review_us_pool.py[:247] - [taskid: 2235]关闭当前浏览器，结束当前线程！
2019-07-15 19:23:30,266 - INFO - review_us_pool.py[:248] - [taskid: 2235]系统会自动生成新的线程来执行留评任务！
2019-07-15 19:23:35,536 - INFO - review_us_pool.py[:486] - ********************************pool sleep 3s************************************
2019-07-15 19:23:36,675 - INFO - review_us_pool.py[:480] - 成功获取到1条待评论的数据！
2019-07-15 19:25:44,071 - INFO - review_us_pool.py[:417] - [taskid: 2235]账户登录日志已成功插入！
2019-07-15 19:25:46,400 - INFO - review_us_pool.py[:423] - [taskid: 2235]对应账户的header和cookies字段已成功修改!
2019-07-15 19:26:33,526 - INFO - review_us_pool.py[:201] - [taskid: 2235]找到目标订单所在的tbody!
2019-07-15 19:26:33,606 - INFO - review_us_pool.py[:238] - [taskid: 2235]卖家尚未发货，暂时不能留评，程序退出！
2019-07-15 19:26:35,768 - INFO - review_us_pool.py[:242] - [taskid: 2235]当前账户操作完毕，关闭当前浏览器！
2019-07-15 19:26:36,769 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000000BEC49FCC0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/58355d05ed65593189b9ab5e6e3ae029
2019-07-15 19:26:37,800 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000000BECAA5358>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/58355d05ed65593189b9ab5e6e3ae029
2019-07-15 19:26:38,832 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000000BECAA56A0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/58355d05ed65593189b9ab5e6e3ae029
2019-07-15 19:26:43,022 - INFO - review_us_pool.py[:486] - ********************************pool sleep 3s************************************
2019-07-15 19:26:44,663 - INFO - review_us_pool.py[:480] - 成功获取到1条待评论的数据！
2019-07-15 19:28:41,019 - INFO - review_us_pool.py[:417] - [taskid: 2235]账户登录日志已成功插入！
2019-07-15 19:28:41,870 - INFO - review_us_pool.py[:423] - [taskid: 2235]对应账户的header和cookies字段已成功修改!
2019-07-15 19:29:16,971 - INFO - review_us_pool.py[:201] - [taskid: 2235]找到目标订单所在的tbody!
2019-07-15 19:29:17,051 - INFO - review_us_pool.py[:238] - [taskid: 2235]卖家尚未发货，暂时不能留评，程序退出！
2019-07-15 19:29:19,200 - INFO - review_us_pool.py[:242] - [taskid: 2235]当前账户操作完毕，关闭当前浏览器！
2019-07-15 19:29:20,201 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000FF14F6FC88>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/46735e050190661c31386576f2ba41f4
2019-07-15 19:29:21,217 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000FF14F8E160>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/46735e050190661c31386576f2ba41f4
2019-07-15 19:29:22,233 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000FF15575828>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/46735e050190661c31386576f2ba41f4
2019-07-15 19:29:26,375 - INFO - review_us_pool.py[:486] - ********************************pool sleep 3s************************************
2019-07-15 19:29:27,719 - INFO - review_us_pool.py[:480] - 成功获取到1条待评论的数据！
2019-07-15 19:31:21,027 - INFO - review_us_pool.py[:417] - [taskid: 2235]账户登录日志已成功插入！
2019-07-15 19:31:21,685 - INFO - review_us_pool.py[:423] - [taskid: 2235]对应账户的header和cookies字段已成功修改!
2019-07-15 19:32:12,758 - INFO - review_us_pool.py[:201] - [taskid: 2235]找到目标订单所在的tbody!
2019-07-15 19:32:12,846 - INFO - review_us_pool.py[:238] - [taskid: 2235]卖家尚未发货，暂时不能留评，程序退出！
2019-07-15 19:32:16,012 - INFO - review_us_pool.py[:242] - [taskid: 2235]当前账户操作完毕，关闭当前浏览器！
2019-07-15 19:32:17,044 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000B2B617FCC0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/d93dac1140e54ffe6eed41fd51606eba
2019-07-15 19:32:18,076 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000B2B619E240>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/d93dac1140e54ffe6eed41fd51606eba
2019-07-15 19:32:19,093 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000B2B619E320>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/d93dac1140e54ffe6eed41fd51606eba
2019-07-15 19:32:23,219 - INFO - review_us_pool.py[:486] - ********************************pool sleep 3s************************************
2019-07-15 19:32:23,969 - INFO - review_us_pool.py[:480] - 成功获取到1条待评论的数据！
2019-07-15 19:34:02,726 - INFO - review_us_pool.py[:417] - [taskid: 2235]账户登录日志已成功插入！
2019-07-15 19:34:05,528 - INFO - review_us_pool.py[:423] - [taskid: 2235]对应账户的header和cookies字段已成功修改!
2019-07-15 19:34:24,750 - INFO - review_us_pool.py[:201] - [taskid: 2235]找到目标订单所在的tbody!
2019-07-15 19:34:24,826 - INFO - review_us_pool.py[:238] - [taskid: 2235]卖家尚未发货，暂时不能留评，程序退出！
2019-07-15 19:34:26,979 - INFO - review_us_pool.py[:242] - [taskid: 2235]当前账户操作完毕，关闭当前浏览器！
2019-07-15 19:34:27,995 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000889A35FC50>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/6668e2cd85f21c00aad053a96f4d5bed
2019-07-15 19:34:29,012 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000889A585A20>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/6668e2cd85f21c00aad053a96f4d5bed
2019-07-15 19:34:30,028 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000889A5A30B8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/6668e2cd85f21c00aad053a96f4d5bed
2019-07-15 19:34:34,170 - INFO - review_us_pool.py[:486] - ********************************pool sleep 3s************************************
2019-07-15 19:34:34,732 - INFO - review_us_pool.py[:480] - 成功获取到1条待评论的数据！
2019-07-15 19:35:56,411 - INFO - review_us_pool.py[:417] - [taskid: 2235]账户登录日志已成功插入！
2019-07-15 19:35:57,013 - INFO - review_us_pool.py[:423] - [taskid: 2235]对应账户的header和cookies字段已成功修改!
2019-07-15 19:36:18,984 - INFO - review_us_pool.py[:201] - [taskid: 2235]找到目标订单所在的tbody!
2019-07-15 19:36:19,066 - INFO - review_us_pool.py[:238] - [taskid: 2235]卖家尚未发货，暂时不能留评，程序退出！
2019-07-15 19:36:22,261 - INFO - review_us_pool.py[:242] - [taskid: 2235]当前账户操作完毕，关闭当前浏览器！
2019-07-15 19:36:23,276 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000000103501CC0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/a80da426134f8a8f4a3748909ee1b603
2019-07-15 19:36:24,309 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000010351E470>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/a80da426134f8a8f4a3748909ee1b603
2019-07-15 19:36:25,340 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000000103725898>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/a80da426134f8a8f4a3748909ee1b603
2019-07-15 19:36:29,545 - INFO - review_us_pool.py[:486] - ********************************pool sleep 3s************************************
2019-07-15 19:36:30,201 - INFO - review_us_pool.py[:480] - 成功获取到1条待评论的数据！
2019-07-15 19:38:04,747 - INFO - review_us_pool.py[:417] - [taskid: 2235]账户登录日志已成功插入！
2019-07-15 19:38:09,443 - INFO - review_us_pool.py[:423] - [taskid: 2235]对应账户的header和cookies字段已成功修改!
2019-07-15 19:39:00,329 - INFO - review_us_pool.py[:201] - [taskid: 2235]找到目标订单所在的tbody!
2019-07-15 19:39:00,417 - INFO - review_us_pool.py[:238] - [taskid: 2235]卖家尚未发货，暂时不能留评，程序退出！
2019-07-15 19:39:03,566 - INFO - review_us_pool.py[:242] - [taskid: 2235]当前账户操作完毕，关闭当前浏览器！
2019-07-15 19:39:04,597 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000BFB49EFCC0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/cfef9bb7b56d46af87f559f75ebd5b6d
2019-07-15 19:39:05,628 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000BFB4C158D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/cfef9bb7b56d46af87f559f75ebd5b6d
2019-07-15 19:39:06,629 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000BFB4C15B00>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/cfef9bb7b56d46af87f559f75ebd5b6d
2019-07-15 19:39:10,772 - INFO - review_us_pool.py[:486] - ********************************pool sleep 3s************************************
2019-07-15 19:39:11,646 - INFO - review_us_pool.py[:480] - 成功获取到1条待评论的数据！
2019-07-15 19:40:42,109 - INFO - review_us_pool.py[:246] - [taskid: 2235]等待超时,或者元素位未完全加载导致定位出错!
2019-07-15 19:40:42,109 - INFO - review_us_pool.py[:247] - [taskid: 2235]关闭当前浏览器，结束当前线程！
2019-07-15 19:40:42,109 - INFO - review_us_pool.py[:248] - [taskid: 2235]系统会自动生成新的线程来执行留评任务！
2019-07-15 19:40:47,346 - INFO - review_us_pool.py[:486] - ********************************pool sleep 3s************************************
2019-07-15 19:40:47,814 - INFO - review_us_pool.py[:480] - 成功获取到1条待评论的数据！
2019-07-15 19:43:23,799 - INFO - review_us_pool.py[:417] - [taskid: 2235]账户登录日志已成功插入！
2019-07-15 19:43:24,784 - INFO - review_us_pool.py[:423] - [taskid: 2235]对应账户的header和cookies字段已成功修改!
2019-07-15 19:43:43,212 - INFO - review_us_pool.py[:201] - [taskid: 2235]找到目标订单所在的tbody!
2019-07-15 19:43:43,296 - INFO - review_us_pool.py[:238] - [taskid: 2235]卖家尚未发货，暂时不能留评，程序退出！
2019-07-15 19:43:46,413 - INFO - review_us_pool.py[:242] - [taskid: 2235]当前账户操作完毕，关闭当前浏览器！
2019-07-15 19:43:47,429 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000DE3AE0FC88>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/2062b51beb151d676a98f7ac936ac99c
2019-07-15 19:43:48,445 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000DE3B4152E8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/2062b51beb151d676a98f7ac936ac99c
2019-07-15 19:43:49,477 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000DE3B415550>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/2062b51beb151d676a98f7ac936ac99c
2019-07-15 19:43:53,572 - INFO - review_us_pool.py[:486] - ********************************pool sleep 3s************************************
2019-07-15 19:43:54,713 - INFO - review_us_pool.py[:480] - 成功获取到1条待评论的数据！
2019-07-15 19:45:33,415 - INFO - review_us_pool.py[:417] - [taskid: 2235]账户登录日志已成功插入！
2019-07-15 19:45:34,114 - INFO - review_us_pool.py[:423] - [taskid: 2235]对应账户的header和cookies字段已成功修改!
2019-07-15 19:46:04,392 - INFO - review_us_pool.py[:201] - [taskid: 2235]找到目标订单所在的tbody!
2019-07-15 19:46:04,480 - INFO - review_us_pool.py[:238] - [taskid: 2235]卖家尚未发货，暂时不能留评，程序退出！
2019-07-15 19:46:06,617 - INFO - review_us_pool.py[:242] - [taskid: 2235]当前账户操作完毕，关闭当前浏览器！
2019-07-15 19:46:07,618 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000053F921FCF8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/215550bc028bff6cb4ed02c071391b65
2019-07-15 19:46:08,634 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000053F923E710>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/215550bc028bff6cb4ed02c071391b65
2019-07-15 19:46:09,649 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000053F923E7F0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/215550bc028bff6cb4ed02c071391b65
2019-07-15 19:46:13,855 - INFO - review_us_pool.py[:486] - ********************************pool sleep 3s************************************
2019-07-15 19:46:14,792 - INFO - review_us_pool.py[:480] - 成功获取到1条待评论的数据！
2019-07-15 19:49:18,957 - INFO - review_us_pool.py[:103] - [taskid: 2235]登录时发现滑块验证码，程序退出！
2019-07-15 19:49:23,090 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000E606F01CC0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/0f90f3e4c8298c0ed8f419abf071786a/element
2019-07-15 19:49:24,123 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000E606F1E630>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/0f90f3e4c8298c0ed8f419abf071786a/element
2019-07-15 19:49:25,138 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000E606F1E978>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/0f90f3e4c8298c0ed8f419abf071786a/element
2019-07-15 19:49:29,312 - INFO - review_us_pool.py[:486] - ********************************pool sleep 3s************************************
2019-07-15 19:49:29,952 - INFO - review_us_pool.py[:480] - 成功获取到1条待评论的数据！
2019-07-15 19:51:03,244 - INFO - review_us_pool.py[:246] - [taskid: 2235]等待超时,或者元素位未完全加载导致定位出错!
2019-07-15 19:51:03,244 - INFO - review_us_pool.py[:247] - [taskid: 2235]关闭当前浏览器，结束当前线程！
2019-07-15 19:51:03,244 - INFO - review_us_pool.py[:248] - [taskid: 2235]系统会自动生成新的线程来执行留评任务！
2019-07-15 19:51:09,496 - INFO - review_us_pool.py[:486] - ********************************pool sleep 3s************************************
2019-07-15 19:51:10,340 - INFO - review_us_pool.py[:480] - 成功获取到1条待评论的数据！
2019-07-15 19:52:47,552 - INFO - review_us_pool.py[:417] - [taskid: 2235]账户登录日志已成功插入！
2019-07-15 19:52:48,346 - INFO - review_us_pool.py[:423] - [taskid: 2235]对应账户的header和cookies字段已成功修改!
2019-07-15 19:53:14,725 - INFO - review_us_pool.py[:201] - [taskid: 2235]找到目标订单所在的tbody!
2019-07-15 19:53:14,809 - INFO - review_us_pool.py[:238] - [taskid: 2235]卖家尚未发货，暂时不能留评，程序退出！
2019-07-15 19:53:16,958 - INFO - review_us_pool.py[:242] - [taskid: 2235]当前账户操作完毕，关闭当前浏览器！
2019-07-15 19:53:17,973 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000F4F5A7FCC0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/fadf057a8657b232643328521b9e949b
2019-07-15 19:53:19,006 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000F4F5A9E0B8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/fadf057a8657b232643328521b9e949b
2019-07-15 19:53:20,021 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000F4F5A9E320>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/fadf057a8657b232643328521b9e949b
2019-07-15 19:53:24,164 - INFO - review_us_pool.py[:486] - ********************************pool sleep 3s************************************
2019-07-15 19:53:25,148 - INFO - review_us_pool.py[:480] - 成功获取到1条待评论的数据！
2019-07-15 19:55:04,049 - INFO - review_us_pool.py[:417] - [taskid: 2235]账户登录日志已成功插入！
2019-07-15 19:55:04,690 - INFO - review_us_pool.py[:423] - [taskid: 2235]对应账户的header和cookies字段已成功修改!
2019-07-15 19:55:34,321 - INFO - review_us_pool.py[:201] - [taskid: 2235]找到目标订单所在的tbody!
2019-07-15 19:55:34,404 - INFO - review_us_pool.py[:238] - [taskid: 2235]卖家尚未发货，暂时不能留评，程序退出！
2019-07-15 19:55:37,530 - INFO - review_us_pool.py[:242] - [taskid: 2235]当前账户操作完毕，关闭当前浏览器！
2019-07-15 19:55:38,531 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000039C155FCF8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/744562726b8b7545e1ab6d19bb7e9d39
2019-07-15 19:55:39,547 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000039C157E240>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/744562726b8b7545e1ab6d19bb7e9d39
2019-07-15 19:55:40,547 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000039C157ED68>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/744562726b8b7545e1ab6d19bb7e9d39
2019-07-15 19:55:44,799 - INFO - review_us_pool.py[:486] - ********************************pool sleep 3s************************************
2019-07-15 19:55:46,143 - INFO - review_us_pool.py[:480] - 成功获取到1条待评论的数据！
2019-07-15 19:57:51,891 - INFO - review_us_pool.py[:417] - [taskid: 2235]账户登录日志已成功插入！
2019-07-15 19:57:53,138 - INFO - review_us_pool.py[:423] - [taskid: 2235]对应账户的header和cookies字段已成功修改!
2019-07-15 19:58:28,863 - INFO - review_us_pool.py[:201] - [taskid: 2235]找到目标订单所在的tbody!
2019-07-15 19:58:28,937 - INFO - review_us_pool.py[:238] - [taskid: 2235]卖家尚未发货，暂时不能留评，程序退出！
2019-07-15 19:58:32,066 - INFO - review_us_pool.py[:242] - [taskid: 2235]当前账户操作完毕，关闭当前浏览器！
2019-07-15 19:58:33,082 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000445E1EFCF8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/43e30ff14298d13c63b1cb631ccd8f72
2019-07-15 19:58:34,098 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000445E20E160>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/43e30ff14298d13c63b1cb631ccd8f72
2019-07-15 19:58:35,098 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000445E7F5898>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/43e30ff14298d13c63b1cb631ccd8f72
2019-07-15 19:58:39,272 - INFO - review_us_pool.py[:486] - ********************************pool sleep 3s************************************
2019-07-15 19:58:40,163 - INFO - review_us_pool.py[:480] - 成功获取到1条待评论的数据！
2019-07-15 20:00:11,510 - INFO - review_us_pool.py[:417] - [taskid: 2235]账户登录日志已成功插入！
2019-07-15 20:00:12,572 - INFO - review_us_pool.py[:423] - [taskid: 2235]对应账户的header和cookies字段已成功修改!
2019-07-15 20:00:36,626 - INFO - review_us_pool.py[:201] - [taskid: 2235]找到目标订单所在的tbody!
2019-07-15 20:00:36,712 - INFO - review_us_pool.py[:238] - [taskid: 2235]卖家尚未发货，暂时不能留评，程序退出！
2019-07-15 20:00:39,884 - INFO - review_us_pool.py[:242] - [taskid: 2235]当前账户操作完毕，关闭当前浏览器！
2019-07-15 20:00:40,899 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000853337FCC0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/e5627528a03cc97eeb8ee0bf20cb881e
2019-07-15 20:00:41,930 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000085335A5358>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/e5627528a03cc97eeb8ee0bf20cb881e
2019-07-15 20:00:42,947 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000085335A55C0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/e5627528a03cc97eeb8ee0bf20cb881e
2019-07-15 20:00:47,074 - INFO - review_us_pool.py[:486] - ********************************pool sleep 3s************************************
2019-07-15 20:00:47,636 - INFO - review_us_pool.py[:480] - 成功获取到1条待评论的数据！
2019-07-15 20:03:07,460 - INFO - review_us_pool.py[:246] - [taskid: 2235]等待超时,或者元素位未完全加载导致定位出错!
2019-07-15 20:03:07,460 - INFO - review_us_pool.py[:247] - [taskid: 2235]关闭当前浏览器，结束当前线程！
2019-07-15 20:03:07,460 - INFO - review_us_pool.py[:248] - [taskid: 2235]系统会自动生成新的线程来执行留评任务！
2019-07-15 20:03:13,725 - INFO - review_us_pool.py[:486] - ********************************pool sleep 3s************************************
2019-07-15 20:03:14,193 - INFO - review_us_pool.py[:480] - 成功获取到1条待评论的数据！
2019-07-15 20:04:23,495 - INFO - review_us_pool.py[:103] - [taskid: 2235]登录时发现滑块验证码，程序退出！
2019-07-15 20:04:27,642 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000A5921E1CF8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/d130100d693c96d82d5935eb1108eed5/element
2019-07-15 20:04:28,658 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000A5921FE668>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/d130100d693c96d82d5935eb1108eed5/element
2019-07-15 20:04:29,689 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000A5921FE9B0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/d130100d693c96d82d5935eb1108eed5/element
2019-07-15 20:04:33,864 - INFO - review_us_pool.py[:486] - ********************************pool sleep 3s************************************
2019-07-15 20:04:34,676 - INFO - review_us_pool.py[:480] - 成功获取到1条待评论的数据！
2019-07-15 20:07:37,704 - INFO - review_us_pool.py[:201] - [taskid: 2235]找到目标订单所在的tbody!
2019-07-15 20:07:37,782 - INFO - review_us_pool.py[:238] - [taskid: 2235]卖家尚未发货，暂时不能留评，程序退出！
2019-07-15 20:07:39,908 - INFO - review_us_pool.py[:242] - [taskid: 2235]当前账户操作完毕，关闭当前浏览器！
2019-07-15 20:07:40,924 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007C23CAFCC0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/a22f5a393e0b08f802a1b83120595601
2019-07-15 20:07:41,940 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007C23CCE2E8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/a22f5a393e0b08f802a1b83120595601
2019-07-15 20:07:42,956 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007C23CCEBA8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/a22f5a393e0b08f802a1b83120595601
2019-07-15 20:07:47,067 - INFO - review_us_pool.py[:486] - ********************************pool sleep 3s************************************
2019-07-15 20:07:48,130 - INFO - review_us_pool.py[:480] - 成功获取到1条待评论的数据！
2019-07-15 20:10:59,301 - INFO - review_us_pool.py[:417] - [taskid: 2235]账户登录日志已成功插入！
2019-07-15 20:11:05,456 - INFO - review_us_pool.py[:423] - [taskid: 2235]对应账户的header和cookies字段已成功修改!
2019-07-15 20:11:53,571 - INFO - review_us_pool.py[:201] - [taskid: 2235]找到目标订单所在的tbody!
2019-07-15 20:11:53,654 - INFO - review_us_pool.py[:238] - [taskid: 2235]卖家尚未发货，暂时不能留评，程序退出！
2019-07-15 20:11:55,775 - INFO - review_us_pool.py[:242] - [taskid: 2235]当前账户操作完毕，关闭当前浏览器！
2019-07-15 20:11:56,790 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000001166A3FCC0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/55ecd13cb60534e3a3ad6bc26563cac7
2019-07-15 20:11:57,806 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000001166C65358>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/55ecd13cb60534e3a3ad6bc26563cac7
2019-07-15 20:11:58,822 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000001166C655C0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/55ecd13cb60534e3a3ad6bc26563cac7
2019-07-15 20:12:02,981 - INFO - review_us_pool.py[:486] - ********************************pool sleep 3s************************************
2019-07-15 20:12:09,123 - INFO - review_us_pool.py[:480] - 成功获取到1条待评论的数据！
2019-07-15 20:13:38,575 - INFO - review_us_pool.py[:417] - [taskid: 2235]账户登录日志已成功插入！
2019-07-15 20:13:40,937 - INFO - review_us_pool.py[:423] - [taskid: 2235]对应账户的header和cookies字段已成功修改!
2019-07-15 20:14:02,172 - INFO - review_us_pool.py[:201] - [taskid: 2235]找到目标订单所在的tbody!
2019-07-15 20:14:02,262 - INFO - review_us_pool.py[:238] - [taskid: 2235]卖家尚未发货，暂时不能留评，程序退出！
2019-07-15 20:14:05,393 - INFO - review_us_pool.py[:242] - [taskid: 2235]当前账户操作完毕，关闭当前浏览器！
2019-07-15 20:14:06,409 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000A2322AFCC0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/a37bdb19c31a5eb8f618ae6361f4b5b1
2019-07-15 20:14:07,409 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000A2324D5358>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/a37bdb19c31a5eb8f618ae6361f4b5b1
2019-07-15 20:14:08,425 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000A2324D55C0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/a37bdb19c31a5eb8f618ae6361f4b5b1
2019-07-15 20:14:12,615 - INFO - review_us_pool.py[:486] - ********************************pool sleep 3s************************************
2019-07-15 20:14:14,693 - INFO - review_us_pool.py[:480] - 成功获取到1条待评论的数据！
2019-07-15 20:16:27,227 - INFO - review_us_pool.py[:417] - [taskid: 2235]账户登录日志已成功插入！
2019-07-15 20:16:28,154 - INFO - review_us_pool.py[:423] - [taskid: 2235]对应账户的header和cookies字段已成功修改!
2019-07-15 20:17:27,432 - INFO - review_us_pool.py[:201] - [taskid: 2235]找到目标订单所在的tbody!
2019-07-15 20:17:27,508 - INFO - review_us_pool.py[:238] - [taskid: 2235]卖家尚未发货，暂时不能留评，程序退出！
2019-07-15 20:17:30,633 - INFO - review_us_pool.py[:242] - [taskid: 2235]当前账户操作完毕，关闭当前浏览器！
2019-07-15 20:17:31,649 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000F0B43FFC50>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/2e20d628a5765f4fe01c13b334c053cf
2019-07-15 20:17:32,650 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000F0B441E3C8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/2e20d628a5765f4fe01c13b334c053cf
2019-07-15 20:17:33,665 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000F0B441E6D8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/2e20d628a5765f4fe01c13b334c053cf
2019-07-15 20:17:37,777 - INFO - review_us_pool.py[:486] - ********************************pool sleep 3s************************************
2019-07-15 20:17:38,464 - INFO - review_us_pool.py[:480] - 成功获取到1条待评论的数据！
2019-07-15 20:20:02,189 - INFO - review_us_pool.py[:246] - [taskid: 2235]等待超时,或者元素位未完全加载导致定位出错!
2019-07-15 20:20:02,189 - INFO - review_us_pool.py[:247] - [taskid: 2235]关闭当前浏览器，结束当前线程！
2019-07-15 20:20:02,189 - INFO - review_us_pool.py[:248] - [taskid: 2235]系统会自动生成新的线程来执行留评任务！
2019-07-15 20:20:08,409 - INFO - review_us_pool.py[:486] - ********************************pool sleep 3s************************************
2019-07-15 20:20:08,972 - INFO - review_us_pool.py[:480] - 成功获取到1条待评论的数据！
2019-07-15 20:21:35,933 - INFO - review_us_pool.py[:417] - [taskid: 2235]账户登录日志已成功插入！
2019-07-15 20:21:37,133 - INFO - review_us_pool.py[:423] - [taskid: 2235]对应账户的header和cookies字段已成功修改!
2019-07-15 20:22:03,942 - INFO - review_us_pool.py[:201] - [taskid: 2235]找到目标订单所在的tbody!
2019-07-15 20:22:04,025 - INFO - review_us_pool.py[:238] - [taskid: 2235]卖家尚未发货，暂时不能留评，程序退出！
2019-07-15 20:22:07,135 - INFO - review_us_pool.py[:242] - [taskid: 2235]当前账户操作完毕，关闭当前浏览器！
2019-07-15 20:22:08,150 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000F1DA6DFC50>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/3803e7f2675b86ca97d3eabc84291bcb
2019-07-15 20:22:09,182 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000F1DA6FE400>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/3803e7f2675b86ca97d3eabc84291bcb
2019-07-15 20:22:10,183 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000F1DA905828>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/3803e7f2675b86ca97d3eabc84291bcb
2019-07-15 20:22:14,388 - INFO - review_us_pool.py[:486] - ********************************pool sleep 3s************************************
2019-07-15 20:22:15,356 - INFO - review_us_pool.py[:480] - 成功获取到1条待评论的数据！
2019-07-15 20:24:05,079 - INFO - review_us_pool.py[:417] - [taskid: 2235]账户登录日志已成功插入！
2019-07-15 20:24:11,983 - INFO - review_us_pool.py[:423] - [taskid: 2235]对应账户的header和cookies字段已成功修改!
2019-07-15 20:24:34,337 - INFO - review_us_pool.py[:201] - [taskid: 2235]找到目标订单所在的tbody!
2019-07-15 20:24:34,553 - INFO - review_us_pool.py[:238] - [taskid: 2235]卖家尚未发货，暂时不能留评，程序退出！
2019-07-15 20:24:38,106 - INFO - review_us_pool.py[:242] - [taskid: 2235]当前账户操作完毕，关闭当前浏览器！
2019-07-15 20:24:39,188 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000003E755E1CC0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/b38635210429598c4d540caa1391352f
2019-07-15 20:24:40,324 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000003E75BE5358>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/b38635210429598c4d540caa1391352f
2019-07-15 20:24:41,389 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000003E75BE55C0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/b38635210429598c4d540caa1391352f
2019-07-15 20:24:45,720 - INFO - review_us_pool.py[:486] - ********************************pool sleep 3s************************************
2019-07-15 20:24:47,399 - INFO - review_us_pool.py[:480] - 成功获取到1条待评论的数据！
2019-07-15 20:27:15,787 - INFO - review_us_pool.py[:417] - [taskid: 2235]账户登录日志已成功插入！
2019-07-15 20:27:17,247 - INFO - review_us_pool.py[:423] - [taskid: 2235]对应账户的header和cookies字段已成功修改!
2019-07-15 20:27:47,888 - INFO - review_us_pool.py[:201] - [taskid: 2235]找到目标订单所在的tbody!
2019-07-15 20:27:48,064 - INFO - review_us_pool.py[:238] - [taskid: 2235]卖家尚未发货，暂时不能留评，程序退出！
2019-07-15 20:27:50,366 - INFO - review_us_pool.py[:242] - [taskid: 2235]当前账户操作完毕，关闭当前浏览器！
2019-07-15 20:27:51,419 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000A2C531FCF8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/0d329018daf0eaa0bdf04631953f983f
2019-07-15 20:27:52,458 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000A2C5925390>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/0d329018daf0eaa0bdf04631953f983f
2019-07-15 20:27:53,520 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000A2C5925BA8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/0d329018daf0eaa0bdf04631953f983f
2019-07-15 20:27:57,749 - INFO - review_us_pool.py[:486] - ********************************pool sleep 3s************************************
2019-07-15 20:28:00,511 - INFO - review_us_pool.py[:480] - 成功获取到1条待评论的数据！
2019-07-15 20:29:49,845 - INFO - review_us_pool.py[:417] - [taskid: 2235]账户登录日志已成功插入！
2019-07-15 20:29:50,719 - INFO - review_us_pool.py[:423] - [taskid: 2235]对应账户的header和cookies字段已成功修改!
2019-07-15 20:30:24,894 - INFO - review_us_pool.py[:201] - [taskid: 2235]找到目标订单所在的tbody!
2019-07-15 20:30:25,495 - INFO - review_us_pool.py[:238] - [taskid: 2235]卖家尚未发货，暂时不能留评，程序退出！
2019-07-15 20:30:29,088 - INFO - review_us_pool.py[:242] - [taskid: 2235]当前账户操作完毕，关闭当前浏览器！
2019-07-15 20:30:30,141 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000EAE9971CC0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/f93e8a608ac37a2c0bb21c96a59e4fbd
2019-07-15 20:30:31,150 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000EAE9F75358>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/f93e8a608ac37a2c0bb21c96a59e4fbd
2019-07-15 20:30:32,160 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000EAE9F755C0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/f93e8a608ac37a2c0bb21c96a59e4fbd
2019-07-15 20:30:36,387 - INFO - review_us_pool.py[:486] - ********************************pool sleep 3s************************************
2019-07-15 20:30:38,281 - INFO - review_us_pool.py[:480] - 成功获取到1条待评论的数据！
2019-07-15 20:34:27,842 - INFO - review_us_pool.py[:246] - [taskid: 2235]等待超时,或者元素位未完全加载导致定位出错!
2019-07-15 20:34:27,844 - INFO - review_us_pool.py[:247] - [taskid: 2235]关闭当前浏览器，结束当前线程！
2019-07-15 20:34:27,844 - INFO - review_us_pool.py[:248] - [taskid: 2235]系统会自动生成新的线程来执行留评任务！
2019-07-15 20:34:34,328 - INFO - review_us_pool.py[:486] - ********************************pool sleep 3s************************************
2019-07-15 20:34:35,189 - INFO - review_us_pool.py[:480] - 成功获取到1条待评论的数据！
2019-07-15 20:36:21,611 - INFO - review_us_pool.py[:417] - [taskid: 2235]账户登录日志已成功插入！
2019-07-15 20:36:22,979 - INFO - review_us_pool.py[:423] - [taskid: 2235]对应账户的header和cookies字段已成功修改!
2019-07-15 20:36:44,752 - INFO - review_us_pool.py[:201] - [taskid: 2235]找到目标订单所在的tbody!
2019-07-15 20:36:44,856 - INFO - review_us_pool.py[:238] - [taskid: 2235]卖家尚未发货，暂时不能留评，程序退出！
2019-07-15 20:36:48,033 - INFO - review_us_pool.py[:242] - [taskid: 2235]当前账户操作完毕，关闭当前浏览器！
2019-07-15 20:36:49,037 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000008FB6CFCC0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/2e8b8165b8829ce91fdaaf85d5fafe04
2019-07-15 20:36:50,033 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000008FBCD5358>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/2e8b8165b8829ce91fdaaf85d5fafe04
2019-07-15 20:36:51,038 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000008FBCD56A0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/2e8b8165b8829ce91fdaaf85d5fafe04
2019-07-15 20:36:55,207 - INFO - review_us_pool.py[:486] - ********************************pool sleep 3s************************************
2019-07-15 20:37:03,844 - INFO - review_us_pool.py[:480] - 成功获取到1条待评论的数据！
2019-07-15 20:38:33,989 - INFO - review_us_pool.py[:246] - [taskid: 2235]等待超时,或者元素位未完全加载导致定位出错!
2019-07-15 20:38:33,990 - INFO - review_us_pool.py[:247] - [taskid: 2235]关闭当前浏览器，结束当前线程！
2019-07-15 20:38:33,990 - INFO - review_us_pool.py[:248] - [taskid: 2235]系统会自动生成新的线程来执行留评任务！
2019-07-15 20:38:39,208 - INFO - review_us_pool.py[:486] - ********************************pool sleep 3s************************************
2019-07-15 20:38:40,875 - INFO - review_us_pool.py[:480] - 成功获取到1条待评论的数据！
2019-07-15 20:40:11,434 - INFO - review_us_pool.py[:246] - [taskid: 2235]等待超时,或者元素位未完全加载导致定位出错!
2019-07-15 20:40:11,435 - INFO - review_us_pool.py[:247] - [taskid: 2235]关闭当前浏览器，结束当前线程！
2019-07-15 20:40:11,436 - INFO - review_us_pool.py[:248] - [taskid: 2235]系统会自动生成新的线程来执行留评任务！
2019-07-15 20:40:17,632 - INFO - review_us_pool.py[:486] - ********************************pool sleep 3s************************************
2019-07-15 20:40:18,323 - INFO - review_us_pool.py[:480] - 成功获取到1条待评论的数据！
2019-07-15 20:41:53,071 - INFO - review_us_pool.py[:417] - [taskid: 2235]账户登录日志已成功插入！
2019-07-15 20:41:59,240 - INFO - review_us_pool.py[:423] - [taskid: 2235]对应账户的header和cookies字段已成功修改!
2019-07-15 20:42:18,093 - INFO - review_us_pool.py[:201] - [taskid: 2235]找到目标订单所在的tbody!
2019-07-15 20:42:18,180 - INFO - review_us_pool.py[:238] - [taskid: 2235]卖家尚未发货，暂时不能留评，程序退出！
2019-07-15 20:42:21,625 - INFO - review_us_pool.py[:242] - [taskid: 2235]当前账户操作完毕，关闭当前浏览器！
2019-07-15 20:42:22,687 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000A57C21FCF8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/9d071afccca84b70723ad3a89cd7070f
2019-07-15 20:42:23,787 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000A57C825358>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/9d071afccca84b70723ad3a89cd7070f
2019-07-15 20:42:24,901 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000A57C8255C0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/9d071afccca84b70723ad3a89cd7070f
2019-07-15 20:42:29,075 - INFO - review_us_pool.py[:486] - ********************************pool sleep 3s************************************
2019-07-15 20:42:30,250 - INFO - review_us_pool.py[:480] - 成功获取到1条待评论的数据！
2019-07-15 20:45:32,155 - INFO - review_us_pool.py[:246] - [taskid: 2235]等待超时,或者元素位未完全加载导致定位出错!
2019-07-15 20:45:32,156 - INFO - review_us_pool.py[:247] - [taskid: 2235]关闭当前浏览器，结束当前线程！
2019-07-15 20:45:32,156 - INFO - review_us_pool.py[:248] - [taskid: 2235]系统会自动生成新的线程来执行留评任务！
2019-07-15 20:45:38,521 - INFO - review_us_pool.py[:486] - ********************************pool sleep 3s************************************
2019-07-15 20:45:40,077 - INFO - review_us_pool.py[:480] - 成功获取到1条待评论的数据！
2019-07-15 20:47:11,581 - INFO - review_us_pool.py[:246] - [taskid: 2235]等待超时,或者元素位未完全加载导致定位出错!
2019-07-15 20:47:11,582 - INFO - review_us_pool.py[:247] - [taskid: 2235]关闭当前浏览器，结束当前线程！
2019-07-15 20:47:11,583 - INFO - review_us_pool.py[:248] - [taskid: 2235]系统会自动生成新的线程来执行留评任务！
2019-07-15 20:47:16,875 - INFO - review_us_pool.py[:486] - ********************************pool sleep 3s************************************
2019-07-15 20:47:18,019 - INFO - review_us_pool.py[:480] - 成功获取到1条待评论的数据！
2019-07-15 20:49:49,060 - INFO - review_us_pool.py[:246] - [taskid: 2235]等待超时,或者元素位未完全加载导致定位出错!
2019-07-15 20:49:50,043 - INFO - review_us_pool.py[:247] - [taskid: 2235]关闭当前浏览器，结束当前线程！
2019-07-15 20:49:50,044 - INFO - review_us_pool.py[:248] - [taskid: 2235]系统会自动生成新的线程来执行留评任务！
2019-07-15 20:49:58,053 - INFO - review_us_pool.py[:486] - ********************************pool sleep 3s************************************
2019-07-15 20:50:02,315 - INFO - review_us_pool.py[:480] - 成功获取到1条待评论的数据！
2019-07-15 20:52:52,813 - INFO - review_us_pool.py[:417] - [taskid: 2235]账户登录日志已成功插入！
2019-07-15 20:52:53,750 - INFO - review_us_pool.py[:423] - [taskid: 2235]对应账户的header和cookies字段已成功修改!
2019-07-15 20:53:33,857 - INFO - review_us_pool.py[:201] - [taskid: 2235]找到目标订单所在的tbody!
2019-07-15 20:53:33,879 - INFO - review_us_pool.py[:246] - [taskid: 2235]等待超时,或者元素位未完全加载导致定位出错!
2019-07-15 20:53:33,881 - INFO - review_us_pool.py[:247] - [taskid: 2235]关闭当前浏览器，结束当前线程！
2019-07-15 20:53:33,882 - INFO - review_us_pool.py[:248] - [taskid: 2235]系统会自动生成新的线程来执行留评任务！
2019-07-15 20:53:39,195 - INFO - review_us_pool.py[:486] - ********************************pool sleep 3s************************************
2019-07-15 20:53:41,012 - INFO - review_us_pool.py[:480] - 成功获取到1条待评论的数据！
2019-07-15 20:56:05,985 - INFO - review_us_pool.py[:246] - [taskid: 2235]等待超时,或者元素位未完全加载导致定位出错!
2019-07-15 20:56:05,986 - INFO - review_us_pool.py[:247] - [taskid: 2235]关闭当前浏览器，结束当前线程！
2019-07-15 20:56:05,986 - INFO - review_us_pool.py[:248] - [taskid: 2235]系统会自动生成新的线程来执行留评任务！
2019-07-15 20:56:12,319 - INFO - review_us_pool.py[:486] - ********************************pool sleep 3s************************************
2019-07-15 20:56:12,982 - INFO - review_us_pool.py[:480] - 成功获取到1条待评论的数据！
2019-07-15 20:58:44,451 - INFO - review_us_pool.py[:246] - [taskid: 2235]等待超时,或者元素位未完全加载导致定位出错!
2019-07-15 20:58:44,452 - INFO - review_us_pool.py[:247] - [taskid: 2235]关闭当前浏览器，结束当前线程！
2019-07-15 20:58:44,453 - INFO - review_us_pool.py[:248] - [taskid: 2235]系统会自动生成新的线程来执行留评任务！
2019-07-15 20:58:49,886 - INFO - review_us_pool.py[:486] - ********************************pool sleep 3s************************************
2019-07-15 20:58:50,493 - INFO - review_us_pool.py[:480] - 成功获取到1条待评论的数据！
2019-07-15 21:01:20,795 - INFO - review_us_pool.py[:417] - [taskid: 2235]账户登录日志已成功插入！
2019-07-15 21:01:24,632 - INFO - review_us_pool.py[:423] - [taskid: 2235]对应账户的header和cookies字段已成功修改!
2019-07-15 21:03:17,147 - INFO - review_us_pool.py[:201] - [taskid: 2235]找到目标订单所在的tbody!
2019-07-15 21:03:17,171 - INFO - review_us_pool.py[:246] - [taskid: 2235]等待超时,或者元素位未完全加载导致定位出错!
2019-07-15 21:03:17,173 - INFO - review_us_pool.py[:247] - [taskid: 2235]关闭当前浏览器，结束当前线程！
2019-07-15 21:03:17,174 - INFO - review_us_pool.py[:248] - [taskid: 2235]系统会自动生成新的线程来执行留评任务！
2019-07-15 21:03:23,482 - INFO - review_us_pool.py[:486] - ********************************pool sleep 3s************************************
2019-07-15 21:03:24,150 - INFO - review_us_pool.py[:480] - 成功获取到1条待评论的数据！
2019-07-15 21:05:12,661 - INFO - review_us_pool.py[:417] - [taskid: 2235]账户登录日志已成功插入！
2019-07-15 21:06:38,399 - INFO - review_us_pool.py[:423] - [taskid: 2235]对应账户的header和cookies字段已成功修改!
2019-07-15 21:06:58,367 - INFO - review_us_pool.py[:201] - [taskid: 2235]找到目标订单所在的tbody!
2019-07-15 21:06:58,389 - INFO - review_us_pool.py[:246] - [taskid: 2235]等待超时,或者元素位未完全加载导致定位出错!
2019-07-15 21:06:58,390 - INFO - review_us_pool.py[:247] - [taskid: 2235]关闭当前浏览器，结束当前线程！
2019-07-15 21:06:58,391 - INFO - review_us_pool.py[:248] - [taskid: 2235]系统会自动生成新的线程来执行留评任务！
2019-07-15 21:07:04,699 - INFO - review_us_pool.py[:486] - ********************************pool sleep 3s************************************
2019-07-15 21:08:30,461 - INFO - review_us_pool.py[:490] - 任务系统出错，程序[sleep 30s]...
2019-07-15 21:10:32,261 - INFO - review_us_pool.py[:490] - 任务系统出错，程序[sleep 30s]...
2019-07-15 21:12:25,042 - INFO - review_us_pool.py[:490] - 任务系统出错，程序[sleep 30s]...
2019-07-15 21:14:20,855 - INFO - review_us_pool.py[:490] - 任务系统出错，程序[sleep 30s]...
2019-07-15 21:16:16,590 - INFO - review_us_pool.py[:490] - 任务系统出错，程序[sleep 30s]...
2019-07-15 21:17:04,720 - INFO - review_us_pool.py[:490] - 任务系统出错，程序[sleep 30s]...
2019-07-15 21:17:50,692 - INFO - review_us_pool.py[:490] - 任务系统出错，程序[sleep 30s]...
2019-07-15 21:18:30,256 - INFO - review_us_pool.py[:480] - 成功获取到1条待评论的数据！
2019-07-15 21:19:54,619 - INFO - review_us_pool.py[:417] - [taskid: 2235]账户登录日志已成功插入！
2019-07-15 21:19:56,018 - INFO - review_us_pool.py[:423] - [taskid: 2235]对应账户的header和cookies字段已成功修改!
2019-07-15 21:20:14,294 - INFO - review_us_pool.py[:201] - [taskid: 2235]找到目标订单所在的tbody!
2019-07-15 21:20:14,312 - INFO - review_us_pool.py[:246] - [taskid: 2235]等待超时,或者元素位未完全加载导致定位出错!
2019-07-15 21:20:14,313 - INFO - review_us_pool.py[:247] - [taskid: 2235]关闭当前浏览器，结束当前线程！
2019-07-15 21:20:14,313 - INFO - review_us_pool.py[:248] - [taskid: 2235]系统会自动生成新的线程来执行留评任务！
2019-07-15 21:20:19,652 - INFO - review_us_pool.py[:486] - ********************************pool sleep 3s************************************
2019-07-15 21:20:20,302 - INFO - review_us_pool.py[:480] - 成功获取到1条待评论的数据！
2019-07-15 21:22:07,914 - INFO - review_us_pool.py[:417] - [taskid: 2235]账户登录日志已成功插入！
2019-07-15 21:22:08,677 - INFO - review_us_pool.py[:423] - [taskid: 2235]对应账户的header和cookies字段已成功修改!
2019-07-15 21:22:36,890 - INFO - review_us_pool.py[:201] - [taskid: 2235]找到目标订单所在的tbody!
2019-07-15 21:22:36,913 - INFO - review_us_pool.py[:246] - [taskid: 2235]等待超时,或者元素位未完全加载导致定位出错!
2019-07-15 21:22:36,914 - INFO - review_us_pool.py[:247] - [taskid: 2235]关闭当前浏览器，结束当前线程！
2019-07-15 21:22:36,915 - INFO - review_us_pool.py[:248] - [taskid: 2235]系统会自动生成新的线程来执行留评任务！
2019-07-15 21:22:42,282 - INFO - review_us_pool.py[:486] - ********************************pool sleep 3s************************************
2019-07-15 21:22:43,206 - INFO - review_us_pool.py[:480] - 成功获取到1条待评论的数据！
2019-07-15 21:25:21,049 - INFO - review_us_pool.py[:246] - [taskid: 2235]等待超时,或者元素位未完全加载导致定位出错!
2019-07-15 21:25:21,051 - INFO - review_us_pool.py[:247] - [taskid: 2235]关闭当前浏览器，结束当前线程！
2019-07-15 21:25:21,052 - INFO - review_us_pool.py[:248] - [taskid: 2235]系统会自动生成新的线程来执行留评任务！
2019-07-15 21:25:26,377 - INFO - review_us_pool.py[:486] - ********************************pool sleep 3s************************************
2019-07-15 21:25:27,423 - INFO - review_us_pool.py[:480] - 成功获取到1条待评论的数据！
2019-07-15 21:27:30,266 - INFO - review_us_pool.py[:417] - [taskid: 2235]账户登录日志已成功插入！
2019-07-15 21:27:32,674 - INFO - review_us_pool.py[:423] - [taskid: 2235]对应账户的header和cookies字段已成功修改!
2019-07-15 21:28:20,666 - INFO - review_us_pool.py[:201] - [taskid: 2235]找到目标订单所在的tbody!
2019-07-15 21:28:20,697 - INFO - review_us_pool.py[:246] - [taskid: 2235]等待超时,或者元素位未完全加载导致定位出错!
2019-07-15 21:28:20,698 - INFO - review_us_pool.py[:247] - [taskid: 2235]关闭当前浏览器，结束当前线程！
2019-07-15 21:28:20,699 - INFO - review_us_pool.py[:248] - [taskid: 2235]系统会自动生成新的线程来执行留评任务！
2019-07-15 21:28:26,968 - INFO - review_us_pool.py[:486] - ********************************pool sleep 3s************************************
2019-07-15 21:28:28,173 - INFO - review_us_pool.py[:480] - 成功获取到1条待评论的数据！
2019-07-15 21:29:59,568 - INFO - review_us_pool.py[:246] - [taskid: 2235]等待超时,或者元素位未完全加载导致定位出错!
2019-07-15 21:29:59,569 - INFO - review_us_pool.py[:247] - [taskid: 2235]关闭当前浏览器，结束当前线程！
2019-07-15 21:29:59,569 - INFO - review_us_pool.py[:248] - [taskid: 2235]系统会自动生成新的线程来执行留评任务！
2019-07-15 21:30:04,780 - INFO - review_us_pool.py[:486] - ********************************pool sleep 3s************************************
2019-07-15 21:30:06,278 - INFO - review_us_pool.py[:480] - 成功获取到1条待评论的数据！
2019-07-15 21:32:14,574 - INFO - review_us_pool.py[:246] - [taskid: 2235]等待超时,或者元素位未完全加载导致定位出错!
2019-07-15 21:32:14,575 - INFO - review_us_pool.py[:247] - [taskid: 2235]关闭当前浏览器，结束当前线程！
2019-07-15 21:32:14,576 - INFO - review_us_pool.py[:248] - [taskid: 2235]系统会自动生成新的线程来执行留评任务！
2019-07-15 21:32:19,838 - INFO - review_us_pool.py[:486] - ********************************pool sleep 3s************************************
2019-07-15 21:32:20,492 - INFO - review_us_pool.py[:480] - 成功获取到1条待评论的数据！
2019-07-15 21:34:58,025 - INFO - review_us_pool.py[:246] - [taskid: 2235]等待超时,或者元素位未完全加载导致定位出错!
